// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsPrivacyAndSecurityUpdateAddonsCmd(flags *rootFlags) *cobra.Command {
	var bodyAppTrustInformationDataAccessAndStorageAppProcessEUDOutsideAtlassian bool
	var bodyAppTrustInformationDataAccessAndStorageAppStoresEUDOutsideAtlassian bool
	var bodyAppTrustInformationDataAccessAndStorageIsSameDataProcessedAndStored bool
	var bodyAppTrustInformationDataAccessAndStorageTypesOfDataAccessed string
	var bodyAppTrustInformationDataAccessAndStorageTypesOfDataStored string
	var bodyAppTrustInformationDataResidencyCountriesWhereEndUserDataStored string
	var bodyAppTrustInformationDataResidencyInScopeDataTypes string
	var bodyAppTrustInformationDataResidencyIsDataResidencySupported string
	var bodyAppTrustInformationDataResidencyRealmMigrationSupported bool
	var bodyAppTrustInformationDataRetentionIsCustomRetentionPeriodAllowed bool
	var bodyAppTrustInformationDataRetentionIsDataRetentionSupported bool
	var bodyAppTrustInformationDataRetentionIsRetentionDurationIndefinite bool
	var bodyAppTrustInformationLogDetailsLogEUDShareWithThirdParty bool
	var bodyAppTrustInformationLogDetailsLogEndUserData bool
	var bodyAppTrustInformationLogDetailsLogProcessAndOrStoreEUDOutsideAtlassian bool
	var bodyAppTrustInformationLogDetailsLogsIntegralForAppFunctionality bool
	var bodyAppTrustInformationSecurityCompliantCertifications string
	var bodyAppTrustInformationSecurityHasCompliantCertifications bool
	var bodyAppTrustInformationSecurityIsDiskEncryptionSupported bool
	var bodyAppTrustInformationSecurityPermissionsJustification string
	var bodyAppTrustInformationSecurityPublicSecurityPoliciesLink string
	var bodyAppTrustInformationSecurityRequiresUsersToProvidePATs bool
	var bodyAppTrustInformationSecuritySecurityContact string
	var bodyAppTrustInformationThirdPartyInformationDataSubProcessors string
	var bodyAppTrustInformationThirdPartyInformationIsEndUserDataShared bool
	var bodyAppTrustInformationThirdPartyInformationThirdPartyDetails string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-addons <addonKey>",
		Short:       "Create/Update draft version of privacy and security info for the specified app.",
		Example:     "  jira-pp-cli-pp-cli addons privacy-and-security update-addons your-token-here",
		Annotations: map[string]string{"pp:endpoint": "privacy-and-security.update-addons", "pp:method": "PUT", "pp:path": "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/privacy-and-security"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/privacy-and-security"
			path = replacePathParam(path, "addonKey", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAppTrustInformation := map[string]any{}
					{
						nestedAppTrustInformationDataAccessAndStorage := map[string]any{}
						if cmd.Flags().Changed("app-trust-information-data-access-and-storage-app-process-eud-outside-atlassian") {
							nestedAppTrustInformationDataAccessAndStorage["appProcessEUDOutsideAtlassian"] = bodyAppTrustInformationDataAccessAndStorageAppProcessEUDOutsideAtlassian
						}
						if cmd.Flags().Changed("app-trust-information-data-access-and-storage-app-stores-eud-outside-atlassian") {
							nestedAppTrustInformationDataAccessAndStorage["appStoresEUDOutsideAtlassian"] = bodyAppTrustInformationDataAccessAndStorageAppStoresEUDOutsideAtlassian
						}
						if cmd.Flags().Changed("app-trust-information-data-access-and-storage-is-same-data-processed-and-stored") {
							nestedAppTrustInformationDataAccessAndStorage["isSameDataProcessedAndStored"] = bodyAppTrustInformationDataAccessAndStorageIsSameDataProcessedAndStored
						}
						if bodyAppTrustInformationDataAccessAndStorageTypesOfDataAccessed != "" {
							var parsedAppTrustInformationDataAccessAndStorageTypesOfDataAccessed any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationDataAccessAndStorageTypesOfDataAccessed), &parsedAppTrustInformationDataAccessAndStorageTypesOfDataAccessed); err != nil {
								return fmt.Errorf("parsing --app-trust-information-data-access-and-storage-types-of-data-accessed JSON: %w", err)
							}
							nestedAppTrustInformationDataAccessAndStorage["typesOfDataAccessed"] = parsedAppTrustInformationDataAccessAndStorageTypesOfDataAccessed
						}
						if bodyAppTrustInformationDataAccessAndStorageTypesOfDataStored != "" {
							var parsedAppTrustInformationDataAccessAndStorageTypesOfDataStored any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationDataAccessAndStorageTypesOfDataStored), &parsedAppTrustInformationDataAccessAndStorageTypesOfDataStored); err != nil {
								return fmt.Errorf("parsing --app-trust-information-data-access-and-storage-types-of-data-stored JSON: %w", err)
							}
							nestedAppTrustInformationDataAccessAndStorage["typesOfDataStored"] = parsedAppTrustInformationDataAccessAndStorageTypesOfDataStored
						}
						if len(nestedAppTrustInformationDataAccessAndStorage) > 0 {
							nestedAppTrustInformation["dataAccessAndStorage"] = nestedAppTrustInformationDataAccessAndStorage
						}
					}
					{
						nestedAppTrustInformationDataResidency := map[string]any{}
						if bodyAppTrustInformationDataResidencyCountriesWhereEndUserDataStored != "" {
							var parsedAppTrustInformationDataResidencyCountriesWhereEndUserDataStored any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationDataResidencyCountriesWhereEndUserDataStored), &parsedAppTrustInformationDataResidencyCountriesWhereEndUserDataStored); err != nil {
								return fmt.Errorf("parsing --app-trust-information-data-residency-countries-where-end-user-data-stored JSON: %w", err)
							}
							nestedAppTrustInformationDataResidency["countriesWhereEndUserDataStored"] = parsedAppTrustInformationDataResidencyCountriesWhereEndUserDataStored
						}
						if bodyAppTrustInformationDataResidencyInScopeDataTypes != "" {
							var parsedAppTrustInformationDataResidencyInScopeDataTypes any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationDataResidencyInScopeDataTypes), &parsedAppTrustInformationDataResidencyInScopeDataTypes); err != nil {
								return fmt.Errorf("parsing --app-trust-information-data-residency-in-scope-data-types JSON: %w", err)
							}
							nestedAppTrustInformationDataResidency["inScopeDataTypes"] = parsedAppTrustInformationDataResidencyInScopeDataTypes
						}
						if bodyAppTrustInformationDataResidencyIsDataResidencySupported != "" {
							nestedAppTrustInformationDataResidency["isDataResidencySupported"] = bodyAppTrustInformationDataResidencyIsDataResidencySupported
						}
						if cmd.Flags().Changed("app-trust-information-data-residency-realm-migration-supported") {
							nestedAppTrustInformationDataResidency["realmMigrationSupported"] = bodyAppTrustInformationDataResidencyRealmMigrationSupported
						}
						if len(nestedAppTrustInformationDataResidency) > 0 {
							nestedAppTrustInformation["dataResidency"] = nestedAppTrustInformationDataResidency
						}
					}
					{
						nestedAppTrustInformationDataRetention := map[string]any{}
						if cmd.Flags().Changed("app-trust-information-data-retention-is-custom-retention-period-allowed") {
							nestedAppTrustInformationDataRetention["isCustomRetentionPeriodAllowed"] = bodyAppTrustInformationDataRetentionIsCustomRetentionPeriodAllowed
						}
						if cmd.Flags().Changed("app-trust-information-data-retention-is-data-retention-supported") {
							nestedAppTrustInformationDataRetention["isDataRetentionSupported"] = bodyAppTrustInformationDataRetentionIsDataRetentionSupported
						}
						if cmd.Flags().Changed("app-trust-information-data-retention-is-retention-duration-indefinite") {
							nestedAppTrustInformationDataRetention["isRetentionDurationIndefinite"] = bodyAppTrustInformationDataRetentionIsRetentionDurationIndefinite
						}
						if len(nestedAppTrustInformationDataRetention) > 0 {
							nestedAppTrustInformation["dataRetention"] = nestedAppTrustInformationDataRetention
						}
					}
					{
						nestedAppTrustInformationLogDetails := map[string]any{}
						if cmd.Flags().Changed("app-trust-information-log-details-log-eud-share-with-third-party") {
							nestedAppTrustInformationLogDetails["logEUDShareWithThirdParty"] = bodyAppTrustInformationLogDetailsLogEUDShareWithThirdParty
						}
						if cmd.Flags().Changed("app-trust-information-log-details-log-end-user-data") {
							nestedAppTrustInformationLogDetails["logEndUserData"] = bodyAppTrustInformationLogDetailsLogEndUserData
						}
						if cmd.Flags().Changed("app-trust-information-log-details-log-process-and-or-store-eud-outside-atlassian") {
							nestedAppTrustInformationLogDetails["logProcessAndOrStoreEUDOutsideAtlassian"] = bodyAppTrustInformationLogDetailsLogProcessAndOrStoreEUDOutsideAtlassian
						}
						if cmd.Flags().Changed("app-trust-information-log-details-logs-integral-for-app-functionality") {
							nestedAppTrustInformationLogDetails["logsIntegralForAppFunctionality"] = bodyAppTrustInformationLogDetailsLogsIntegralForAppFunctionality
						}
						if len(nestedAppTrustInformationLogDetails) > 0 {
							nestedAppTrustInformation["logDetails"] = nestedAppTrustInformationLogDetails
						}
					}
					{
						nestedAppTrustInformationPrivacy := map[string]any{}
						if len(nestedAppTrustInformationPrivacy) > 0 {
							nestedAppTrustInformation["privacy"] = nestedAppTrustInformationPrivacy
						}
					}
					{
						nestedAppTrustInformationSecurity := map[string]any{}
						if bodyAppTrustInformationSecurityCompliantCertifications != "" {
							var parsedAppTrustInformationSecurityCompliantCertifications any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationSecurityCompliantCertifications), &parsedAppTrustInformationSecurityCompliantCertifications); err != nil {
								return fmt.Errorf("parsing --app-trust-information-security-compliant-certifications JSON: %w", err)
							}
							nestedAppTrustInformationSecurity["compliantCertifications"] = parsedAppTrustInformationSecurityCompliantCertifications
						}
						if cmd.Flags().Changed("app-trust-information-security-has-compliant-certifications") {
							nestedAppTrustInformationSecurity["hasCompliantCertifications"] = bodyAppTrustInformationSecurityHasCompliantCertifications
						}
						if cmd.Flags().Changed("app-trust-information-security-is-disk-encryption-supported") {
							nestedAppTrustInformationSecurity["isDiskEncryptionSupported"] = bodyAppTrustInformationSecurityIsDiskEncryptionSupported
						}
						if bodyAppTrustInformationSecurityPermissionsJustification != "" {
							nestedAppTrustInformationSecurity["permissionsJustification"] = bodyAppTrustInformationSecurityPermissionsJustification
						}
						if bodyAppTrustInformationSecurityPublicSecurityPoliciesLink != "" {
							nestedAppTrustInformationSecurity["publicSecurityPoliciesLink"] = bodyAppTrustInformationSecurityPublicSecurityPoliciesLink
						}
						if cmd.Flags().Changed("app-trust-information-security-requires-users-to-provide-pa-ts") {
							nestedAppTrustInformationSecurity["requiresUsersToProvidePATs"] = bodyAppTrustInformationSecurityRequiresUsersToProvidePATs
						}
						if bodyAppTrustInformationSecuritySecurityContact != "" {
							nestedAppTrustInformationSecurity["securityContact"] = bodyAppTrustInformationSecuritySecurityContact
						}
						if len(nestedAppTrustInformationSecurity) > 0 {
							nestedAppTrustInformation["security"] = nestedAppTrustInformationSecurity
						}
					}
					{
						nestedAppTrustInformationThirdPartyInformation := map[string]any{}
						if bodyAppTrustInformationThirdPartyInformationDataSubProcessors != "" {
							nestedAppTrustInformationThirdPartyInformation["dataSubProcessors"] = bodyAppTrustInformationThirdPartyInformationDataSubProcessors
						}
						if cmd.Flags().Changed("app-trust-information-third-party-information-is-end-user-data-shared") {
							nestedAppTrustInformationThirdPartyInformation["isEndUserDataShared"] = bodyAppTrustInformationThirdPartyInformationIsEndUserDataShared
						}
						if bodyAppTrustInformationThirdPartyInformationThirdPartyDetails != "" {
							var parsedAppTrustInformationThirdPartyInformationThirdPartyDetails any
							if err := json.Unmarshal([]byte(bodyAppTrustInformationThirdPartyInformationThirdPartyDetails), &parsedAppTrustInformationThirdPartyInformationThirdPartyDetails); err != nil {
								return fmt.Errorf("parsing --app-trust-information-third-party-information-third-party-details JSON: %w", err)
							}
							nestedAppTrustInformationThirdPartyInformation["thirdPartyDetails"] = parsedAppTrustInformationThirdPartyInformationThirdPartyDetails
						}
						if len(nestedAppTrustInformationThirdPartyInformation) > 0 {
							nestedAppTrustInformation["thirdPartyInformation"] = nestedAppTrustInformationThirdPartyInformation
						}
					}
					if len(nestedAppTrustInformation) > 0 {
						body["appTrustInformation"] = nestedAppTrustInformation
					}
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "privacy-and-security", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "privacy-and-security", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "privacy-and-security", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "privacy-and-security", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "privacy-and-security", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "privacy-and-security",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "privacy-and-security", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "privacy-and-security", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataAccessAndStorageAppProcessEUDOutsideAtlassian, "app-trust-information-data-access-and-storage-app-process-eud-outside-atlassian", false, "Does your app process End-User Data outside of Atlassian products and services?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataAccessAndStorageAppStoresEUDOutsideAtlassian, "app-trust-information-data-access-and-storage-app-stores-eud-outside-atlassian", false, "Does your app store End-User Data outside of Atlassian products and services?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataAccessAndStorageIsSameDataProcessedAndStored, "app-trust-information-data-access-and-storage-is-same-data-processed-and-stored", false, "Does your app process and/or store End-User Data?")
	cmd.Flags().StringVar(&bodyAppTrustInformationDataAccessAndStorageTypesOfDataAccessed, "app-trust-information-data-access-and-storage-types-of-data-accessed", "", "List of End-User Data types your app processes")
	cmd.Flags().StringVar(&bodyAppTrustInformationDataAccessAndStorageTypesOfDataStored, "app-trust-information-data-access-and-storage-types-of-data-stored", "", "List of End-User Data types your app stores")
	cmd.Flags().StringVar(&bodyAppTrustInformationDataResidencyCountriesWhereEndUserDataStored, "app-trust-information-data-residency-countries-where-end-user-data-stored", "", "List of locations where in-scope End-User Data is stored")
	cmd.Flags().StringVar(&bodyAppTrustInformationDataResidencyInScopeDataTypes, "app-trust-information-data-residency-in-scope-data-types", "", "List of in-scope End-User Data type")
	cmd.Flags().StringVar(&bodyAppTrustInformationDataResidencyIsDataResidencySupported, "app-trust-information-data-residency-is-data-residency-supported", "", "Does your App support data residency?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataResidencyRealmMigrationSupported, "app-trust-information-data-residency-realm-migration-supported", false, "Does your app support migration of in-scope End User Data between your data residency supported locations?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataRetentionIsCustomRetentionPeriodAllowed, "app-trust-information-data-retention-is-custom-retention-period-allowed", false, "Does your app allow customers to request a custom End-User Data retention period?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataRetentionIsDataRetentionSupported, "app-trust-information-data-retention-is-data-retention-supported", false, "Is end-user data stored?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationDataRetentionIsRetentionDurationIndefinite, "app-trust-information-data-retention-is-retention-duration-indefinite", false, "Does your app store End-User Data indefinitely post app uninstallation?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationLogDetailsLogEUDShareWithThirdParty, "app-trust-information-log-details-log-eud-share-with-third-party", false, "Does your app share logs that include End-User Data with any third party entities?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationLogDetailsLogEndUserData, "app-trust-information-log-details-log-end-user-data", false, "Does your app log End-User Data?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationLogDetailsLogProcessAndOrStoreEUDOutsideAtlassian, "app-trust-information-log-details-log-process-and-or-store-eud-outside-atlassian", false, "Does your app process and/or store End-User Data in logs outside of Atlassian products and services?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationLogDetailsLogsIntegralForAppFunctionality, "app-trust-information-log-details-logs-integral-for-app-functionality", false, "Is sharing of logs that include End-User Data with any third party entities integral for app functionality?")
	cmd.Flags().StringVar(&bodyAppTrustInformationSecurityCompliantCertifications, "app-trust-information-security-compliant-certifications", "", "List of compliance certificates for your app")
	cmd.Flags().BoolVar(&bodyAppTrustInformationSecurityHasCompliantCertifications, "app-trust-information-security-has-compliant-certifications", false, "Does your app have any compliance certifications?")
	cmd.Flags().BoolVar(&bodyAppTrustInformationSecurityIsDiskEncryptionSupported, "app-trust-information-security-is-disk-encryption-supported", false, "Does your app use full disk encryption at-rest for End-User Data stored outside of Atlassian or the users’s browser?")
	cmd.Flags().StringVar(&bodyAppTrustInformationSecurityPermissionsJustification, "app-trust-information-security-permissions-justification", "", "Reason/justification for the permissions that are required by the app.")
	cmd.Flags().StringVar(&bodyAppTrustInformationSecurityPublicSecurityPoliciesLink, "app-trust-information-security-public-security-policies-link", "", "Security policy for your app")
	cmd.Flags().BoolVar(&bodyAppTrustInformationSecurityRequiresUsersToProvidePATs, "app-trust-information-security-requires-users-to-provide-pa-ts", false, "Does the app require end users to provide Atlassian Personal Access Tokens (PATs), User Account Passwords")
	cmd.Flags().StringVar(&bodyAppTrustInformationSecuritySecurityContact, "app-trust-information-security-security-contact", "", "Contact for your app security issues")
	cmd.Flags().StringVar(&bodyAppTrustInformationThirdPartyInformationDataSubProcessors, "app-trust-information-third-party-information-data-sub-processors", "", "If End-User Data is shared with third-party entities, provide a link to sub-processor list")
	cmd.Flags().BoolVar(&bodyAppTrustInformationThirdPartyInformationIsEndUserDataShared, "app-trust-information-third-party-information-is-end-user-data-shared", false, "Does your app share End-User Data with any third party entities (e.g. sub-processors)?")
	cmd.Flags().StringVar(&bodyAppTrustInformationThirdPartyInformationThirdPartyDetails, "app-trust-information-third-party-information-third-party-details", "", "If End-User Data is shared with third-party entities, provide third-party details")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
