// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAddonCategoriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "addon-categories",
		Short:  "Manage addon categories command groups",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAddonCategoriesGetCmd(flags))
	cmd.AddCommand(newAddonCategoriesGetAddoncategoriesCmd(flags))
	return cmd
}
