// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsVersionsGetCmd(flags *rootFlags) *cobra.Command {
	var flagAfterVersion string
	var flagApplication string
	var flagApplicationBuild int
	var flagCost string
	var flagHosting string
	var flagIncludePrivate bool
	var flagCloudComplianceBoundary string
	var flagOffset string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get <addonKey>",
		Short:       "Get a list of versions for the specified app.",
		Example:     "  jira-pp-cli-pp-cli addons versions get your-token-here",
		Annotations: map[string]string{"pp:endpoint": "versions.get", "pp:method": "GET", "pp:path": "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/versions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("cost") {
				allowedCost := []string{"free", "marketplace", "orderable", "paid"}
				validCost := false
				for _, v := range allowedCost {
					if flagCost == v {
						validCost = true
						break
					}
				}
				if !validCost {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "cost", flagCost, allowedCost)
				}
			}
			if cmd.Flags().Changed("hosting") {
				allowedHosting := []string{"any", "cloud", "datacenter", "server"}
				validHosting := false
				for _, v := range allowedHosting {
					if flagHosting == v {
						validHosting = true
						break
					}
				}
				if !validHosting {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "hosting", flagHosting, allowedHosting)
				}
			}
			if cmd.Flags().Changed("cloud-compliance-boundary") {
				allowedCloudComplianceBoundary := []string{"commercial", "fedramp_moderate", "isolated_cloud"}
				validCloudComplianceBoundary := false
				for _, v := range allowedCloudComplianceBoundary {
					if flagCloudComplianceBoundary == v {
						validCloudComplianceBoundary = true
						break
					}
				}
				if !validCloudComplianceBoundary {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "cloud-compliance-boundary", flagCloudComplianceBoundary, allowedCloudComplianceBoundary)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/versions"
			path = replacePathParam(path, "addonKey", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "versions", path, map[string]string{
				"afterVersion":            fmt.Sprintf("%v", flagAfterVersion),
				"application":             fmt.Sprintf("%v", flagApplication),
				"applicationBuild":        fmt.Sprintf("%v", flagApplicationBuild),
				"cost":                    fmt.Sprintf("%v", flagCost),
				"hosting":                 fmt.Sprintf("%v", flagHosting),
				"includePrivate":          fmt.Sprintf("%v", flagIncludePrivate),
				"cloudComplianceBoundary": fmt.Sprintf("%v", flagCloudComplianceBoundary),
				"offset":                  fmt.Sprintf("%v", flagOffset),
				"limit":                   fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "offset", "offset", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAfterVersion, "after-version", "", "Selects only app versions newer than the version with the specified display name")
	cmd.Flags().StringVar(&flagApplication, "application", "", "Only returns apps compatible with this application")
	cmd.Flags().IntVar(&flagApplicationBuild, "application-build", 0, "Only returns apps compatible with the specified application build number")
	cmd.Flags().StringVar(&flagCost, "cost", "", "Only returns apps with the specified payment model (one of: free, marketplace, orderable, paid)")
	cmd.Flags().StringVar(&flagHosting, "hosting", "", "Only returns apps with the specified hosting model (one of: any, cloud, datacenter, server)")
	cmd.Flags().BoolVar(&flagIncludePrivate, "include-private", false, "Includes private apps or versions if you are authorized to see them")
	cmd.Flags().StringVar(&flagCloudComplianceBoundary, "cloud-compliance-boundary", "commercial", "Only returns app versions with the specified cloud compliance boundary, with 'commercial' as the default for cloud apps. (one of: commercial, fedramp_moderate, isolated_cloud)")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "If specified, skips ahead by this number of items")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "If specified, limits the result set to this number of items")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
