// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAddonsPrivacyAndSecurityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "privacy-and-security",
		Short: "Below are the APIs to fill privacy and security information about apps.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAddonsPrivacyAndSecurityDeleteCmd(flags))
	cmd.AddCommand(newAddonsPrivacyAndSecurityGetCmd(flags))
	cmd.AddCommand(newAddonsPrivacyAndSecurityUpdateCmd(flags))
	cmd.AddCommand(newAddonsPrivacyAndSecurityUpdateAddonsCmd(flags))
	cmd.AddCommand(newAddonsPrivacyAndSecurityUpdateAddons2Cmd(flags))
	return cmd
}
