// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyEmbeddedCategories string
	var bodyEmbeddedDistributionBundled bool
	var bodyEmbeddedDistributionBundledCloud bool
	var bodyEmbeddedDistributionDownloads int
	var bodyEmbeddedDistributionTotalInstalls int
	var bodyEmbeddedDistributionTotalUsers int
	var bodyEmbeddedReviewsAverageStars float64
	var bodyEmbeddedReviewsCount int
	var bodyEmbeddedVendorIsAtlassian bool
	var bodyEmbeddedVendorName string
	var bodyEmbeddedVendorVerifiedStatus string
	var bodyEmbeddedVersionBuildNumber int
	var bodyEmbeddedVersionCloudComplianceBoundaries string
	var bodyEmbeddedVersionCompatibilities string
	var bodyEmbeddedVersionDeployable bool
	var bodyEmbeddedVersionIntegrationType string
	var bodyEmbeddedVersionName string
	var bodyEmbeddedVersionPaymentModel string
	var bodyEmbeddedVersionStatic bool
	var bodyEmbeddedVersionStatus string
	var bodyEmbeddedVersionYoutubeId string
	var bodyLinksAlternateHref string
	var bodyLinksAlternateTitle string
	var bodyLinksAlternateType string
	var bodyLinksApprovalHref string
	var bodyLinksApprovalTitle string
	var bodyLinksApprovalType string
	var bodyLinksBannerHref string
	var bodyLinksBannerTitle string
	var bodyLinksBannerType string
	var bodyLinksCategories string
	var bodyLinksDistributionHref string
	var bodyLinksDistributionTitle string
	var bodyLinksDistributionType string
	var bodyLinksEditHref string
	var bodyLinksEditTitle string
	var bodyLinksEditType string
	var bodyLinksFeedbacksName string
	var bodyLinksFeedbacksTemplate string
	var bodyLinksFeedbacksType string
	var bodyLinksLogoHref string
	var bodyLinksLogoTitle string
	var bodyLinksLogoType string
	var bodyLinksPricing string
	var bodyLinksRecommendationsName string
	var bodyLinksRecommendationsTemplate string
	var bodyLinksRecommendationsType string
	var bodyLinksReleaseHref string
	var bodyLinksReleaseTitle string
	var bodyLinksReleaseType string
	var bodyLinksReviews string
	var bodyLinksSelfHref string
	var bodyLinksSelfTitle string
	var bodyLinksSelfType string
	var bodyLinksSupportHref string
	var bodyLinksSupportTitle string
	var bodyLinksSupportType string
	var bodyLinksTitleLogoHref string
	var bodyLinksTitleLogoTitle string
	var bodyLinksTitleLogoType string
	var bodyLinksTokensHref string
	var bodyLinksTokensTitle string
	var bodyLinksTokensType string
	var bodyLinksTransitionHref string
	var bodyLinksTransitionTitle string
	var bodyLinksTransitionType string
	var bodyLinksVendorHref string
	var bodyLinksVendorTitle string
	var bodyLinksVendorType string
	var bodyLinksVersionsHref string
	var bodyLinksVersionsTitle string
	var bodyLinksVersionsType string
	var bodyLinksWatchHref string
	var bodyLinksWatchTitle string
	var bodyLinksWatchType string
	var bodyCodegeist bool
	var bodyCommunityEnabled bool
	var bodyDataCenterReviewIssueKey string
	var bodyEnableAtlassianAnswers bool
	var bodyGoogleAnalyticsId string
	var bodyJsdEmbeddedDataKey string
	var bodyKey string
	var bodyLastModified string
	var bodyLegacyDescription string
	var bodyLegacyVendorLinksBuilds string
	var bodyLegacyVendorLinksSource string
	var bodyLegacyVendorLinksWiki string
	var bodyMarketingMarketingLabels string
	var bodyName string
	var bodyStatus string
	var bodyStatusAfterApproval string
	var bodySummary string
	var bodyTagLine string
	var bodyTagsCategory string
	var bodyTagsKeywords string
	var bodyTagsMarketing string
	var bodyVendorLinksAppStatusPage string
	var bodyVendorLinksForums string
	var bodyVendorLinksIssueTracker string
	var bodyVendorLinksPrivacy string
	var bodyVendorLinksSupportTicketSystem string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a new app. The associated vendor account must exist prior to the app's creation.",
		Example:     "  jira-pp-cli-pp-cli addons create --key your-token-here",
		Annotations: map[string]string{"pp:endpoint": "addons.create", "pp:method": "POST", "pp:path": "https://marketplace.atlassian.com/rest/2/addons"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("embedded-distribution-bundled") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-distribution-bundled")
				}
				if !cmd.Flags().Changed("embedded-distribution-bundled-cloud") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-distribution-bundled-cloud")
				}
				if !cmd.Flags().Changed("embedded-distribution-downloads") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-distribution-downloads")
				}
				if !cmd.Flags().Changed("embedded-reviews-average-stars") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-reviews-average-stars")
				}
				if !cmd.Flags().Changed("embedded-reviews-count") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-reviews-count")
				}
				if !cmd.Flags().Changed("embedded-vendor-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-vendor-name")
				}
				if !cmd.Flags().Changed("embedded-version-status") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-version-status")
				}
				if !cmd.Flags().Changed("links-alternate-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-alternate-href")
				}
				if !cmd.Flags().Changed("links-approval-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-approval-href")
				}
				if !cmd.Flags().Changed("links-banner-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-banner-href")
				}
				if !cmd.Flags().Changed("links-distribution-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-distribution-href")
				}
				if !cmd.Flags().Changed("links-edit-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-edit-href")
				}
				if !cmd.Flags().Changed("links-feedbacks-template") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-feedbacks-template")
				}
				if !cmd.Flags().Changed("links-logo-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-logo-href")
				}
				if !cmd.Flags().Changed("links-recommendations-template") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-recommendations-template")
				}
				if !cmd.Flags().Changed("links-release-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-release-href")
				}
				if !cmd.Flags().Changed("links-self-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-self-href")
				}
				if !cmd.Flags().Changed("links-support-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-support-href")
				}
				if !cmd.Flags().Changed("links-title-logo-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-title-logo-href")
				}
				if !cmd.Flags().Changed("links-tokens-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-tokens-href")
				}
				if !cmd.Flags().Changed("links-transition-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-transition-href")
				}
				if !cmd.Flags().Changed("links-vendor-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-vendor-href")
				}
				if !cmd.Flags().Changed("links-versions-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-versions-href")
				}
				if !cmd.Flags().Changed("links-watch-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-watch-href")
				}
				if !cmd.Flags().Changed("key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "key")
				}
				if !cmd.Flags().Changed("marketing-marketing-labels") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "marketing-marketing-labels")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("status") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status")
				}
				if !cmd.Flags().Changed("tags-category") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "tags-category")
				}
				if !cmd.Flags().Changed("tags-keywords") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "tags-keywords")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedEmbedded := map[string]any{}
					{
						nestedEmbeddedBanner := map[string]any{}
						if len(nestedEmbeddedBanner) > 0 {
							nestedEmbedded["banner"] = nestedEmbeddedBanner
						}
					}
					if bodyEmbeddedCategories != "" {
						var parsedEmbeddedCategories any
						if err := json.Unmarshal([]byte(bodyEmbeddedCategories), &parsedEmbeddedCategories); err != nil {
							return fmt.Errorf("parsing --embedded-categories JSON: %w", err)
						}
						nestedEmbedded["categories"] = parsedEmbeddedCategories
					}
					{
						nestedEmbeddedDistribution := map[string]any{}
						if cmd.Flags().Changed("embedded-distribution-bundled") {
							nestedEmbeddedDistribution["bundled"] = bodyEmbeddedDistributionBundled
						}
						if cmd.Flags().Changed("embedded-distribution-bundled-cloud") {
							nestedEmbeddedDistribution["bundledCloud"] = bodyEmbeddedDistributionBundledCloud
						}
						if bodyEmbeddedDistributionDownloads != 0 {
							nestedEmbeddedDistribution["downloads"] = bodyEmbeddedDistributionDownloads
						}
						if bodyEmbeddedDistributionTotalInstalls != 0 {
							nestedEmbeddedDistribution["totalInstalls"] = bodyEmbeddedDistributionTotalInstalls
						}
						if bodyEmbeddedDistributionTotalUsers != 0 {
							nestedEmbeddedDistribution["totalUsers"] = bodyEmbeddedDistributionTotalUsers
						}
						if len(nestedEmbeddedDistribution) > 0 {
							nestedEmbedded["distribution"] = nestedEmbeddedDistribution
						}
					}
					{
						nestedEmbeddedLogo := map[string]any{}
						if len(nestedEmbeddedLogo) > 0 {
							nestedEmbedded["logo"] = nestedEmbeddedLogo
						}
					}
					{
						nestedEmbeddedReviews := map[string]any{}
						if bodyEmbeddedReviewsAverageStars != 0.0 {
							nestedEmbeddedReviews["averageStars"] = bodyEmbeddedReviewsAverageStars
						}
						if bodyEmbeddedReviewsCount != 0 {
							nestedEmbeddedReviews["count"] = bodyEmbeddedReviewsCount
						}
						if len(nestedEmbeddedReviews) > 0 {
							nestedEmbedded["reviews"] = nestedEmbeddedReviews
						}
					}
					{
						nestedEmbeddedTitleLogo := map[string]any{}
						if len(nestedEmbeddedTitleLogo) > 0 {
							nestedEmbedded["titleLogo"] = nestedEmbeddedTitleLogo
						}
					}
					{
						nestedEmbeddedVendor := map[string]any{}
						if cmd.Flags().Changed("embedded-vendor-is-atlassian") {
							nestedEmbeddedVendor["isAtlassian"] = bodyEmbeddedVendorIsAtlassian
						}
						if bodyEmbeddedVendorName != "" {
							nestedEmbeddedVendor["name"] = bodyEmbeddedVendorName
						}
						if bodyEmbeddedVendorVerifiedStatus != "" {
							nestedEmbeddedVendor["verifiedStatus"] = bodyEmbeddedVendorVerifiedStatus
						}
						if len(nestedEmbeddedVendor) > 0 {
							nestedEmbedded["vendor"] = nestedEmbeddedVendor
						}
					}
					{
						nestedEmbeddedVersion := map[string]any{}
						if bodyEmbeddedVersionBuildNumber != 0 {
							nestedEmbeddedVersion["buildNumber"] = bodyEmbeddedVersionBuildNumber
						}
						if bodyEmbeddedVersionCloudComplianceBoundaries != "" {
							var parsedEmbeddedVersionCloudComplianceBoundaries any
							if err := json.Unmarshal([]byte(bodyEmbeddedVersionCloudComplianceBoundaries), &parsedEmbeddedVersionCloudComplianceBoundaries); err != nil {
								return fmt.Errorf("parsing --embedded-version-cloud-compliance-boundaries JSON: %w", err)
							}
							nestedEmbeddedVersion["cloudComplianceBoundaries"] = parsedEmbeddedVersionCloudComplianceBoundaries
						}
						if bodyEmbeddedVersionCompatibilities != "" {
							var parsedEmbeddedVersionCompatibilities any
							if err := json.Unmarshal([]byte(bodyEmbeddedVersionCompatibilities), &parsedEmbeddedVersionCompatibilities); err != nil {
								return fmt.Errorf("parsing --embedded-version-compatibilities JSON: %w", err)
							}
							nestedEmbeddedVersion["compatibilities"] = parsedEmbeddedVersionCompatibilities
						}
						if cmd.Flags().Changed("embedded-version-deployable") {
							nestedEmbeddedVersion["deployable"] = bodyEmbeddedVersionDeployable
						}
						if bodyEmbeddedVersionIntegrationType != "" {
							nestedEmbeddedVersion["integrationType"] = bodyEmbeddedVersionIntegrationType
						}
						if bodyEmbeddedVersionName != "" {
							nestedEmbeddedVersion["name"] = bodyEmbeddedVersionName
						}
						if bodyEmbeddedVersionPaymentModel != "" {
							nestedEmbeddedVersion["paymentModel"] = bodyEmbeddedVersionPaymentModel
						}
						if cmd.Flags().Changed("embedded-version-static") {
							nestedEmbeddedVersion["static"] = bodyEmbeddedVersionStatic
						}
						if bodyEmbeddedVersionStatus != "" {
							nestedEmbeddedVersion["status"] = bodyEmbeddedVersionStatus
						}
						if bodyEmbeddedVersionYoutubeId != "" {
							nestedEmbeddedVersion["youtubeId"] = bodyEmbeddedVersionYoutubeId
						}
						if len(nestedEmbeddedVersion) > 0 {
							nestedEmbedded["version"] = nestedEmbeddedVersion
						}
					}
					if len(nestedEmbedded) > 0 {
						body["_embedded"] = nestedEmbedded
					}
				}
				{
					nestedLinks := map[string]any{}
					{
						nestedLinksAlternate := map[string]any{}
						if bodyLinksAlternateHref != "" {
							nestedLinksAlternate["href"] = bodyLinksAlternateHref
						}
						if bodyLinksAlternateTitle != "" {
							nestedLinksAlternate["title"] = bodyLinksAlternateTitle
						}
						if bodyLinksAlternateType != "" {
							nestedLinksAlternate["type"] = bodyLinksAlternateType
						}
						if len(nestedLinksAlternate) > 0 {
							nestedLinks["alternate"] = nestedLinksAlternate
						}
					}
					{
						nestedLinksApproval := map[string]any{}
						if bodyLinksApprovalHref != "" {
							nestedLinksApproval["href"] = bodyLinksApprovalHref
						}
						if bodyLinksApprovalTitle != "" {
							nestedLinksApproval["title"] = bodyLinksApprovalTitle
						}
						if bodyLinksApprovalType != "" {
							nestedLinksApproval["type"] = bodyLinksApprovalType
						}
						if len(nestedLinksApproval) > 0 {
							nestedLinks["approval"] = nestedLinksApproval
						}
					}
					{
						nestedLinksBanner := map[string]any{}
						if bodyLinksBannerHref != "" {
							nestedLinksBanner["href"] = bodyLinksBannerHref
						}
						if bodyLinksBannerTitle != "" {
							nestedLinksBanner["title"] = bodyLinksBannerTitle
						}
						if bodyLinksBannerType != "" {
							nestedLinksBanner["type"] = bodyLinksBannerType
						}
						if len(nestedLinksBanner) > 0 {
							nestedLinks["banner"] = nestedLinksBanner
						}
					}
					if bodyLinksCategories != "" {
						var parsedLinksCategories any
						if err := json.Unmarshal([]byte(bodyLinksCategories), &parsedLinksCategories); err != nil {
							return fmt.Errorf("parsing --links-categories JSON: %w", err)
						}
						nestedLinks["categories"] = parsedLinksCategories
					}
					{
						nestedLinksDistribution := map[string]any{}
						if bodyLinksDistributionHref != "" {
							nestedLinksDistribution["href"] = bodyLinksDistributionHref
						}
						if bodyLinksDistributionTitle != "" {
							nestedLinksDistribution["title"] = bodyLinksDistributionTitle
						}
						if bodyLinksDistributionType != "" {
							nestedLinksDistribution["type"] = bodyLinksDistributionType
						}
						if len(nestedLinksDistribution) > 0 {
							nestedLinks["distribution"] = nestedLinksDistribution
						}
					}
					{
						nestedLinksEdit := map[string]any{}
						if bodyLinksEditHref != "" {
							nestedLinksEdit["href"] = bodyLinksEditHref
						}
						if bodyLinksEditTitle != "" {
							nestedLinksEdit["title"] = bodyLinksEditTitle
						}
						if bodyLinksEditType != "" {
							nestedLinksEdit["type"] = bodyLinksEditType
						}
						if len(nestedLinksEdit) > 0 {
							nestedLinks["edit"] = nestedLinksEdit
						}
					}
					{
						nestedLinksFeedbacks := map[string]any{}
						if bodyLinksFeedbacksName != "" {
							nestedLinksFeedbacks["name"] = bodyLinksFeedbacksName
						}
						if bodyLinksFeedbacksTemplate != "" {
							nestedLinksFeedbacks["template"] = bodyLinksFeedbacksTemplate
						}
						if bodyLinksFeedbacksType != "" {
							nestedLinksFeedbacks["type"] = bodyLinksFeedbacksType
						}
						if len(nestedLinksFeedbacks) > 0 {
							nestedLinks["feedbacks"] = nestedLinksFeedbacks
						}
					}
					{
						nestedLinksLogo := map[string]any{}
						if bodyLinksLogoHref != "" {
							nestedLinksLogo["href"] = bodyLinksLogoHref
						}
						if bodyLinksLogoTitle != "" {
							nestedLinksLogo["title"] = bodyLinksLogoTitle
						}
						if bodyLinksLogoType != "" {
							nestedLinksLogo["type"] = bodyLinksLogoType
						}
						if len(nestedLinksLogo) > 0 {
							nestedLinks["logo"] = nestedLinksLogo
						}
					}
					if bodyLinksPricing != "" {
						var parsedLinksPricing any
						if err := json.Unmarshal([]byte(bodyLinksPricing), &parsedLinksPricing); err != nil {
							return fmt.Errorf("parsing --links-pricing JSON: %w", err)
						}
						nestedLinks["pricing"] = parsedLinksPricing
					}
					{
						nestedLinksRecommendations := map[string]any{}
						if bodyLinksRecommendationsName != "" {
							nestedLinksRecommendations["name"] = bodyLinksRecommendationsName
						}
						if bodyLinksRecommendationsTemplate != "" {
							nestedLinksRecommendations["template"] = bodyLinksRecommendationsTemplate
						}
						if bodyLinksRecommendationsType != "" {
							nestedLinksRecommendations["type"] = bodyLinksRecommendationsType
						}
						if len(nestedLinksRecommendations) > 0 {
							nestedLinks["recommendations"] = nestedLinksRecommendations
						}
					}
					{
						nestedLinksRelease := map[string]any{}
						if bodyLinksReleaseHref != "" {
							nestedLinksRelease["href"] = bodyLinksReleaseHref
						}
						if bodyLinksReleaseTitle != "" {
							nestedLinksRelease["title"] = bodyLinksReleaseTitle
						}
						if bodyLinksReleaseType != "" {
							nestedLinksRelease["type"] = bodyLinksReleaseType
						}
						if len(nestedLinksRelease) > 0 {
							nestedLinks["release"] = nestedLinksRelease
						}
					}
					if bodyLinksReviews != "" {
						var parsedLinksReviews any
						if err := json.Unmarshal([]byte(bodyLinksReviews), &parsedLinksReviews); err != nil {
							return fmt.Errorf("parsing --links-reviews JSON: %w", err)
						}
						nestedLinks["reviews"] = parsedLinksReviews
					}
					{
						nestedLinksSelf := map[string]any{}
						if bodyLinksSelfHref != "" {
							nestedLinksSelf["href"] = bodyLinksSelfHref
						}
						if bodyLinksSelfTitle != "" {
							nestedLinksSelf["title"] = bodyLinksSelfTitle
						}
						if bodyLinksSelfType != "" {
							nestedLinksSelf["type"] = bodyLinksSelfType
						}
						if len(nestedLinksSelf) > 0 {
							nestedLinks["self"] = nestedLinksSelf
						}
					}
					{
						nestedLinksSupport := map[string]any{}
						if bodyLinksSupportHref != "" {
							nestedLinksSupport["href"] = bodyLinksSupportHref
						}
						if bodyLinksSupportTitle != "" {
							nestedLinksSupport["title"] = bodyLinksSupportTitle
						}
						if bodyLinksSupportType != "" {
							nestedLinksSupport["type"] = bodyLinksSupportType
						}
						if len(nestedLinksSupport) > 0 {
							nestedLinks["support"] = nestedLinksSupport
						}
					}
					{
						nestedLinksTitleLogo := map[string]any{}
						if bodyLinksTitleLogoHref != "" {
							nestedLinksTitleLogo["href"] = bodyLinksTitleLogoHref
						}
						if bodyLinksTitleLogoTitle != "" {
							nestedLinksTitleLogo["title"] = bodyLinksTitleLogoTitle
						}
						if bodyLinksTitleLogoType != "" {
							nestedLinksTitleLogo["type"] = bodyLinksTitleLogoType
						}
						if len(nestedLinksTitleLogo) > 0 {
							nestedLinks["titleLogo"] = nestedLinksTitleLogo
						}
					}
					{
						nestedLinksTokens := map[string]any{}
						if bodyLinksTokensHref != "" {
							nestedLinksTokens["href"] = bodyLinksTokensHref
						}
						if bodyLinksTokensTitle != "" {
							nestedLinksTokens["title"] = bodyLinksTokensTitle
						}
						if bodyLinksTokensType != "" {
							nestedLinksTokens["type"] = bodyLinksTokensType
						}
						if len(nestedLinksTokens) > 0 {
							nestedLinks["tokens"] = nestedLinksTokens
						}
					}
					{
						nestedLinksTransition := map[string]any{}
						if bodyLinksTransitionHref != "" {
							nestedLinksTransition["href"] = bodyLinksTransitionHref
						}
						if bodyLinksTransitionTitle != "" {
							nestedLinksTransition["title"] = bodyLinksTransitionTitle
						}
						if bodyLinksTransitionType != "" {
							nestedLinksTransition["type"] = bodyLinksTransitionType
						}
						if len(nestedLinksTransition) > 0 {
							nestedLinks["transition"] = nestedLinksTransition
						}
					}
					{
						nestedLinksVendor := map[string]any{}
						if bodyLinksVendorHref != "" {
							nestedLinksVendor["href"] = bodyLinksVendorHref
						}
						if bodyLinksVendorTitle != "" {
							nestedLinksVendor["title"] = bodyLinksVendorTitle
						}
						if bodyLinksVendorType != "" {
							nestedLinksVendor["type"] = bodyLinksVendorType
						}
						if len(nestedLinksVendor) > 0 {
							nestedLinks["vendor"] = nestedLinksVendor
						}
					}
					{
						nestedLinksVersions := map[string]any{}
						if bodyLinksVersionsHref != "" {
							nestedLinksVersions["href"] = bodyLinksVersionsHref
						}
						if bodyLinksVersionsTitle != "" {
							nestedLinksVersions["title"] = bodyLinksVersionsTitle
						}
						if bodyLinksVersionsType != "" {
							nestedLinksVersions["type"] = bodyLinksVersionsType
						}
						if len(nestedLinksVersions) > 0 {
							nestedLinks["versions"] = nestedLinksVersions
						}
					}
					{
						nestedLinksWatch := map[string]any{}
						if bodyLinksWatchHref != "" {
							nestedLinksWatch["href"] = bodyLinksWatchHref
						}
						if bodyLinksWatchTitle != "" {
							nestedLinksWatch["title"] = bodyLinksWatchTitle
						}
						if bodyLinksWatchType != "" {
							nestedLinksWatch["type"] = bodyLinksWatchType
						}
						if len(nestedLinksWatch) > 0 {
							nestedLinks["watch"] = nestedLinksWatch
						}
					}
					if len(nestedLinks) > 0 {
						body["_links"] = nestedLinks
					}
				}
				if cmd.Flags().Changed("codegeist") {
					body["codegeist"] = bodyCodegeist
				}
				if cmd.Flags().Changed("community-enabled") {
					body["communityEnabled"] = bodyCommunityEnabled
				}
				if bodyDataCenterReviewIssueKey != "" {
					body["dataCenterReviewIssueKey"] = bodyDataCenterReviewIssueKey
				}
				if cmd.Flags().Changed("enable-atlassian-answers") {
					body["enableAtlassianAnswers"] = bodyEnableAtlassianAnswers
				}
				if bodyGoogleAnalyticsId != "" {
					body["googleAnalyticsId"] = bodyGoogleAnalyticsId
				}
				if bodyJsdEmbeddedDataKey != "" {
					body["jsdEmbeddedDataKey"] = bodyJsdEmbeddedDataKey
				}
				if bodyKey != "" {
					body["key"] = bodyKey
				}
				if bodyLastModified != "" {
					body["lastModified"] = bodyLastModified
				}
				{
					nestedLegacy := map[string]any{}
					if bodyLegacyDescription != "" {
						nestedLegacy["description"] = bodyLegacyDescription
					}
					{
						nestedLegacyVendorLinks := map[string]any{}
						if bodyLegacyVendorLinksBuilds != "" {
							nestedLegacyVendorLinks["builds"] = bodyLegacyVendorLinksBuilds
						}
						if bodyLegacyVendorLinksSource != "" {
							nestedLegacyVendorLinks["source"] = bodyLegacyVendorLinksSource
						}
						if bodyLegacyVendorLinksWiki != "" {
							nestedLegacyVendorLinks["wiki"] = bodyLegacyVendorLinksWiki
						}
						if len(nestedLegacyVendorLinks) > 0 {
							nestedLegacy["vendorLinks"] = nestedLegacyVendorLinks
						}
					}
					if len(nestedLegacy) > 0 {
						body["legacy"] = nestedLegacy
					}
				}
				{
					nestedMarketing := map[string]any{}
					if bodyMarketingMarketingLabels != "" {
						var parsedMarketingMarketingLabels any
						if err := json.Unmarshal([]byte(bodyMarketingMarketingLabels), &parsedMarketingMarketingLabels); err != nil {
							return fmt.Errorf("parsing --marketing-marketing-labels JSON: %w", err)
						}
						nestedMarketing["marketingLabels"] = parsedMarketingMarketingLabels
					}
					if len(nestedMarketing) > 0 {
						body["marketing"] = nestedMarketing
					}
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				if bodyStatusAfterApproval != "" {
					body["statusAfterApproval"] = bodyStatusAfterApproval
				}
				if bodySummary != "" {
					body["summary"] = bodySummary
				}
				if bodyTagLine != "" {
					body["tagLine"] = bodyTagLine
				}
				{
					nestedTags := map[string]any{}
					if bodyTagsCategory != "" {
						var parsedTagsCategory any
						if err := json.Unmarshal([]byte(bodyTagsCategory), &parsedTagsCategory); err != nil {
							return fmt.Errorf("parsing --tags-category JSON: %w", err)
						}
						nestedTags["category"] = parsedTagsCategory
					}
					if bodyTagsKeywords != "" {
						var parsedTagsKeywords any
						if err := json.Unmarshal([]byte(bodyTagsKeywords), &parsedTagsKeywords); err != nil {
							return fmt.Errorf("parsing --tags-keywords JSON: %w", err)
						}
						nestedTags["keywords"] = parsedTagsKeywords
					}
					if bodyTagsMarketing != "" {
						var parsedTagsMarketing any
						if err := json.Unmarshal([]byte(bodyTagsMarketing), &parsedTagsMarketing); err != nil {
							return fmt.Errorf("parsing --tags-marketing JSON: %w", err)
						}
						nestedTags["marketing"] = parsedTagsMarketing
					}
					if len(nestedTags) > 0 {
						body["tags"] = nestedTags
					}
				}
				{
					nestedVendorLinks := map[string]any{}
					if bodyVendorLinksAppStatusPage != "" {
						nestedVendorLinks["appStatusPage"] = bodyVendorLinksAppStatusPage
					}
					if bodyVendorLinksForums != "" {
						nestedVendorLinks["forums"] = bodyVendorLinksForums
					}
					if bodyVendorLinksIssueTracker != "" {
						nestedVendorLinks["issueTracker"] = bodyVendorLinksIssueTracker
					}
					if bodyVendorLinksPrivacy != "" {
						nestedVendorLinks["privacy"] = bodyVendorLinksPrivacy
					}
					if bodyVendorLinksSupportTicketSystem != "" {
						nestedVendorLinks["supportTicketSystem"] = bodyVendorLinksSupportTicketSystem
					}
					if len(nestedVendorLinks) > 0 {
						body["vendorLinks"] = nestedVendorLinks
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "addons", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "addons", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "addons", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "addons", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "addons", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "addons",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "addons", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "addons", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyEmbeddedCategories, "embedded-categories", "", "Information about any categories that the app belongs to")
	cmd.Flags().BoolVar(&bodyEmbeddedDistributionBundled, "embedded-distribution-bundled", false, "True if this is a preinstalled Server app")
	cmd.Flags().BoolVar(&bodyEmbeddedDistributionBundledCloud, "embedded-distribution-bundled-cloud", false, "True if this is a preinstalled Cloud app")
	cmd.Flags().IntVar(&bodyEmbeddedDistributionDownloads, "embedded-distribution-downloads", 0, "Total number of times this app has been downloaded from Marketplace")
	cmd.Flags().IntVar(&bodyEmbeddedDistributionTotalInstalls, "embedded-distribution-total-installs", 0, "Current (as of the last full week) number of application instances or accounts reporting that they have this app")
	cmd.Flags().IntVar(&bodyEmbeddedDistributionTotalUsers, "embedded-distribution-total-users", 0, "Current (as of the last full week) number of users among those instances or accounts")
	cmd.Flags().Float64Var(&bodyEmbeddedReviewsAverageStars, "embedded-reviews-average-stars", 0.0, "Average number of stars")
	cmd.Flags().IntVar(&bodyEmbeddedReviewsCount, "embedded-reviews-count", 0, "Total number of reviews")
	cmd.Flags().BoolVar(&bodyEmbeddedVendorIsAtlassian, "embedded-vendor-is-atlassian", false, "Whether this vendor is one of the Atlassian vendors")
	cmd.Flags().StringVar(&bodyEmbeddedVendorName, "embedded-vendor-name", "", "Name of the vendor")
	cmd.Flags().StringVar(&bodyEmbeddedVendorVerifiedStatus, "embedded-vendor-verified-status", "", "Indicates whether the vendor has Atlassian Verified status")
	cmd.Flags().IntVar(&bodyEmbeddedVersionBuildNumber, "embedded-version-build-number", 0, "The unique internal identifier and sort key for this version; omit this if you are creating an Atlassian Connect version")
	cmd.Flags().StringVar(&bodyEmbeddedVersionCloudComplianceBoundaries, "embedded-version-cloud-compliance-boundaries", "", "The cloud compliance boundaries for this app version.")
	cmd.Flags().StringVar(&bodyEmbeddedVersionCompatibilities, "embedded-version-compatibilities", "", "Describes the application(s), version ranges, and hosting models the app version is compatible with")
	cmd.Flags().BoolVar(&bodyEmbeddedVersionDeployable, "embedded-version-deployable", false, "True if this app version is directly installable")
	cmd.Flags().StringVar(&bodyEmbeddedVersionIntegrationType, "embedded-version-integration-type", "", "Integration type if the app is a Hipchat integration")
	cmd.Flags().StringVar(&bodyEmbeddedVersionName, "embedded-version-name", "", "The display name of the version, for example '1.0.0'")
	cmd.Flags().StringVar(&bodyEmbeddedVersionPaymentModel, "embedded-version-payment-model", "", "The payment model; you may omit this when creating a version and Marketplace will infer it, unless it is paid via vendor")
	cmd.Flags().BoolVar(&bodyEmbeddedVersionStatic, "embedded-version-static", false, "True if this is a static app (Plugins 1, a deprecated app framework)")
	cmd.Flags().StringVar(&bodyEmbeddedVersionStatus, "embedded-version-status", "", "Indicates whether the version is public, private, or pending approval")
	cmd.Flags().StringVar(&bodyEmbeddedVersionYoutubeId, "embedded-version-youtube-id", "", "YouTube video identifier if the version's hero image is a video")
	cmd.Flags().StringVar(&bodyLinksAlternateHref, "links-alternate-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksAlternateTitle, "links-alternate-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksAlternateType, "links-alternate-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksApprovalHref, "links-approval-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksApprovalTitle, "links-approval-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksApprovalType, "links-approval-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksBannerHref, "links-banner-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksBannerTitle, "links-banner-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksBannerType, "links-banner-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksCategories, "links-categories", "", "Resource links for any categories that the app belongs to, such as Integrations; for each app")
	cmd.Flags().StringVar(&bodyLinksDistributionHref, "links-distribution-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksDistributionTitle, "links-distribution-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksDistributionType, "links-distribution-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksEditHref, "links-edit-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksEditTitle, "links-edit-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksEditType, "links-edit-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksFeedbacksName, "links-feedbacks-name", "", "A secondary key for selecting Link objects which share the same relation type")
	cmd.Flags().StringVar(&bodyLinksFeedbacksTemplate, "links-feedbacks-template", "", "A link template in RFC6570 format")
	cmd.Flags().StringVar(&bodyLinksFeedbacksType, "links-feedbacks-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksLogoHref, "links-logo-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksLogoTitle, "links-logo-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksLogoType, "links-logo-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksPricing, "links-pricing", "", "Links to the app's pricing resource and pricing details page")
	cmd.Flags().StringVar(&bodyLinksRecommendationsName, "links-recommendations-name", "", "A secondary key for selecting Link objects which share the same relation type")
	cmd.Flags().StringVar(&bodyLinksRecommendationsTemplate, "links-recommendations-template", "", "A link template in RFC6570 format")
	cmd.Flags().StringVar(&bodyLinksRecommendationsType, "links-recommendations-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksReleaseHref, "links-release-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksReleaseTitle, "links-release-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksReleaseType, "links-release-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksReviews, "links-reviews", "", "Links to the app's reviews collection resource and review details page")
	cmd.Flags().StringVar(&bodyLinksSelfHref, "links-self-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksSelfTitle, "links-self-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksSelfType, "links-self-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksSupportHref, "links-support-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksSupportTitle, "links-support-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksSupportType, "links-support-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksTitleLogoHref, "links-title-logo-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksTitleLogoTitle, "links-title-logo-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksTitleLogoType, "links-title-logo-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksTokensHref, "links-tokens-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksTokensTitle, "links-tokens-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksTokensType, "links-tokens-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksTransitionHref, "links-transition-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksTransitionTitle, "links-transition-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksTransitionType, "links-transition-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksVendorHref, "links-vendor-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksVendorTitle, "links-vendor-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksVendorType, "links-vendor-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksVersionsHref, "links-versions-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksVersionsTitle, "links-versions-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksVersionsType, "links-versions-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksWatchHref, "links-watch-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksWatchTitle, "links-watch-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksWatchType, "links-watch-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().BoolVar(&bodyCodegeist, "codegeist", false, "True if this app is an entry to the Atlassian Codegeist competition")
	cmd.Flags().BoolVar(&bodyCommunityEnabled, "community-enabled", false, "To enable and disable showing the Atlassian Comunity Link for a supported app")
	cmd.Flags().StringVar(&bodyDataCenterReviewIssueKey, "data-center-review-issue-key", "", "Data Center apps go through a technical review process. This is the related issue key.")
	cmd.Flags().BoolVar(&bodyEnableAtlassianAnswers, "enable-atlassian-answers", false, "This field is deprecated and will always be empty. If specified in a request body, it'll be ignored'")
	cmd.Flags().StringVar(&bodyGoogleAnalyticsId, "google-analytics-id", "", "Google Analytics account ID for tracking visitors to the app page")
	cmd.Flags().StringVar(&bodyJsdEmbeddedDataKey, "jsd-embedded-data-key", "", "The data key that associates the Jira Service Desk Widget with a specific Jira Service Desk project")
	cmd.Flags().StringVar(&bodyKey, "key", "", "The unique identifier for this app, for example 'com.atlassian.confluence.plugins.confluence-questions'")
	cmd.Flags().StringVar(&bodyLastModified, "last-modified", "", "Date and time the app was last updated")
	cmd.Flags().StringVar(&bodyLegacyDescription, "legacy-description", "", "A general description of the app")
	cmd.Flags().StringVar(&bodyLegacyVendorLinksBuilds, "legacy-vendor-links-builds", "", "Link to a continuous integration server for the app")
	cmd.Flags().StringVar(&bodyLegacyVendorLinksSource, "legacy-vendor-links-source", "", "Link to a source control repository for the app")
	cmd.Flags().StringVar(&bodyLegacyVendorLinksWiki, "legacy-vendor-links-wiki", "", "Link to a wiki related to the app")
	cmd.Flags().StringVar(&bodyMarketingMarketingLabels, "marketing-marketing-labels", "", "List of labels that groups an app for marketing purposes")
	cmd.Flags().StringVar(&bodyName, "name", "", "The display name of the app, for example 'Questions for Confluence'")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Indicates whether the app is public, private, or pending approval")
	cmd.Flags().StringVar(&bodyStatusAfterApproval, "status-after-approval", "", "The status the app will transition to after it has been approved. If not specified, this will be Public")
	cmd.Flags().StringVar(&bodySummary, "summary", "", "Summary of the app's functionality")
	cmd.Flags().StringVar(&bodyTagLine, "tag-line", "", "Short phrase that summarizes what the app does and will be displayed as a heading on the app details page")
	cmd.Flags().StringVar(&bodyTagsCategory, "tags-category", "", "List of product tags for category associated with this app")
	cmd.Flags().StringVar(&bodyTagsKeywords, "tags-keywords", "", "List of product tags for keywords associated with this app")
	cmd.Flags().StringVar(&bodyTagsMarketing, "tags-marketing", "", "List of product tags for marketing associated with this app")
	cmd.Flags().StringVar(&bodyVendorLinksAppStatusPage, "vendor-links-app-status-page", "", "Link to an status page for the app")
	cmd.Flags().StringVar(&bodyVendorLinksForums, "vendor-links-forums", "", "Link to a forum where users can ask and discuss topics about the app")
	cmd.Flags().StringVar(&bodyVendorLinksIssueTracker, "vendor-links-issue-tracker", "", "Link to a work item tracker for the app")
	cmd.Flags().StringVar(&bodyVendorLinksPrivacy, "vendor-links-privacy", "", "Link to a data security and privacy statement page for the app")
	cmd.Flags().StringVar(&bodyVendorLinksSupportTicketSystem, "vendor-links-support-ticket-system", "", "Link to a support ticket system for the app")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
