// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsPricingGetCmd(flags *rootFlags) *cobra.Command {
	var flagCloudOrServer string
	var flagLiveOrPending string
	var flagCloudComplianceBoundary string

	cmd := &cobra.Command{
		Use:         "get <addonKey>",
		Short:       "Get pricing for the specified app. Live pricing is visible to all users.",
		Example:     "  jira-pp-cli-pp-cli addons pricing get your-token-here --cloud-or-server cloud --live-or-pending live",
		Annotations: map[string]string{"pp:endpoint": "pricing.get", "pp:method": "GET", "pp:path": "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/pricing/{cloudOrServer}/{liveOrPending}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("cloud-or-server") {
				allowedCloudOrServer := []string{"cloud", "datacenter", "server"}
				validCloudOrServer := false
				for _, v := range allowedCloudOrServer {
					if flagCloudOrServer == v {
						validCloudOrServer = true
						break
					}
				}
				if !validCloudOrServer {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "cloud-or-server", flagCloudOrServer, allowedCloudOrServer)
				}
			}
			if cmd.Flags().Changed("live-or-pending") {
				allowedLiveOrPending := []string{"live", "pending"}
				validLiveOrPending := false
				for _, v := range allowedLiveOrPending {
					if flagLiveOrPending == v {
						validLiveOrPending = true
						break
					}
				}
				if !validLiveOrPending {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "live-or-pending", flagLiveOrPending, allowedLiveOrPending)
				}
			}
			if cmd.Flags().Changed("cloud-compliance-boundary") {
				allowedCloudComplianceBoundary := []string{"commercial", "fedramp_moderate", "isolated_cloud"}
				validCloudComplianceBoundary := false
				for _, v := range allowedCloudComplianceBoundary {
					if flagCloudComplianceBoundary == v {
						validCloudComplianceBoundary = true
						break
					}
				}
				if !validCloudComplianceBoundary {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "cloud-compliance-boundary", flagCloudComplianceBoundary, allowedCloudComplianceBoundary)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/pricing/{cloudOrServer}/{liveOrPending}"
			path = replacePathParam(path, "addonKey", args[0])
			path = replacePathParam(path, "cloudOrServer", fmt.Sprintf("%v", flagCloudOrServer))
			path = replacePathParam(path, "liveOrPending", fmt.Sprintf("%v", flagLiveOrPending))
			params := map[string]string{}
			if flagCloudComplianceBoundary != "" {
				params["cloudComplianceBoundary"] = fmt.Sprintf("%v", flagCloudComplianceBoundary)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "pricing", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCloudOrServer, "cloud-or-server", "cloud", "Cloud or server (one of: cloud, datacenter, server)")
	cmd.Flags().StringVar(&flagLiveOrPending, "live-or-pending", "live", "Specifies either the pricing that is currently in effect and visible to users (live) (one of: live, pending)")
	cmd.Flags().StringVar(&flagCloudComplianceBoundary, "cloud-compliance-boundary", "", "The cloud compliance boundary for which the pricing is to be fetched, with 'commercial' as the default for cloud apps. (one of: commercial, fedramp_moderate, isolated_cloud)")

	return cmd
}
