// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsReviewsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyEmbeddedAuthorEmail string
	var bodyEmbeddedAuthorName string
	var bodyEmbeddedResponseText string
	var bodyLinksAlternateHref string
	var bodyLinksAlternateTitle string
	var bodyLinksAlternateType string
	var bodyLinksAuthor string
	var bodyLinksFlagHref string
	var bodyLinksFlagTitle string
	var bodyLinksFlagType string
	var bodyLinksResponseHref string
	var bodyLinksResponseTitle string
	var bodyLinksResponseType string
	var bodyLinksSelfHref string
	var bodyLinksSelfTitle string
	var bodyLinksSelfType string
	var bodyLinksVoteDownHref string
	var bodyLinksVoteDownTitle string
	var bodyLinksVoteDownType string
	var bodyLinksVoteUpHref string
	var bodyLinksVoteUpTitle string
	var bodyLinksVoteUpType string
	var bodyDate string
	var bodyHelpfulVotes int
	var bodyHosting string
	var bodyReview string
	var bodyStars int
	var bodyTotalVotes int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <addonKey>",
		Short:       "Create or update a specific app review written by the current user. This resource requires authentication.",
		Example:     "  jira-pp-cli-pp-cli addons reviews update your-token-here",
		Annotations: map[string]string{"pp:endpoint": "reviews.update", "pp:method": "PUT", "pp:path": "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/reviews/mine"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("embedded-author-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-author-name")
				}
				if !cmd.Flags().Changed("embedded-response-text") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "embedded-response-text")
				}
				if !cmd.Flags().Changed("links-alternate-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-alternate-href")
				}
				if !cmd.Flags().Changed("links-flag-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-flag-href")
				}
				if !cmd.Flags().Changed("links-response-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-response-href")
				}
				if !cmd.Flags().Changed("links-self-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-self-href")
				}
				if !cmd.Flags().Changed("links-vote-down-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-vote-down-href")
				}
				if !cmd.Flags().Changed("links-vote-up-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-vote-up-href")
				}
				if !cmd.Flags().Changed("stars") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "stars")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons/{addonKey}/reviews/mine"
			path = replacePathParam(path, "addonKey", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedEmbedded := map[string]any{}
					{
						nestedEmbeddedAuthor := map[string]any{}
						if bodyEmbeddedAuthorEmail != "" {
							nestedEmbeddedAuthor["email"] = bodyEmbeddedAuthorEmail
						}
						if bodyEmbeddedAuthorName != "" {
							nestedEmbeddedAuthor["name"] = bodyEmbeddedAuthorName
						}
						if len(nestedEmbeddedAuthor) > 0 {
							nestedEmbedded["author"] = nestedEmbeddedAuthor
						}
					}
					{
						nestedEmbeddedResponse := map[string]any{}
						if bodyEmbeddedResponseText != "" {
							nestedEmbeddedResponse["text"] = bodyEmbeddedResponseText
						}
						if len(nestedEmbeddedResponse) > 0 {
							nestedEmbedded["response"] = nestedEmbeddedResponse
						}
					}
					if len(nestedEmbedded) > 0 {
						body["_embedded"] = nestedEmbedded
					}
				}
				{
					nestedLinks := map[string]any{}
					{
						nestedLinksAlternate := map[string]any{}
						if bodyLinksAlternateHref != "" {
							nestedLinksAlternate["href"] = bodyLinksAlternateHref
						}
						if bodyLinksAlternateTitle != "" {
							nestedLinksAlternate["title"] = bodyLinksAlternateTitle
						}
						if bodyLinksAlternateType != "" {
							nestedLinksAlternate["type"] = bodyLinksAlternateType
						}
						if len(nestedLinksAlternate) > 0 {
							nestedLinks["alternate"] = nestedLinksAlternate
						}
					}
					if bodyLinksAuthor != "" {
						var parsedLinksAuthor any
						if err := json.Unmarshal([]byte(bodyLinksAuthor), &parsedLinksAuthor); err != nil {
							return fmt.Errorf("parsing --links-author JSON: %w", err)
						}
						nestedLinks["author"] = parsedLinksAuthor
					}
					{
						nestedLinksFlag := map[string]any{}
						if bodyLinksFlagHref != "" {
							nestedLinksFlag["href"] = bodyLinksFlagHref
						}
						if bodyLinksFlagTitle != "" {
							nestedLinksFlag["title"] = bodyLinksFlagTitle
						}
						if bodyLinksFlagType != "" {
							nestedLinksFlag["type"] = bodyLinksFlagType
						}
						if len(nestedLinksFlag) > 0 {
							nestedLinks["flag"] = nestedLinksFlag
						}
					}
					{
						nestedLinksResponse := map[string]any{}
						if bodyLinksResponseHref != "" {
							nestedLinksResponse["href"] = bodyLinksResponseHref
						}
						if bodyLinksResponseTitle != "" {
							nestedLinksResponse["title"] = bodyLinksResponseTitle
						}
						if bodyLinksResponseType != "" {
							nestedLinksResponse["type"] = bodyLinksResponseType
						}
						if len(nestedLinksResponse) > 0 {
							nestedLinks["response"] = nestedLinksResponse
						}
					}
					{
						nestedLinksSelf := map[string]any{}
						if bodyLinksSelfHref != "" {
							nestedLinksSelf["href"] = bodyLinksSelfHref
						}
						if bodyLinksSelfTitle != "" {
							nestedLinksSelf["title"] = bodyLinksSelfTitle
						}
						if bodyLinksSelfType != "" {
							nestedLinksSelf["type"] = bodyLinksSelfType
						}
						if len(nestedLinksSelf) > 0 {
							nestedLinks["self"] = nestedLinksSelf
						}
					}
					{
						nestedLinksVoteDown := map[string]any{}
						if bodyLinksVoteDownHref != "" {
							nestedLinksVoteDown["href"] = bodyLinksVoteDownHref
						}
						if bodyLinksVoteDownTitle != "" {
							nestedLinksVoteDown["title"] = bodyLinksVoteDownTitle
						}
						if bodyLinksVoteDownType != "" {
							nestedLinksVoteDown["type"] = bodyLinksVoteDownType
						}
						if len(nestedLinksVoteDown) > 0 {
							nestedLinks["voteDown"] = nestedLinksVoteDown
						}
					}
					{
						nestedLinksVoteUp := map[string]any{}
						if bodyLinksVoteUpHref != "" {
							nestedLinksVoteUp["href"] = bodyLinksVoteUpHref
						}
						if bodyLinksVoteUpTitle != "" {
							nestedLinksVoteUp["title"] = bodyLinksVoteUpTitle
						}
						if bodyLinksVoteUpType != "" {
							nestedLinksVoteUp["type"] = bodyLinksVoteUpType
						}
						if len(nestedLinksVoteUp) > 0 {
							nestedLinks["voteUp"] = nestedLinksVoteUp
						}
					}
					if len(nestedLinks) > 0 {
						body["_links"] = nestedLinks
					}
				}
				if bodyDate != "" {
					body["date"] = bodyDate
				}
				if bodyHelpfulVotes != 0 {
					body["helpfulVotes"] = bodyHelpfulVotes
				}
				if bodyHosting != "" {
					body["hosting"] = bodyHosting
				}
				if bodyReview != "" {
					body["review"] = bodyReview
				}
				if bodyStars != 0 {
					body["stars"] = bodyStars
				}
				if bodyTotalVotes != 0 {
					body["totalVotes"] = bodyTotalVotes
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "reviews", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "reviews", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reviews", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reviews", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reviews", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "reviews",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reviews", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reviews", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyEmbeddedAuthorEmail, "embedded-author-email", "", "The user's email address")
	cmd.Flags().StringVar(&bodyEmbeddedAuthorName, "embedded-author-name", "", "The display name of the user, for example 'John Smith'")
	cmd.Flags().StringVar(&bodyEmbeddedResponseText, "embedded-response-text", "", "Text of the response to the review")
	cmd.Flags().StringVar(&bodyLinksAlternateHref, "links-alternate-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksAlternateTitle, "links-alternate-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksAlternateType, "links-alternate-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksAuthor, "links-author", "", "This field is deprecated and will be removed soon")
	cmd.Flags().StringVar(&bodyLinksFlagHref, "links-flag-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksFlagTitle, "links-flag-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksFlagType, "links-flag-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksResponseHref, "links-response-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksResponseTitle, "links-response-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksResponseType, "links-response-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksSelfHref, "links-self-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksSelfTitle, "links-self-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksSelfType, "links-self-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksVoteDownHref, "links-vote-down-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksVoteDownTitle, "links-vote-down-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksVoteDownType, "links-vote-down-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksVoteUpHref, "links-vote-up-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksVoteUpTitle, "links-vote-up-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksVoteUpType, "links-vote-up-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyDate, "date", "", "The date when the app was reviewed")
	cmd.Flags().IntVar(&bodyHelpfulVotes, "helpful-votes", 0, "Number of helpful votes")
	cmd.Flags().StringVar(&bodyHosting, "hosting", "", "The review hosting type, either cloud or server")
	cmd.Flags().StringVar(&bodyReview, "review", "", "App review content")
	cmd.Flags().IntVar(&bodyStars, "stars", 0, "Number of stars")
	cmd.Flags().IntVar(&bodyTotalVotes, "total-votes", 0, "Total number of votes")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
