// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAddonsGetVendorCmd(flags *rootFlags) *cobra.Command {
	var flagApplication string
	var flagApplicationBuild int
	var flagCategory string
	var flagCost string
	var flagFilter string
	var flagForThisUser bool
	var flagHosting string
	var flagCloudComplianceBoundaries string
	var flagIncludeHidden string
	var flagIncludePrivate bool
	var flagMarketingLabel string
	var flagText string
	var flagWithVersion bool
	var flagOffset string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-vendor <vendorId>",
		Short:       "Get a list of apps for the specified vendor.",
		Example:     "  jira-pp-cli-pp-cli addons get-vendor 42",
		Annotations: map[string]string{"pp:endpoint": "addons.get-vendor", "pp:method": "GET", "pp:path": "https://marketplace.atlassian.com/rest/2/addons/vendor/{vendorId}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("cost") {
				allowedCost := []string{"free", "marketplace", "orderable", "paid"}
				validCost := false
				for _, v := range allowedCost {
					if flagCost == v {
						validCost = true
						break
					}
				}
				if !validCost {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "cost", flagCost, allowedCost)
				}
			}
			if cmd.Flags().Changed("filter") {
				allowedFilter := []string{"atlassian", "codegeist", "featured", "highest-rated", "name", "new", "popular", "recent", "top-grossing", "top-vendor", "trending", "verified"}
				validFilter := false
				for _, v := range allowedFilter {
					if flagFilter == v {
						validFilter = true
						break
					}
				}
				if !validFilter {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "filter", flagFilter, allowedFilter)
				}
			}
			if cmd.Flags().Changed("include-hidden") {
				allowedIncludeHidden := []string{"all", "visibleInApp"}
				validIncludeHidden := false
				for _, v := range allowedIncludeHidden {
					if flagIncludeHidden == v {
						validIncludeHidden = true
						break
					}
				}
				if !validIncludeHidden {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "include-hidden", flagIncludeHidden, allowedIncludeHidden)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/addons/vendor/{vendorId}"
			path = replacePathParam(path, "vendorId", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "addons", path, map[string]string{
				"application":               fmt.Sprintf("%v", flagApplication),
				"applicationBuild":          fmt.Sprintf("%v", flagApplicationBuild),
				"category":                  fmt.Sprintf("%v", flagCategory),
				"cost":                      fmt.Sprintf("%v", flagCost),
				"filter":                    fmt.Sprintf("%v", flagFilter),
				"forThisUser":               fmt.Sprintf("%v", flagForThisUser),
				"hosting":                   fmt.Sprintf("%v", flagHosting),
				"cloudComplianceBoundaries": fmt.Sprintf("%v", flagCloudComplianceBoundaries),
				"includeHidden":             fmt.Sprintf("%v", flagIncludeHidden),
				"includePrivate":            fmt.Sprintf("%v", flagIncludePrivate),
				"marketingLabel":            fmt.Sprintf("%v", flagMarketingLabel),
				"text":                      fmt.Sprintf("%v", flagText),
				"withVersion":               fmt.Sprintf("%v", flagWithVersion),
				"offset":                    fmt.Sprintf("%v", flagOffset),
				"limit":                     fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "offset", "offset", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagApplication, "application", "", "Only returns apps compatible with this application")
	cmd.Flags().IntVar(&flagApplicationBuild, "application-build", 0, "Only returns apps compatible with the specified application build number")
	cmd.Flags().StringVar(&flagCategory, "category", "", "Only returns apps with any of the specified categories")
	cmd.Flags().StringVar(&flagCost, "cost", "", "Only returns apps with the specified payment model (one of: free, marketplace, orderable, paid)")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "Return apps filtered or sorted using the specified parameter (one of: atlassian, codegeist, featured, highest-rated, name, new, popular, recent, top-grossing, top-vendor, trending, verified)")
	cmd.Flags().BoolVar(&flagForThisUser, "for-this-user", false, "Only returns apps from vendors associated with the current user")
	cmd.Flags().StringVar(&flagHosting, "hosting", "", "Only returns apps with the specified hosting model")
	cmd.Flags().StringVar(&flagCloudComplianceBoundaries, "cloud-compliance-boundaries", "", "Only returns apps with the specified cloud compliance boundaries")
	cmd.Flags().StringVar(&flagIncludeHidden, "include-hidden", "", "Includes apps that are normally hidden in the site (one of: all, visibleInApp)")
	cmd.Flags().BoolVar(&flagIncludePrivate, "include-private", false, "Includes private apps or versions if you are authorized to see them")
	cmd.Flags().StringVar(&flagMarketingLabel, "marketing-label", "", "Only returns apps with the specified marketing labels")
	cmd.Flags().StringVar(&flagText, "text", "", "Only returns apps that match the search text")
	cmd.Flags().BoolVar(&flagWithVersion, "with-version", false, "Includes the latest compatible version in the response")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "If specified, skips ahead by this number of items")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "If specified, limits the result set to this number of items")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
