// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAddonsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "addons",
		Short:  "List, get, create, and update addons",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAddonsCreateCmd(flags))
	cmd.AddCommand(newAddonsGetCmd(flags))
	cmd.AddCommand(newAddonsGetArchivedCmd(flags))
	cmd.AddCommand(newAddonsGetVendorCmd(flags))
	cmd.AddCommand(newAddonsListCmd(flags))
	cmd.AddCommand(newAddonsListArchivedCmd(flags))
	cmd.AddCommand(newAddonsListListingsCmd(flags))
	cmd.AddCommand(newAddonsListSearchCmd(flags))
	cmd.AddCommand(newAddonsUpdateCmd(flags))
	cmd.AddCommand(newAddonsApprovalCmd(flags))
	cmd.AddCommand(newAddonsDistributionCmd(flags))
	cmd.AddCommand(newAddonsFeedbacksCmd(flags))
	cmd.AddCommand(newAddonsMigrationCmd(flags))
	cmd.AddCommand(newAddonsPricingCmd(flags))
	cmd.AddCommand(newAddonsPrivacyAndSecurityCmd(flags))
	cmd.AddCommand(newAddonsRecommendationsCmd(flags))
	cmd.AddCommand(newAddonsReleaseCmd(flags))
	cmd.AddCommand(newAddonsReviewsCmd(flags))
	cmd.AddCommand(newAddonsTokensCmd(flags))
	cmd.AddCommand(newAddonsVersionsCmd(flags))
	cmd.AddCommand(newAddonsWatchCmd(flags))
	return cmd
}
