// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAgileGetAllBoardsCmd(flags *rootFlags) *cobra.Command {
	var flagStartAt int
	var flagMaxResults int
	var flagType string
	var flagName string
	var flagProjectKeyOrId string
	var flagAccountIdLocation string
	var flagProjectLocation string
	var flagIncludePrivate bool
	var flagNegateLocationFiltering bool
	var flagOrderBy string
	var flagExpand string
	var flagProjectTypeLocation string
	var flagFilterId string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-all-boards",
		Aliases:     []string{"list"},
		Short:       "Returns all boards. This only includes boards that the user has permission to view.",
		Example:     "  jira-pp-cli-pp-cli agile get-all-boards",
		Annotations: map[string]string{"pp:endpoint": "agile.get-all-boards", "pp:method": "GET", "pp:path": "/rest/agile/1.0/board", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("order-by") {
				allowedOrderBy := []string{"name", "-name", "+name"}
				validOrderBy := false
				for _, v := range allowedOrderBy {
					if flagOrderBy == v {
						validOrderBy = true
						break
					}
				}
				if !validOrderBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order-by", flagOrderBy, allowedOrderBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/agile/1.0/board"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "agile", path, map[string]string{
				"startAt":                 fmt.Sprintf("%v", flagStartAt),
				"maxResults":              fmt.Sprintf("%v", flagMaxResults),
				"type":                    fmt.Sprintf("%v", flagType),
				"name":                    fmt.Sprintf("%v", flagName),
				"projectKeyOrId":          fmt.Sprintf("%v", flagProjectKeyOrId),
				"accountIdLocation":       fmt.Sprintf("%v", flagAccountIdLocation),
				"projectLocation":         fmt.Sprintf("%v", flagProjectLocation),
				"includePrivate":          fmt.Sprintf("%v", flagIncludePrivate),
				"negateLocationFiltering": fmt.Sprintf("%v", flagNegateLocationFiltering),
				"orderBy":                 fmt.Sprintf("%v", flagOrderBy),
				"expand":                  fmt.Sprintf("%v", flagExpand),
				"projectTypeLocation":     fmt.Sprintf("%v", flagProjectTypeLocation),
				"filterId":                fmt.Sprintf("%v", flagFilterId),
			}, nil, flagAll, "", "offset", "maxResults", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagStartAt, "start-at", 0, "The starting index of the returned boards. Base index: 0.")
	cmd.Flags().IntVar(&flagMaxResults, "max-results", 50, "The maximum number of boards to return per page. See the 'Pagination' section at the top of this page for more details.")
	cmd.Flags().StringVar(&flagType, "type", "", "Filters results to boards of the specified types. Valid values: scrum, kanban, simple.")
	cmd.Flags().StringVar(&flagName, "name", "", "Filters results to boards that match or partially match the specified name.")
	cmd.Flags().StringVar(&flagProjectKeyOrId, "project-key-or-id", "", "Filters results to boards that are relevant to a project.")
	cmd.Flags().StringVar(&flagAccountIdLocation, "account-id-location", "", "Account id location")
	cmd.Flags().StringVar(&flagProjectLocation, "project-location", "", "Project location")
	cmd.Flags().BoolVar(&flagIncludePrivate, "include-private", false, "Appends private boards to the end of the list. The name and type fields are excluded for security reasons.")
	cmd.Flags().BoolVar(&flagNegateLocationFiltering, "negate-location-filtering", false, "If set to true, negate filters used for querying by location. By default false.")
	cmd.Flags().StringVar(&flagOrderBy, "order-by", "", "Ordering of the results by a given field. If not provided, values will not be sorted. Valid values: name. (one of: name, -name, +name)")
	cmd.Flags().StringVar(&flagExpand, "expand", "", "List of fields to expand for each board. Valid values: admins, permissions.")
	cmd.Flags().StringVar(&flagProjectTypeLocation, "project-type-location", "", "Filters results to boards that are relevant to a project types. Support Jira Software, Jira Service Management.")
	cmd.Flags().StringVar(&flagFilterId, "filter-id", "", "Filters results to boards that are relevant to a filter. Not supported for next-gen boards.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
