// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAgileGetBoardIssuesForEpicCmd(flags *rootFlags) *cobra.Command {
	var flagStartAt int
	var flagMaxResults int
	var flagJql string
	var flagValidateQuery bool
	var flagFields string
	var flagExpand string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-board-issues-for-epic <boardId> <epicId>",
		Short:       "Returns all issues that belong to an epic on the board, for the given epic ID and the board ID.",
		Example:     "  jira-pp-cli-pp-cli agile get-board-issues-for-epic 42 42",
		Annotations: map[string]string{"pp:endpoint": "agile.get-board-issues-for-epic", "pp:method": "GET", "pp:path": "/rest/agile/1.0/board/{boardId}/epic/{epicId}/issue", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/agile/1.0/board/{boardId}/epic/{epicId}/issue"
			path = replacePathParam(path, "boardId", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("epicId is required\nUsage: %s <%s>", cmd.CommandPath(), "epicId"))
			}
			path = replacePathParam(path, "epicId", args[1])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "agile", path, map[string]string{
				"startAt":       fmt.Sprintf("%v", flagStartAt),
				"maxResults":    fmt.Sprintf("%v", flagMaxResults),
				"jql":           fmt.Sprintf("%v", flagJql),
				"validateQuery": fmt.Sprintf("%v", flagValidateQuery),
				"fields":        fmt.Sprintf("%v", flagFields),
				"expand":        fmt.Sprintf("%v", flagExpand),
			}, nil, flagAll, "", "offset", "maxResults", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagStartAt, "start-at", 0, "The starting index of the returned issues. Base index: 0.")
	cmd.Flags().IntVar(&flagMaxResults, "max-results", 0, "The maximum number of issues to return per page. Default: 50.")
	cmd.Flags().StringVar(&flagJql, "jql", "", "Filters results using a JQL query.")
	cmd.Flags().BoolVar(&flagValidateQuery, "validate-query", false, "Specifies whether to validate the JQL query or not. Default: true.")
	cmd.Flags().StringVar(&flagFields, "fields", "", "The list of fields to return for each issue. By default, all navigable and Agile fields are returned.")
	cmd.Flags().StringVar(&flagExpand, "expand", "", "A comma-separated list of the parameters to expand.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
