// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAppCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "app",
		Short:  "Get and update app",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAppGetCustomFieldConfigurationCmd(flags))
	cmd.AddCommand(newAppGetCustomFieldsConfigurationsCmd(flags))
	cmd.AddCommand(newAppUpdateCustomFieldConfigurationCmd(flags))
	cmd.AddCommand(newAppUpdateCustomFieldValueCmd(flags))
	cmd.AddCommand(newAppUpdateMultipleCustomFieldValuesCmd(flags))
	return cmd
}
