// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newApplicationPropertiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "application-properties",
		Short:  "Get and update application properties",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newApplicationPropertiesGetAdvancedSettingsCmd(flags))
	cmd.AddCommand(newApplicationPropertiesGetApplicationPropertyCmd(flags))
	cmd.AddCommand(newApplicationPropertiesSetApplicationPropertyCmd(flags))
	return cmd
}
