// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAtlassianAccessUsersRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "roles",
		Short: "Create roles for atlassian access users",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAtlassianAccessUsersRolesAssignCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersRolesRevokeCmd(flags))
	return cmd
}
