// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAtlassianAccessEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "atlassian-access-events",
		Short:  "Get atlassian access events",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAtlassianAccessEventsGetCmd(flags))
	cmd.AddCommand(newAtlassianAccessEventsGetByIdCmd(flags))
	return cmd
}
