// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAtlassianAccessUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "atlassian-access-users",
		Short:  "Get, search, and create atlassian access users",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAtlassianAccessUsersCreateCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersCreateOrgsCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersGetCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersSearchCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersRoleAssignmentsCmd(flags))
	cmd.AddCommand(newAtlassianAccessUsersRolesCmd(flags))
	return cmd
}
