// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBuildsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "builds",
		Short:  "APIs related to integrating build data with Jira Software. These APIs are available to Atlassian Connect apps.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBuildsDeleteByKeyCmd(flags))
	cmd.AddCommand(newBuildsDeleteByPropertyCmd(flags))
	cmd.AddCommand(newBuildsGetByKeyCmd(flags))
	cmd.AddCommand(newBuildsSubmitCmd(flags))
	return cmd
}
