// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDashboardCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "dashboard",
		Short:  "This resource represents dashboards.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDashboardBulkEditCmd(flags))
	cmd.AddCommand(newDashboardCreateCmd(flags))
	cmd.AddCommand(newDashboardDeleteCmd(flags))
	cmd.AddCommand(newDashboardGetCmd(flags))
	cmd.AddCommand(newDashboardGetAllCmd(flags))
	cmd.AddCommand(newDashboardGetAllAvailableGadgetsCmd(flags))
	cmd.AddCommand(newDashboardGetPaginatedCmd(flags))
	cmd.AddCommand(newDashboardUpdateCmd(flags))
	cmd.AddCommand(newDashboardCopyCmd(flags))
	cmd.AddCommand(newDashboardGadgetCmd(flags))
	cmd.AddCommand(newDashboardItemsCmd(flags))
	return cmd
}
