// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDevinfoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "devinfo",
		Short:  "Get, create, and delete devinfo",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDevinfoDeleteByPropertiesCmd(flags))
	cmd.AddCommand(newDevinfoDeleteEntityCmd(flags))
	cmd.AddCommand(newDevinfoDeleteRepositoryCmd(flags))
	cmd.AddCommand(newDevinfoExistsByPropertiesCmd(flags))
	cmd.AddCommand(newDevinfoGetRepositoryCmd(flags))
	cmd.AddCommand(newDevinfoStoreDevelopmentInformationCmd(flags))
	return cmd
}
