// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDevopscomponentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "devopscomponents",
		Short:  "Get, delete, and submit devopscomponents",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDevopscomponentsDeleteComponentByIdCmd(flags))
	cmd.AddCommand(newDevopscomponentsDeleteComponentsByPropertyCmd(flags))
	cmd.AddCommand(newDevopscomponentsGetComponentByIdCmd(flags))
	cmd.AddCommand(newDevopscomponentsSubmitComponentsCmd(flags))
	return cmd
}
