// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDirectoriesUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Get, create, and delete users for directories",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDirectoriesUsersCreateCmd(flags))
	cmd.AddCommand(newDirectoriesUsersCreateOrgsCmd(flags))
	cmd.AddCommand(newDirectoriesUsersDeleteCmd(flags))
	cmd.AddCommand(newDirectoriesUsersGetDirectoryCmd(flags))
	cmd.AddCommand(newDirectoriesUsersGetDirectoryCountCmd(flags))
	cmd.AddCommand(newDirectoriesUsersGetDirectoryDetailsCmd(flags))
	cmd.AddCommand(newDirectoriesUsersGetRoleAssignmentsCmd(flags))
	cmd.AddCommand(newDirectoriesUsersGetStatsCmd(flags))
	return cmd
}
