// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDirectoriesGroupsGetCmd(flags *rootFlags) *cobra.Command {
	var flagCursor string
	var flagLimit int
	var flagDirectoryIds string
	var flagAccountIds string
	var flagGroupIds string
	var flagResourceOwners string
	var flagResourceIds string
	var flagSearchTerm string
	var flagCounts string
	var flagSortBy string
	var flagRoleIds string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get <orgId> <directoryId>",
		Short:       "Returns a page of groups in an organization that match the supplied parameters.",
		Example:     "  jira-pp-cli-pp-cli directories groups get 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "groups.get", "pp:method": "GET", "pp:path": "https://api.atlassian.com/admin/v2/orgs/{orgId}/directories/{directoryId}/groups", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://api.atlassian.com/admin/v2/orgs/{orgId}/directories/{directoryId}/groups"
			path = replacePathParam(path, "orgId", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("directoryId is required\nUsage: %s <%s>", cmd.CommandPath(), "directoryId"))
			}
			path = replacePathParam(path, "directoryId", args[1])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "groups", path, map[string]string{
				"cursor":         fmt.Sprintf("%v", flagCursor),
				"limit":          fmt.Sprintf("%v", flagLimit),
				"directoryIds":   fmt.Sprintf("%v", flagDirectoryIds),
				"accountIds":     fmt.Sprintf("%v", flagAccountIds),
				"groupIds":       fmt.Sprintf("%v", flagGroupIds),
				"resourceOwners": fmt.Sprintf("%v", flagResourceOwners),
				"resourceIds":    fmt.Sprintf("%v", flagResourceIds),
				"searchTerm":     fmt.Sprintf("%v", flagSearchTerm),
				"counts":         fmt.Sprintf("%v", flagCounts),
				"sortBy":         fmt.Sprintf("%v", flagSortBy),
				"roleIds":        fmt.Sprintf("%v", flagRoleIds),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Sets the cursor position to retrieve the next set of results.")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "The desired number of results for the search request.")
	cmd.Flags().StringVar(&flagDirectoryIds, "directory-ids", "", "A list of directory IDs. The requestor must have permissions to administer resources linked to these directories.")
	cmd.Flags().StringVar(&flagAccountIds, "account-ids", "", "A list of user account IDs.")
	cmd.Flags().StringVar(&flagGroupIds, "group-ids", "", "A list of group IDs.")
	cmd.Flags().StringVar(&flagResourceOwners, "resource-owners", "", "The list of resource owners to filter the results by.")
	cmd.Flags().StringVar(&flagResourceIds, "resource-ids", "", "A list of resource IDs. The resource IDs should be specified using the Atlassian Resource Identifier (ARI) format.")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "A search term to search the `name` field.")
	cmd.Flags().StringVar(&flagCounts, "counts", "", "Whether to include counts of different objects associated with the group.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "The field and direction to sort the results by. Currently, only a single field can be sorted by.")
	cmd.Flags().StringVar(&flagRoleIds, "role-ids", "", "A list of role IDs.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
