// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newExpressionEvaluateJsisjiraCmd(flags *rootFlags) *cobra.Command {
	var flagExpand string
	var bodyContextBoard int
	var bodyContextCustom string
	var bodyContextCustomerRequest int
	var bodyContextIssueId int
	var bodyContextIssueKey string
	var bodyContextProjectId int
	var bodyContextProjectKey string
	var bodyContextServiceDesk int
	var bodyContextSprint int
	var bodyExpression string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "evaluate-jsisjira",
		Short:       "Evaluates a Jira expression and returns its value.",
		Example:     "  jira-pp-cli-pp-cli expression evaluate-jsisjira --expression example-value",
		Annotations: map[string]string{"pp:endpoint": "expression.evaluate-jsisjira", "pp:method": "POST", "pp:path": "/rest/api/2/expression/evaluate"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("expression") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expression")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/expression/evaluate"
			params := map[string]string{}
			if flagExpand != "" {
				params["expand"] = fmt.Sprintf("%v", flagExpand)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedContext := map[string]any{}
					if bodyContextBoard != 0 {
						nestedContext["board"] = bodyContextBoard
					}
					if bodyContextCustom != "" {
						var parsedContextCustom any
						if err := json.Unmarshal([]byte(bodyContextCustom), &parsedContextCustom); err != nil {
							return fmt.Errorf("parsing --context-custom JSON: %w", err)
						}
						nestedContext["custom"] = parsedContextCustom
					}
					if bodyContextCustomerRequest != 0 {
						nestedContext["customerRequest"] = bodyContextCustomerRequest
					}
					{
						nestedContextIssue := map[string]any{}
						if bodyContextIssueId != 0 {
							nestedContextIssue["id"] = bodyContextIssueId
						}
						if bodyContextIssueKey != "" {
							nestedContextIssue["key"] = bodyContextIssueKey
						}
						if len(nestedContextIssue) > 0 {
							nestedContext["issue"] = nestedContextIssue
						}
					}
					{
						nestedContextIssues := map[string]any{}
						if len(nestedContextIssues) > 0 {
							nestedContext["issues"] = nestedContextIssues
						}
					}
					{
						nestedContextProject := map[string]any{}
						if bodyContextProjectId != 0 {
							nestedContextProject["id"] = bodyContextProjectId
						}
						if bodyContextProjectKey != "" {
							nestedContextProject["key"] = bodyContextProjectKey
						}
						if len(nestedContextProject) > 0 {
							nestedContext["project"] = nestedContextProject
						}
					}
					if bodyContextServiceDesk != 0 {
						nestedContext["serviceDesk"] = bodyContextServiceDesk
					}
					if bodyContextSprint != 0 {
						nestedContext["sprint"] = bodyContextSprint
					}
					if len(nestedContext) > 0 {
						body["context"] = nestedContext
					}
				}
				if bodyExpression != "" {
					body["expression"] = bodyExpression
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "expression", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "expression", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "expression", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "expression", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "expression", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "expression",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "expression", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "expression", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagExpand, "expand", "", "Use [expand](#expansion) to include additional information in the response. This parameter accepts `meta.")
	cmd.Flags().IntVar(&bodyContextBoard, "context-board", 0, "The ID of the board that is available under the `board` variable when evaluating the expression.")
	cmd.Flags().StringVar(&bodyContextCustom, "context-custom", "", "Custom context variables and their types.")
	cmd.Flags().IntVar(&bodyContextCustomerRequest, "context-customer-request", 0, "The ID of the customer request that is available under the `customerRequest` variable when evaluating the expression.")
	cmd.Flags().IntVar(&bodyContextIssueId, "context-issue-id", 0, "The ID of the referenced item.")
	cmd.Flags().StringVar(&bodyContextIssueKey, "context-issue-key", "", "The key of the referenced item.")
	cmd.Flags().IntVar(&bodyContextProjectId, "context-project-id", 0, "The ID of the referenced item.")
	cmd.Flags().StringVar(&bodyContextProjectKey, "context-project-key", "", "The key of the referenced item.")
	cmd.Flags().IntVar(&bodyContextServiceDesk, "context-service-desk", 0, "The ID of the service desk that is available under the `serviceDesk` variable when evaluating the expression.")
	cmd.Flags().IntVar(&bodyContextSprint, "context-sprint", 0, "The ID of the sprint that is available under the `sprint` variable when evaluating the expression.")
	cmd.Flags().StringVar(&bodyExpression, "expression", "", "The Jira expression to evaluate.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
