// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFieldRestoreCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Run restore operations for field",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFieldRestoreCustomFieldCmd(flags))
	return cmd
}
