// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssuetypeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "issuetype",
		Short:  "Get, create, update, and delete issuetype",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssuetypeCreateIssueTypeCmd(flags))
	cmd.AddCommand(newIssuetypeDeleteIssueTypeCmd(flags))
	cmd.AddCommand(newIssuetypeGetIssueAllTypesCmd(flags))
	cmd.AddCommand(newIssuetypeGetIssueTypeCmd(flags))
	cmd.AddCommand(newIssuetypeGetIssueTypesForProjectCmd(flags))
	cmd.AddCommand(newIssuetypeUpdateIssueTypeCmd(flags))
	cmd.AddCommand(newIssuetypeAlternativesCmd(flags))
	cmd.AddCommand(newIssuetypeAvatar2Cmd(flags))
	cmd.AddCommand(newIssuetypePropertiesCmd(flags))
	return cmd
}
