// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssuesecurityschemesLevelCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "level",
		Short: "Add, update, and remove level for issuesecurityschemes",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssuesecurityschemesLevelAddSecurityCmd(flags))
	cmd.AddCommand(newIssuesecurityschemesLevelAddSecurityMembersCmd(flags))
	cmd.AddCommand(newIssuesecurityschemesLevelRemoveCmd(flags))
	cmd.AddCommand(newIssuesecurityschemesLevelRemoveMemberFromSecurityCmd(flags))
	cmd.AddCommand(newIssuesecurityschemesLevelUpdateSecurityCmd(flags))
	return cmd
}
