// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssueLinkCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "issue-link",
		Short:  "This resource represents links between issues. Use it to get, create, and delete links between issues.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssueLinkDeleteCmd(flags))
	cmd.AddCommand(newIssueLinkGetCmd(flags))
	cmd.AddCommand(newIssueLinkLinkIssuesCmd(flags))
	return cmd
}
