// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssueAttachmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "attachments",
		Short: "Add attachments for issue",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssueAttachmentsAddCmd(flags))
	return cmd
}
