// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssueLinkTypeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "issue-link-type",
		Short:  "This resource represents [issue link](#api-group-Issue-links) types.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssueLinkTypeCreateCmd(flags))
	cmd.AddCommand(newIssueLinkTypeDeleteCmd(flags))
	cmd.AddCommand(newIssueLinkTypeGetCmd(flags))
	cmd.AddCommand(newIssueLinkTypeGetIssuelinktypeCmd(flags))
	cmd.AddCommand(newIssueLinkTypeUpdateCmd(flags))
	return cmd
}
