// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssuetypeAvatar2Cmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "avatar2",
		Short: "Create avatar2 for issuetype",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssuetypeAvatar2CreateIssueTypeAvatarCmd(flags))
	return cmd
}
