// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJiraCloudPlatformWorkflowCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "jira-cloud-platform-workflow",
		Short:  "Manage jira cloud platform workflow",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJiraCloudPlatformWorkflowCreateTransitionPropertyCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowDeleteInactiveCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowDeleteTransitionPropertyCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowDeleteTransitionRuleConfigurationsCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowGetPaginatedCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowGetTransitionPropertiesCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowGetTransitionRuleConfigurationsCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowListHistoryCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowReadFromHistoryCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowUpdateTransitionPropertyCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowUpdateTransitionRuleConfigurationsCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowProjectCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowProjectUsagesCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformWorkflowWorkflowSchemesCmd(flags))
	return cmd
}
