// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJiraCloudPlatformVersionRelatedworkCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "relatedwork",
		Short: "Get, create, update, and delete relatedwork for jira cloud platform version",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJiraCloudPlatformVersionRelatedworkCreateRelatedWorkCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformVersionRelatedworkDeleteRelatedWorkCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformVersionRelatedworkGetRelatedWorkCmd(flags))
	cmd.AddCommand(newJiraCloudPlatformVersionRelatedworkUpdateRelatedWorkCmd(flags))
	return cmd
}
