// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJiraCloudPlatformWorkflowWorkflowSchemesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workflow-schemes",
		Short: "This resource represents workflow schemes.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJiraCloudPlatformWorkflowWorkflowSchemesGetUsagesForWorkflowCmd(flags))
	return cmd
}
