// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJiraCloudPlatformVersionMergetoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "mergeto",
		Short: "Update mergeto for jira cloud platform version",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJiraCloudPlatformVersionMergetoMergeVersionsCmd(flags))
	return cmd
}
