// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotificationschemeNotificationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "notification",
		Short: "Add and remove notification for notificationscheme",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotificationschemeNotificationAddCmd(flags))
	cmd.AddCommand(newNotificationschemeNotificationRemoveFromSchemeCmd(flags))
	return cmd
}
