// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "orgs",
		Short:  "Manage orgs command groups",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrgsGetCmd(flags))
	cmd.AddCommand(newOrgsGetByIdCmd(flags))
	return cmd
}
