// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPermissionschemeUpdatePermissionSchemeCmd(flags *rootFlags) *cobra.Command {
	var flagExpand string
	var bodyDescription string
	var bodyExpand2 string
	var bodyId int
	var bodyName string
	var bodyPermissions string
	var bodyScopeProjectId string
	var bodyScopeProjectKey string
	var bodyScopeProjectName string
	var bodyScopeProjectProjectTypeKey string
	var bodyScopeProjectSelf string
	var bodyScopeProjectSimplified bool
	var bodyScopeType string
	var bodySelf string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-permission-scheme <schemeId>",
		Aliases:     []string{"update"},
		Short:       "Updates a permission scheme.",
		Example:     "  jira-pp-cli-pp-cli permissionscheme update-permission-scheme 42 --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "permissionscheme.update-permission-scheme", "pp:method": "PUT", "pp:path": "/rest/api/2/permissionscheme/{schemeId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/permissionscheme/{schemeId}"
			path = replacePathParam(path, "schemeId", args[0])
			params := map[string]string{}
			if flagExpand != "" {
				params["expand"] = fmt.Sprintf("%v", flagExpand)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyExpand2 != "" {
					body["expand"] = bodyExpand2
				}
				if bodyId != 0 {
					body["id"] = bodyId
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPermissions != "" {
					var parsedPermissions any
					if err := json.Unmarshal([]byte(bodyPermissions), &parsedPermissions); err != nil {
						return fmt.Errorf("parsing --permissions JSON: %w", err)
					}
					body["permissions"] = parsedPermissions
				}
				{
					nestedScope := map[string]any{}
					{
						nestedScopeProject := map[string]any{}
						if bodyScopeProjectId != "" {
							nestedScopeProject["id"] = bodyScopeProjectId
						}
						if bodyScopeProjectKey != "" {
							nestedScopeProject["key"] = bodyScopeProjectKey
						}
						if bodyScopeProjectName != "" {
							nestedScopeProject["name"] = bodyScopeProjectName
						}
						if bodyScopeProjectProjectTypeKey != "" {
							nestedScopeProject["projectTypeKey"] = bodyScopeProjectProjectTypeKey
						}
						if bodyScopeProjectSelf != "" {
							nestedScopeProject["self"] = bodyScopeProjectSelf
						}
						if cmd.Flags().Changed("scope-project-simplified") {
							nestedScopeProject["simplified"] = bodyScopeProjectSimplified
						}
						if len(nestedScopeProject) > 0 {
							nestedScope["project"] = nestedScopeProject
						}
					}
					if bodyScopeType != "" {
						nestedScope["type"] = bodyScopeType
					}
					if len(nestedScope) > 0 {
						body["scope"] = nestedScope
					}
				}
				if bodySelf != "" {
					body["self"] = bodySelf
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "permissionscheme", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "permissionscheme", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "permissionscheme", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "permissionscheme", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "permissionscheme", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "permissionscheme",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "permissionscheme", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "permissionscheme", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagExpand, "expand", "", "Use expand to include additional information in the response. This parameter accepts a comma-separated list.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description for the permission scheme.")
	cmd.Flags().StringVar(&bodyExpand2, "expand-2", "", "The expand options available for the permission scheme.")
	cmd.Flags().IntVar(&bodyId, "id", 0, "The ID of the permission scheme.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the permission scheme. Must be unique.")
	cmd.Flags().StringVar(&bodyPermissions, "permissions", "", "The permission scheme to create or update. See [About permission schemes and grants](..")
	cmd.Flags().StringVar(&bodyScopeProjectId, "scope-project-id", "", "The ID of the project.")
	cmd.Flags().StringVar(&bodyScopeProjectKey, "scope-project-key", "", "The key of the project.")
	cmd.Flags().StringVar(&bodyScopeProjectName, "scope-project-name", "", "The name of the project.")
	cmd.Flags().StringVar(&bodyScopeProjectProjectTypeKey, "scope-project-project-type-key", "", "The [project type](https://confluence.atlassian.")
	cmd.Flags().StringVar(&bodyScopeProjectSelf, "scope-project-self", "", "The URL of the project details.")
	cmd.Flags().BoolVar(&bodyScopeProjectSimplified, "scope-project-simplified", false, "Whether or not the project is simplified.")
	cmd.Flags().StringVar(&bodyScopeType, "scope-type", "", "The type of scope.")
	cmd.Flags().StringVar(&bodySelf, "self", "", "The URL of the permission scheme.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
