// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPermissionschemeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "permissionscheme",
		Short:  "Get, create, update, and delete permissionscheme",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPermissionschemeCreatePermissionSchemeCmd(flags))
	cmd.AddCommand(newPermissionschemeDeletePermissionSchemeCmd(flags))
	cmd.AddCommand(newPermissionschemeGetAllPermissionSchemesCmd(flags))
	cmd.AddCommand(newPermissionschemeGetPermissionSchemeCmd(flags))
	cmd.AddCommand(newPermissionschemeUpdatePermissionSchemeCmd(flags))
	cmd.AddCommand(newPermissionschemePermissionCmd(flags))
	return cmd
}
