// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPlansCreateCmd(flags *rootFlags) *cobra.Command {
	var flagUseGroupId bool
	var bodyCrossProjectReleases string
	var bodyCustomFields string
	var bodyExclusionRulesIssueIds string
	var bodyExclusionRulesIssueTypeIds string
	var bodyExclusionRulesNumberOfDaysToShowCompletedIssues int
	var bodyExclusionRulesReleaseIds string
	var bodyExclusionRulesWorkStatusCategoryIds string
	var bodyExclusionRulesWorkStatusIds string
	var bodyIssueSources string
	var bodyLeadAccountId string
	var bodyName string
	var bodyPermissions string
	var bodySchedulingDependencies string
	var bodySchedulingEndDateDateCustomFieldId int
	var bodySchedulingEndDateType string
	var bodySchedulingEstimation string
	var bodySchedulingInferredDates string
	var bodySchedulingStartDateDateCustomFieldId int
	var bodySchedulingStartDateType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a plan. **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.",
		Example:     "  jira-pp-cli-pp-cli plans create --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "plans.create", "pp:method": "POST", "pp:path": "/rest/api/2/plans/plan"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("issue-sources") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "issue-sources")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("scheduling-end-date-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "scheduling-end-date-type")
				}
				if !cmd.Flags().Changed("scheduling-estimation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "scheduling-estimation")
				}
				if !cmd.Flags().Changed("scheduling-start-date-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "scheduling-start-date-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/plans/plan"
			params := map[string]string{}
			if flagUseGroupId != false {
				params["useGroupId"] = fmt.Sprintf("%v", flagUseGroupId)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCrossProjectReleases != "" {
					var parsedCrossProjectReleases any
					if err := json.Unmarshal([]byte(bodyCrossProjectReleases), &parsedCrossProjectReleases); err != nil {
						return fmt.Errorf("parsing --cross-project-releases JSON: %w", err)
					}
					body["crossProjectReleases"] = parsedCrossProjectReleases
				}
				if bodyCustomFields != "" {
					var parsedCustomFields any
					if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
						return fmt.Errorf("parsing --custom-fields JSON: %w", err)
					}
					body["customFields"] = parsedCustomFields
				}
				{
					nestedExclusionRules := map[string]any{}
					if bodyExclusionRulesIssueIds != "" {
						var parsedExclusionRulesIssueIds any
						if err := json.Unmarshal([]byte(bodyExclusionRulesIssueIds), &parsedExclusionRulesIssueIds); err != nil {
							return fmt.Errorf("parsing --exclusion-rules-issue-ids JSON: %w", err)
						}
						nestedExclusionRules["issueIds"] = parsedExclusionRulesIssueIds
					}
					if bodyExclusionRulesIssueTypeIds != "" {
						var parsedExclusionRulesIssueTypeIds any
						if err := json.Unmarshal([]byte(bodyExclusionRulesIssueTypeIds), &parsedExclusionRulesIssueTypeIds); err != nil {
							return fmt.Errorf("parsing --exclusion-rules-issue-type-ids JSON: %w", err)
						}
						nestedExclusionRules["issueTypeIds"] = parsedExclusionRulesIssueTypeIds
					}
					if bodyExclusionRulesNumberOfDaysToShowCompletedIssues != 0 {
						nestedExclusionRules["numberOfDaysToShowCompletedIssues"] = bodyExclusionRulesNumberOfDaysToShowCompletedIssues
					}
					if bodyExclusionRulesReleaseIds != "" {
						var parsedExclusionRulesReleaseIds any
						if err := json.Unmarshal([]byte(bodyExclusionRulesReleaseIds), &parsedExclusionRulesReleaseIds); err != nil {
							return fmt.Errorf("parsing --exclusion-rules-release-ids JSON: %w", err)
						}
						nestedExclusionRules["releaseIds"] = parsedExclusionRulesReleaseIds
					}
					if bodyExclusionRulesWorkStatusCategoryIds != "" {
						var parsedExclusionRulesWorkStatusCategoryIds any
						if err := json.Unmarshal([]byte(bodyExclusionRulesWorkStatusCategoryIds), &parsedExclusionRulesWorkStatusCategoryIds); err != nil {
							return fmt.Errorf("parsing --exclusion-rules-work-status-category-ids JSON: %w", err)
						}
						nestedExclusionRules["workStatusCategoryIds"] = parsedExclusionRulesWorkStatusCategoryIds
					}
					if bodyExclusionRulesWorkStatusIds != "" {
						var parsedExclusionRulesWorkStatusIds any
						if err := json.Unmarshal([]byte(bodyExclusionRulesWorkStatusIds), &parsedExclusionRulesWorkStatusIds); err != nil {
							return fmt.Errorf("parsing --exclusion-rules-work-status-ids JSON: %w", err)
						}
						nestedExclusionRules["workStatusIds"] = parsedExclusionRulesWorkStatusIds
					}
					if len(nestedExclusionRules) > 0 {
						body["exclusionRules"] = nestedExclusionRules
					}
				}
				if bodyIssueSources != "" {
					var parsedIssueSources any
					if err := json.Unmarshal([]byte(bodyIssueSources), &parsedIssueSources); err != nil {
						return fmt.Errorf("parsing --issue-sources JSON: %w", err)
					}
					body["issueSources"] = parsedIssueSources
				}
				if bodyLeadAccountId != "" {
					body["leadAccountId"] = bodyLeadAccountId
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPermissions != "" {
					var parsedPermissions any
					if err := json.Unmarshal([]byte(bodyPermissions), &parsedPermissions); err != nil {
						return fmt.Errorf("parsing --permissions JSON: %w", err)
					}
					body["permissions"] = parsedPermissions
				}
				{
					nestedScheduling := map[string]any{}
					if bodySchedulingDependencies != "" {
						nestedScheduling["dependencies"] = bodySchedulingDependencies
					}
					{
						nestedSchedulingEndDate := map[string]any{}
						if bodySchedulingEndDateDateCustomFieldId != 0 {
							nestedSchedulingEndDate["dateCustomFieldId"] = bodySchedulingEndDateDateCustomFieldId
						}
						if bodySchedulingEndDateType != "" {
							nestedSchedulingEndDate["type"] = bodySchedulingEndDateType
						}
						if len(nestedSchedulingEndDate) > 0 {
							nestedScheduling["endDate"] = nestedSchedulingEndDate
						}
					}
					if bodySchedulingEstimation != "" {
						nestedScheduling["estimation"] = bodySchedulingEstimation
					}
					if bodySchedulingInferredDates != "" {
						nestedScheduling["inferredDates"] = bodySchedulingInferredDates
					}
					{
						nestedSchedulingStartDate := map[string]any{}
						if bodySchedulingStartDateDateCustomFieldId != 0 {
							nestedSchedulingStartDate["dateCustomFieldId"] = bodySchedulingStartDateDateCustomFieldId
						}
						if bodySchedulingStartDateType != "" {
							nestedSchedulingStartDate["type"] = bodySchedulingStartDateType
						}
						if len(nestedSchedulingStartDate) > 0 {
							nestedScheduling["startDate"] = nestedSchedulingStartDate
						}
					}
					if len(nestedScheduling) > 0 {
						body["scheduling"] = nestedScheduling
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "plans", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "plans", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "plans", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "plans", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "plans", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "plans",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "plans", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "plans", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&flagUseGroupId, "use-group-id", false, "Whether to accept group IDs instead of group names. Group names are deprecated.")
	cmd.Flags().StringVar(&bodyCrossProjectReleases, "cross-project-releases", "", "The cross-project releases to include in the plan.")
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "The custom fields for the plan.")
	cmd.Flags().StringVar(&bodyExclusionRulesIssueIds, "exclusion-rules-issue-ids", "", "The IDs of the issues to exclude from the plan.")
	cmd.Flags().StringVar(&bodyExclusionRulesIssueTypeIds, "exclusion-rules-issue-type-ids", "", "The IDs of the issue types to exclude from the plan.")
	cmd.Flags().IntVar(&bodyExclusionRulesNumberOfDaysToShowCompletedIssues, "exclusion-rules-number-of-days-to-show-completed-issues", 0, "Issues completed this number of days ago will be excluded from the plan.")
	cmd.Flags().StringVar(&bodyExclusionRulesReleaseIds, "exclusion-rules-release-ids", "", "The IDs of the releases to exclude from the plan.")
	cmd.Flags().StringVar(&bodyExclusionRulesWorkStatusCategoryIds, "exclusion-rules-work-status-category-ids", "", "The IDs of the work status categories to exclude from the plan.")
	cmd.Flags().StringVar(&bodyExclusionRulesWorkStatusIds, "exclusion-rules-work-status-ids", "", "The IDs of the work statuses to exclude from the plan.")
	cmd.Flags().StringVar(&bodyIssueSources, "issue-sources", "", "The issue sources to include in the plan.")
	cmd.Flags().StringVar(&bodyLeadAccountId, "lead-account-id", "", "The account ID of the plan lead.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The plan name.")
	cmd.Flags().StringVar(&bodyPermissions, "permissions", "", "The permissions for the plan.")
	cmd.Flags().StringVar(&bodySchedulingDependencies, "scheduling-dependencies", "", "The dependencies for the plan. This must be 'Sequential' or 'Concurrent'.")
	cmd.Flags().IntVar(&bodySchedulingEndDateDateCustomFieldId, "scheduling-end-date-date-custom-field-id", 0, "A date custom field ID. This is required if the type is 'DateCustomField'.")
	cmd.Flags().StringVar(&bodySchedulingEndDateType, "scheduling-end-date-type", "", "The date field type. This must be 'DueDate', 'TargetStartDate', 'TargetEndDate' or 'DateCustomField'.")
	cmd.Flags().StringVar(&bodySchedulingEstimation, "scheduling-estimation", "", "The estimation unit for the plan. This must be 'StoryPoints', 'Days' or 'Hours'.")
	cmd.Flags().StringVar(&bodySchedulingInferredDates, "scheduling-inferred-dates", "", "The inferred dates for the plan. This must be 'None', 'SprintDates' or 'ReleaseDates'.")
	cmd.Flags().IntVar(&bodySchedulingStartDateDateCustomFieldId, "scheduling-start-date-date-custom-field-id", 0, "A date custom field ID. This is required if the type is 'DateCustomField'.")
	cmd.Flags().StringVar(&bodySchedulingStartDateType, "scheduling-start-date-type", "", "The date field type. This must be 'DueDate', 'TargetStartDate', 'TargetEndDate' or 'DateCustomField'.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
