// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPoliciesUpdatePolicyCmd(flags *rootFlags) *cobra.Command {
	var bodyDataAttributesName string
	var bodyDataAttributesResources string
	var bodyDataAttributesRule string
	var bodyDataAttributesStatus string
	var bodyDataAttributesType string
	var bodyDataId string
	var bodyDataType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-policy <orgId> <policyId>",
		Aliases:     []string{"update"},
		Short:       "Update a policy for an org",
		Example:     "  jira-pp-cli-pp-cli policies update-policy 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "policies.update-policy", "pp:method": "PUT", "pp:path": "https://api.atlassian.com/admin/v1/orgs/{orgId}/policies/{policyId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("data-attributes-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "data-attributes-type")
				}
				if !cmd.Flags().Changed("data-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "data-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://api.atlassian.com/admin/v1/orgs/{orgId}/policies/{policyId}"
			path = replacePathParam(path, "orgId", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("policyId is required\nUsage: %s <%s>", cmd.CommandPath(), "policyId"))
			}
			path = replacePathParam(path, "policyId", args[1])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedData := map[string]any{}
					{
						nestedDataAttributes := map[string]any{}
						if bodyDataAttributesName != "" {
							nestedDataAttributes["name"] = bodyDataAttributesName
						}
						if bodyDataAttributesResources != "" {
							var parsedDataAttributesResources any
							if err := json.Unmarshal([]byte(bodyDataAttributesResources), &parsedDataAttributesResources); err != nil {
								return fmt.Errorf("parsing --data-attributes-resources JSON: %w", err)
							}
							nestedDataAttributes["resources"] = parsedDataAttributesResources
						}
						if bodyDataAttributesRule != "" {
							var parsedDataAttributesRule any
							if err := json.Unmarshal([]byte(bodyDataAttributesRule), &parsedDataAttributesRule); err != nil {
								return fmt.Errorf("parsing --data-attributes-rule JSON: %w", err)
							}
							nestedDataAttributes["rule"] = parsedDataAttributesRule
						}
						if bodyDataAttributesStatus != "" {
							nestedDataAttributes["status"] = bodyDataAttributesStatus
						}
						if bodyDataAttributesType != "" {
							nestedDataAttributes["type"] = bodyDataAttributesType
						}
						if len(nestedDataAttributes) > 0 {
							nestedData["attributes"] = nestedDataAttributes
						}
					}
					if bodyDataId != "" {
						nestedData["id"] = bodyDataId
					}
					if bodyDataType != "" {
						nestedData["type"] = bodyDataType
					}
					if len(nestedData) > 0 {
						body["data"] = nestedData
					}
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "policies", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "policies", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "policies", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "policies", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "policies", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "policies",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "policies", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "policies", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDataAttributesName, "data-attributes-name", "", "Name of this Policy")
	cmd.Flags().StringVar(&bodyDataAttributesResources, "data-attributes-resources", "", "list of resources Policy is associated with")
	cmd.Flags().StringVar(&bodyDataAttributesRule, "data-attributes-rule", "", "Rule of the Policy")
	cmd.Flags().StringVar(&bodyDataAttributesStatus, "data-attributes-status", "", "Status of this Policy")
	cmd.Flags().StringVar(&bodyDataAttributesType, "data-attributes-type", "", "Type of this Policy")
	cmd.Flags().StringVar(&bodyDataId, "data-id", "", "Unique identifier of the Policy")
	cmd.Flags().StringVar(&bodyDataType, "data-type", "", "Type of this object")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
