// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPoliciesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "policies",
		Short:  "Get, create, update, and delete policies",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPoliciesCreatePolicyCmd(flags))
	cmd.AddCommand(newPoliciesDeletePolicyCmd(flags))
	cmd.AddCommand(newPoliciesGetCmd(flags))
	cmd.AddCommand(newPoliciesGetPolicyByIdCmd(flags))
	cmd.AddCommand(newPoliciesUpdatePolicyCmd(flags))
	cmd.AddCommand(newPoliciesResourcesCmd(flags))
	cmd.AddCommand(newPoliciesValidateCmd(flags))
	return cmd
}
