// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPriorityschemeUpdatePrioritySchemeCmd(flags *rootFlags) *cobra.Command {
	var bodyDefaultPriorityId int
	var bodyDescription string
	var bodyMappingsIn string
	var bodyMappingsOut string
	var bodyName string
	var bodyPrioritiesAddIds string
	var bodyPrioritiesRemoveIds string
	var bodyProjectsAddIds string
	var bodyProjectsRemoveIds string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-priority-scheme <schemeId>",
		Aliases:     []string{"update"},
		Short:       "Updates a priority scheme.",
		Example:     "  jira-pp-cli-pp-cli priorityscheme update-priority-scheme 42",
		Annotations: map[string]string{"pp:endpoint": "priorityscheme.update-priority-scheme", "pp:method": "PUT", "pp:path": "/rest/api/2/priorityscheme/{schemeId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("priorities-add-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "priorities-add-ids")
				}
				if !cmd.Flags().Changed("priorities-remove-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "priorities-remove-ids")
				}
				if !cmd.Flags().Changed("projects-add-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "projects-add-ids")
				}
				if !cmd.Flags().Changed("projects-remove-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "projects-remove-ids")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/priorityscheme/{schemeId}"
			path = replacePathParam(path, "schemeId", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDefaultPriorityId != 0 {
					body["defaultPriorityId"] = bodyDefaultPriorityId
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				{
					nestedMappings := map[string]any{}
					if bodyMappingsIn != "" {
						var parsedMappingsIn any
						if err := json.Unmarshal([]byte(bodyMappingsIn), &parsedMappingsIn); err != nil {
							return fmt.Errorf("parsing --mappings-in JSON: %w", err)
						}
						nestedMappings["in"] = parsedMappingsIn
					}
					if bodyMappingsOut != "" {
						var parsedMappingsOut any
						if err := json.Unmarshal([]byte(bodyMappingsOut), &parsedMappingsOut); err != nil {
							return fmt.Errorf("parsing --mappings-out JSON: %w", err)
						}
						nestedMappings["out"] = parsedMappingsOut
					}
					if len(nestedMappings) > 0 {
						body["mappings"] = nestedMappings
					}
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				{
					nestedPriorities := map[string]any{}
					{
						nestedPrioritiesAdd := map[string]any{}
						if bodyPrioritiesAddIds != "" {
							var parsedPrioritiesAddIds any
							if err := json.Unmarshal([]byte(bodyPrioritiesAddIds), &parsedPrioritiesAddIds); err != nil {
								return fmt.Errorf("parsing --priorities-add-ids JSON: %w", err)
							}
							nestedPrioritiesAdd["ids"] = parsedPrioritiesAddIds
						}
						if len(nestedPrioritiesAdd) > 0 {
							nestedPriorities["add"] = nestedPrioritiesAdd
						}
					}
					{
						nestedPrioritiesRemove := map[string]any{}
						if bodyPrioritiesRemoveIds != "" {
							var parsedPrioritiesRemoveIds any
							if err := json.Unmarshal([]byte(bodyPrioritiesRemoveIds), &parsedPrioritiesRemoveIds); err != nil {
								return fmt.Errorf("parsing --priorities-remove-ids JSON: %w", err)
							}
							nestedPrioritiesRemove["ids"] = parsedPrioritiesRemoveIds
						}
						if len(nestedPrioritiesRemove) > 0 {
							nestedPriorities["remove"] = nestedPrioritiesRemove
						}
					}
					if len(nestedPriorities) > 0 {
						body["priorities"] = nestedPriorities
					}
				}
				{
					nestedProjects := map[string]any{}
					{
						nestedProjectsAdd := map[string]any{}
						if bodyProjectsAddIds != "" {
							var parsedProjectsAddIds any
							if err := json.Unmarshal([]byte(bodyProjectsAddIds), &parsedProjectsAddIds); err != nil {
								return fmt.Errorf("parsing --projects-add-ids JSON: %w", err)
							}
							nestedProjectsAdd["ids"] = parsedProjectsAddIds
						}
						if len(nestedProjectsAdd) > 0 {
							nestedProjects["add"] = nestedProjectsAdd
						}
					}
					{
						nestedProjectsRemove := map[string]any{}
						if bodyProjectsRemoveIds != "" {
							var parsedProjectsRemoveIds any
							if err := json.Unmarshal([]byte(bodyProjectsRemoveIds), &parsedProjectsRemoveIds); err != nil {
								return fmt.Errorf("parsing --projects-remove-ids JSON: %w", err)
							}
							nestedProjectsRemove["ids"] = parsedProjectsRemoveIds
						}
						if len(nestedProjectsRemove) > 0 {
							nestedProjects["remove"] = nestedProjectsRemove
						}
					}
					if len(nestedProjects) > 0 {
						body["projects"] = nestedProjects
					}
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "priorityscheme", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "priorityscheme", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "priorityscheme", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "priorityscheme", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "priorityscheme", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "priorityscheme",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "priorityscheme", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "priorityscheme", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().IntVar(&bodyDefaultPriorityId, "default-priority-id", 0, "The default priority of the scheme.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description of the priority scheme.")
	cmd.Flags().StringVar(&bodyMappingsIn, "mappings-in", "", "The mapping of priorities for issues being migrated **into** this priority scheme.")
	cmd.Flags().StringVar(&bodyMappingsOut, "mappings-out", "", "The mapping of priorities for issues being migrated **out of** this priority scheme.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the priority scheme. Must be unique.")
	cmd.Flags().StringVar(&bodyPrioritiesAddIds, "priorities-add-ids", "", "Affected entity ids.")
	cmd.Flags().StringVar(&bodyPrioritiesRemoveIds, "priorities-remove-ids", "", "Affected entity ids.")
	cmd.Flags().StringVar(&bodyProjectsAddIds, "projects-add-ids", "", "Affected entity ids.")
	cmd.Flags().StringVar(&bodyProjectsRemoveIds, "projects-remove-ids", "", "Affected entity ids.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
