// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPriorityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "priority",
		Short:  "Get, search, create, update, and delete priority",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPriorityCreateCmd(flags))
	cmd.AddCommand(newPriorityDeleteCmd(flags))
	cmd.AddCommand(newPriorityGetCmd(flags))
	cmd.AddCommand(newPriorityGetPrioritiesCmd(flags))
	cmd.AddCommand(newPriorityMovePrioritiesCmd(flags))
	cmd.AddCommand(newPrioritySearchPrioritiesCmd(flags))
	cmd.AddCommand(newPrioritySetDefaultCmd(flags))
	cmd.AddCommand(newPriorityUpdateCmd(flags))
	return cmd
}
