// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectFeaturesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "features",
		Short: "Get and update features for project",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectFeaturesGetForProjectCmd(flags))
	cmd.AddCommand(newProjectFeaturesToggleForProjectCmd(flags))
	return cmd
}
