// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectDeleteCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Run delete operations for project",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectDeleteProjectAsynchronouslyCmd(flags))
	return cmd
}
