// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newProjectTemplateCreateProjectWithCustomTemplateCmd(flags *rootFlags) *cobra.Command {
	var bodyDetailsAccessLevel string
	var bodyDetailsAdditionalProperties string
	var bodyDetailsAssigneeType string
	var bodyDetailsAvatarId int
	var bodyDetailsCategoryId int
	var bodyDetailsDescription string
	var bodyDetailsEnableComponents bool
	var bodyDetailsKey string
	var bodyDetailsLanguage string
	var bodyDetailsLeadAccountId string
	var bodyDetailsName string
	var bodyDetailsUrl string
	var bodyTemplateBoardFeaturesBoardFeatures string
	var bodyTemplateBoardsBoards string
	var bodyTemplateFieldCustomFieldDefinitions string
	var bodyTemplateFieldFieldLayouts string
	var bodyTemplateFieldIssueLayouts string
	var bodyTemplateFieldScreenScheme string
	var bodyTemplateFieldScreens string
	var bodyTemplateIssueTypeIssueTypeHierarchy string
	var bodyTemplateIssueTypeIssueTypes string
	var bodyTemplateNotificationDescription string
	var bodyTemplateNotificationName string
	var bodyTemplateNotificationNotificationSchemeEvents string
	var bodyTemplateNotificationOnConflict string
	var bodyTemplatePermissionSchemeAddAddonRole bool
	var bodyTemplatePermissionSchemeDescription string
	var bodyTemplatePermissionSchemeGrants string
	var bodyTemplatePermissionSchemeName string
	var bodyTemplatePermissionSchemeOnConflict string
	var bodyTemplateProjectProjectTypeKey string
	var bodyTemplateRoleRoleToProjectActors string
	var bodyTemplateRoleRoles string
	var bodyTemplateScopeType string
	var bodyTemplateSecurityDescription string
	var bodyTemplateSecurityName string
	var bodyTemplateSecuritySecurityLevels string
	var bodyTemplateWorkflowStatuses string
	var bodyTemplateWorkflowWorkflows string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-project-with-custom-template",
		Aliases:     []string{"create"},
		Short:       "Creates a project based on a custom template provided in the request.",
		Example:     "  jira-pp-cli-pp-cli project-template create-project-with-custom-template",
		Annotations: map[string]string{"pp:endpoint": "project-template.create-project-with-custom-template", "pp:method": "POST", "pp:path": "/rest/api/2/project-template"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/project-template"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedDetails := map[string]any{}
					if bodyDetailsAccessLevel != "" {
						nestedDetails["accessLevel"] = bodyDetailsAccessLevel
					}
					if bodyDetailsAdditionalProperties != "" {
						var parsedDetailsAdditionalProperties any
						if err := json.Unmarshal([]byte(bodyDetailsAdditionalProperties), &parsedDetailsAdditionalProperties); err != nil {
							return fmt.Errorf("parsing --details-additional-properties JSON: %w", err)
						}
						nestedDetails["additionalProperties"] = parsedDetailsAdditionalProperties
					}
					if bodyDetailsAssigneeType != "" {
						nestedDetails["assigneeType"] = bodyDetailsAssigneeType
					}
					if bodyDetailsAvatarId != 0 {
						nestedDetails["avatarId"] = bodyDetailsAvatarId
					}
					if bodyDetailsCategoryId != 0 {
						nestedDetails["categoryId"] = bodyDetailsCategoryId
					}
					if bodyDetailsDescription != "" {
						nestedDetails["description"] = bodyDetailsDescription
					}
					if cmd.Flags().Changed("details-enable-components") {
						nestedDetails["enableComponents"] = bodyDetailsEnableComponents
					}
					if bodyDetailsKey != "" {
						nestedDetails["key"] = bodyDetailsKey
					}
					if bodyDetailsLanguage != "" {
						nestedDetails["language"] = bodyDetailsLanguage
					}
					if bodyDetailsLeadAccountId != "" {
						nestedDetails["leadAccountId"] = bodyDetailsLeadAccountId
					}
					if bodyDetailsName != "" {
						nestedDetails["name"] = bodyDetailsName
					}
					if bodyDetailsUrl != "" {
						nestedDetails["url"] = bodyDetailsUrl
					}
					if len(nestedDetails) > 0 {
						body["details"] = nestedDetails
					}
				}
				{
					nestedTemplate := map[string]any{}
					{
						nestedTemplateBoardFeatures := map[string]any{}
						if bodyTemplateBoardFeaturesBoardFeatures != "" {
							var parsedTemplateBoardFeaturesBoardFeatures any
							if err := json.Unmarshal([]byte(bodyTemplateBoardFeaturesBoardFeatures), &parsedTemplateBoardFeaturesBoardFeatures); err != nil {
								return fmt.Errorf("parsing --template-board-features-board-features JSON: %w", err)
							}
							nestedTemplateBoardFeatures["boardFeatures"] = parsedTemplateBoardFeaturesBoardFeatures
						}
						if len(nestedTemplateBoardFeatures) > 0 {
							nestedTemplate["boardFeatures"] = nestedTemplateBoardFeatures
						}
					}
					{
						nestedTemplateBoards := map[string]any{}
						if bodyTemplateBoardsBoards != "" {
							var parsedTemplateBoardsBoards any
							if err := json.Unmarshal([]byte(bodyTemplateBoardsBoards), &parsedTemplateBoardsBoards); err != nil {
								return fmt.Errorf("parsing --template-boards-boards JSON: %w", err)
							}
							nestedTemplateBoards["boards"] = parsedTemplateBoardsBoards
						}
						if len(nestedTemplateBoards) > 0 {
							nestedTemplate["boards"] = nestedTemplateBoards
						}
					}
					{
						nestedTemplateField := map[string]any{}
						if bodyTemplateFieldCustomFieldDefinitions != "" {
							var parsedTemplateFieldCustomFieldDefinitions any
							if err := json.Unmarshal([]byte(bodyTemplateFieldCustomFieldDefinitions), &parsedTemplateFieldCustomFieldDefinitions); err != nil {
								return fmt.Errorf("parsing --template-field-custom-field-definitions JSON: %w", err)
							}
							nestedTemplateField["customFieldDefinitions"] = parsedTemplateFieldCustomFieldDefinitions
						}
						if bodyTemplateFieldFieldLayouts != "" {
							var parsedTemplateFieldFieldLayouts any
							if err := json.Unmarshal([]byte(bodyTemplateFieldFieldLayouts), &parsedTemplateFieldFieldLayouts); err != nil {
								return fmt.Errorf("parsing --template-field-field-layouts JSON: %w", err)
							}
							nestedTemplateField["fieldLayouts"] = parsedTemplateFieldFieldLayouts
						}
						if bodyTemplateFieldIssueLayouts != "" {
							var parsedTemplateFieldIssueLayouts any
							if err := json.Unmarshal([]byte(bodyTemplateFieldIssueLayouts), &parsedTemplateFieldIssueLayouts); err != nil {
								return fmt.Errorf("parsing --template-field-issue-layouts JSON: %w", err)
							}
							nestedTemplateField["issueLayouts"] = parsedTemplateFieldIssueLayouts
						}
						if bodyTemplateFieldScreenScheme != "" {
							var parsedTemplateFieldScreenScheme any
							if err := json.Unmarshal([]byte(bodyTemplateFieldScreenScheme), &parsedTemplateFieldScreenScheme); err != nil {
								return fmt.Errorf("parsing --template-field-screen-scheme JSON: %w", err)
							}
							nestedTemplateField["screenScheme"] = parsedTemplateFieldScreenScheme
						}
						if bodyTemplateFieldScreens != "" {
							var parsedTemplateFieldScreens any
							if err := json.Unmarshal([]byte(bodyTemplateFieldScreens), &parsedTemplateFieldScreens); err != nil {
								return fmt.Errorf("parsing --template-field-screens JSON: %w", err)
							}
							nestedTemplateField["screens"] = parsedTemplateFieldScreens
						}
						if len(nestedTemplateField) > 0 {
							nestedTemplate["field"] = nestedTemplateField
						}
					}
					{
						nestedTemplateIssueType := map[string]any{}
						if bodyTemplateIssueTypeIssueTypeHierarchy != "" {
							var parsedTemplateIssueTypeIssueTypeHierarchy any
							if err := json.Unmarshal([]byte(bodyTemplateIssueTypeIssueTypeHierarchy), &parsedTemplateIssueTypeIssueTypeHierarchy); err != nil {
								return fmt.Errorf("parsing --template-issue-type-issue-type-hierarchy JSON: %w", err)
							}
							nestedTemplateIssueType["issueTypeHierarchy"] = parsedTemplateIssueTypeIssueTypeHierarchy
						}
						if bodyTemplateIssueTypeIssueTypes != "" {
							var parsedTemplateIssueTypeIssueTypes any
							if err := json.Unmarshal([]byte(bodyTemplateIssueTypeIssueTypes), &parsedTemplateIssueTypeIssueTypes); err != nil {
								return fmt.Errorf("parsing --template-issue-type-issue-types JSON: %w", err)
							}
							nestedTemplateIssueType["issueTypes"] = parsedTemplateIssueTypeIssueTypes
						}
						if len(nestedTemplateIssueType) > 0 {
							nestedTemplate["issueType"] = nestedTemplateIssueType
						}
					}
					{
						nestedTemplateNotification := map[string]any{}
						if bodyTemplateNotificationDescription != "" {
							nestedTemplateNotification["description"] = bodyTemplateNotificationDescription
						}
						if bodyTemplateNotificationName != "" {
							nestedTemplateNotification["name"] = bodyTemplateNotificationName
						}
						if bodyTemplateNotificationNotificationSchemeEvents != "" {
							var parsedTemplateNotificationNotificationSchemeEvents any
							if err := json.Unmarshal([]byte(bodyTemplateNotificationNotificationSchemeEvents), &parsedTemplateNotificationNotificationSchemeEvents); err != nil {
								return fmt.Errorf("parsing --template-notification-notification-scheme-events JSON: %w", err)
							}
							nestedTemplateNotification["notificationSchemeEvents"] = parsedTemplateNotificationNotificationSchemeEvents
						}
						if bodyTemplateNotificationOnConflict != "" {
							nestedTemplateNotification["onConflict"] = bodyTemplateNotificationOnConflict
						}
						if len(nestedTemplateNotification) > 0 {
							nestedTemplate["notification"] = nestedTemplateNotification
						}
					}
					{
						nestedTemplatePermissionScheme := map[string]any{}
						if cmd.Flags().Changed("template-permission-scheme-add-addon-role") {
							nestedTemplatePermissionScheme["addAddonRole"] = bodyTemplatePermissionSchemeAddAddonRole
						}
						if bodyTemplatePermissionSchemeDescription != "" {
							nestedTemplatePermissionScheme["description"] = bodyTemplatePermissionSchemeDescription
						}
						if bodyTemplatePermissionSchemeGrants != "" {
							var parsedTemplatePermissionSchemeGrants any
							if err := json.Unmarshal([]byte(bodyTemplatePermissionSchemeGrants), &parsedTemplatePermissionSchemeGrants); err != nil {
								return fmt.Errorf("parsing --template-permission-scheme-grants JSON: %w", err)
							}
							nestedTemplatePermissionScheme["grants"] = parsedTemplatePermissionSchemeGrants
						}
						if bodyTemplatePermissionSchemeName != "" {
							nestedTemplatePermissionScheme["name"] = bodyTemplatePermissionSchemeName
						}
						if bodyTemplatePermissionSchemeOnConflict != "" {
							nestedTemplatePermissionScheme["onConflict"] = bodyTemplatePermissionSchemeOnConflict
						}
						if len(nestedTemplatePermissionScheme) > 0 {
							nestedTemplate["permissionScheme"] = nestedTemplatePermissionScheme
						}
					}
					{
						nestedTemplateProject := map[string]any{}
						if bodyTemplateProjectProjectTypeKey != "" {
							nestedTemplateProject["projectTypeKey"] = bodyTemplateProjectProjectTypeKey
						}
						if len(nestedTemplateProject) > 0 {
							nestedTemplate["project"] = nestedTemplateProject
						}
					}
					{
						nestedTemplateRole := map[string]any{}
						if bodyTemplateRoleRoleToProjectActors != "" {
							var parsedTemplateRoleRoleToProjectActors any
							if err := json.Unmarshal([]byte(bodyTemplateRoleRoleToProjectActors), &parsedTemplateRoleRoleToProjectActors); err != nil {
								return fmt.Errorf("parsing --template-role-role-to-project-actors JSON: %w", err)
							}
							nestedTemplateRole["roleToProjectActors"] = parsedTemplateRoleRoleToProjectActors
						}
						if bodyTemplateRoleRoles != "" {
							var parsedTemplateRoleRoles any
							if err := json.Unmarshal([]byte(bodyTemplateRoleRoles), &parsedTemplateRoleRoles); err != nil {
								return fmt.Errorf("parsing --template-role-roles JSON: %w", err)
							}
							nestedTemplateRole["roles"] = parsedTemplateRoleRoles
						}
						if len(nestedTemplateRole) > 0 {
							nestedTemplate["role"] = nestedTemplateRole
						}
					}
					{
						nestedTemplateScope := map[string]any{}
						if bodyTemplateScopeType != "" {
							nestedTemplateScope["type"] = bodyTemplateScopeType
						}
						if len(nestedTemplateScope) > 0 {
							nestedTemplate["scope"] = nestedTemplateScope
						}
					}
					{
						nestedTemplateSecurity := map[string]any{}
						if bodyTemplateSecurityDescription != "" {
							nestedTemplateSecurity["description"] = bodyTemplateSecurityDescription
						}
						if bodyTemplateSecurityName != "" {
							nestedTemplateSecurity["name"] = bodyTemplateSecurityName
						}
						if bodyTemplateSecuritySecurityLevels != "" {
							var parsedTemplateSecuritySecurityLevels any
							if err := json.Unmarshal([]byte(bodyTemplateSecuritySecurityLevels), &parsedTemplateSecuritySecurityLevels); err != nil {
								return fmt.Errorf("parsing --template-security-security-levels JSON: %w", err)
							}
							nestedTemplateSecurity["securityLevels"] = parsedTemplateSecuritySecurityLevels
						}
						if len(nestedTemplateSecurity) > 0 {
							nestedTemplate["security"] = nestedTemplateSecurity
						}
					}
					{
						nestedTemplateWorkflow := map[string]any{}
						if bodyTemplateWorkflowStatuses != "" {
							var parsedTemplateWorkflowStatuses any
							if err := json.Unmarshal([]byte(bodyTemplateWorkflowStatuses), &parsedTemplateWorkflowStatuses); err != nil {
								return fmt.Errorf("parsing --template-workflow-statuses JSON: %w", err)
							}
							nestedTemplateWorkflow["statuses"] = parsedTemplateWorkflowStatuses
						}
						if bodyTemplateWorkflowWorkflows != "" {
							var parsedTemplateWorkflowWorkflows any
							if err := json.Unmarshal([]byte(bodyTemplateWorkflowWorkflows), &parsedTemplateWorkflowWorkflows); err != nil {
								return fmt.Errorf("parsing --template-workflow-workflows JSON: %w", err)
							}
							nestedTemplateWorkflow["workflows"] = parsedTemplateWorkflowWorkflows
						}
						if len(nestedTemplateWorkflow) > 0 {
							nestedTemplate["workflow"] = nestedTemplateWorkflow
						}
					}
					if len(nestedTemplate) > 0 {
						body["template"] = nestedTemplate
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "project-template", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "project-template", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "project-template", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "project-template", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "project-template", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "project-template",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "project-template", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "project-template", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDetailsAccessLevel, "details-access-level", "", "The access level of the project. Only used by team-managed project")
	cmd.Flags().StringVar(&bodyDetailsAdditionalProperties, "details-additional-properties", "", "Additional properties of the project")
	cmd.Flags().StringVar(&bodyDetailsAssigneeType, "details-assignee-type", "", "The default assignee when creating issues in the project")
	cmd.Flags().IntVar(&bodyDetailsAvatarId, "details-avatar-id", 0, "The ID of the project's avatar.")
	cmd.Flags().IntVar(&bodyDetailsCategoryId, "details-category-id", 0, "The ID of the project's category.")
	cmd.Flags().StringVar(&bodyDetailsDescription, "details-description", "", "Brief description of the project")
	cmd.Flags().BoolVar(&bodyDetailsEnableComponents, "details-enable-components", false, "Whether components are enabled for the project. Only used by company-managed project")
	cmd.Flags().StringVar(&bodyDetailsKey, "details-key", "", "Project keys must be unique and start with an uppercase letter followed by one or more uppercase alphanumeric")
	cmd.Flags().StringVar(&bodyDetailsLanguage, "details-language", "", "The default language for the project")
	cmd.Flags().StringVar(&bodyDetailsLeadAccountId, "details-lead-account-id", "", "The account ID of the project lead. Either `lead` or `leadAccountId` must be set when creating a project.")
	cmd.Flags().StringVar(&bodyDetailsName, "details-name", "", "Name of the project")
	cmd.Flags().StringVar(&bodyDetailsUrl, "details-url", "", "A link to information about this project, such as project documentation")
	cmd.Flags().StringVar(&bodyTemplateBoardFeaturesBoardFeatures, "template-board-features-board-features", "", "A map of board PCRIs to the list of features to enable on each board.")
	cmd.Flags().StringVar(&bodyTemplateBoardsBoards, "template-boards-boards", "", "The boards to be associated with the project.")
	cmd.Flags().StringVar(&bodyTemplateFieldCustomFieldDefinitions, "template-field-custom-field-definitions", "", "The custom field definitions. See https://developer.atlassian.")
	cmd.Flags().StringVar(&bodyTemplateFieldFieldLayouts, "template-field-field-layouts", "", "The field layouts configuration.")
	cmd.Flags().StringVar(&bodyTemplateFieldIssueLayouts, "template-field-issue-layouts", "", "The issue layouts configuration")
	cmd.Flags().StringVar(&bodyTemplateFieldScreenScheme, "template-field-screen-scheme", "", "The screen schemes See https://developer.atlassian.")
	cmd.Flags().StringVar(&bodyTemplateFieldScreens, "template-field-screens", "", "The screens. See https://developer.atlassian.")
	cmd.Flags().StringVar(&bodyTemplateIssueTypeIssueTypeHierarchy, "template-issue-type-issue-type-hierarchy", "", "Defines the issue type hierarhy to be created and used during this project creation.")
	cmd.Flags().StringVar(&bodyTemplateIssueTypeIssueTypes, "template-issue-type-issue-types", "", "Only needed if you want to create issue types, you can otherwise use the ids of issue types in the scheme configuration")
	cmd.Flags().StringVar(&bodyTemplateNotificationDescription, "template-notification-description", "", "The description of the notification scheme")
	cmd.Flags().StringVar(&bodyTemplateNotificationName, "template-notification-name", "", "The name of the notification scheme")
	cmd.Flags().StringVar(&bodyTemplateNotificationNotificationSchemeEvents, "template-notification-notification-scheme-events", "", "The events and notifications for the notification scheme")
	cmd.Flags().StringVar(&bodyTemplateNotificationOnConflict, "template-notification-on-conflict", "", "The strategy to use when there is a conflict with an existing entity")
	cmd.Flags().BoolVar(&bodyTemplatePermissionSchemeAddAddonRole, "template-permission-scheme-add-addon-role", false, "Configuration to generate addon role. Default is false if null. Only applies to GLOBAL-scoped permission scheme")
	cmd.Flags().StringVar(&bodyTemplatePermissionSchemeDescription, "template-permission-scheme-description", "", "The description of the permission scheme")
	cmd.Flags().StringVar(&bodyTemplatePermissionSchemeGrants, "template-permission-scheme-grants", "", "List of permission grants")
	cmd.Flags().StringVar(&bodyTemplatePermissionSchemeName, "template-permission-scheme-name", "", "The name of the permission scheme")
	cmd.Flags().StringVar(&bodyTemplatePermissionSchemeOnConflict, "template-permission-scheme-on-conflict", "", "The strategy to use when there is a conflict with an existing permission scheme.")
	cmd.Flags().StringVar(&bodyTemplateProjectProjectTypeKey, "template-project-project-type-key", "", "The [project type](https://confluence.atlassian.")
	cmd.Flags().StringVar(&bodyTemplateRoleRoleToProjectActors, "template-role-role-to-project-actors", "", "A map of role PCRI (can be ID or REF) to a list of user or group PCRI IDs to associate with the role and project.")
	cmd.Flags().StringVar(&bodyTemplateRoleRoles, "template-role-roles", "", "The list of roles to create.")
	cmd.Flags().StringVar(&bodyTemplateScopeType, "template-scope-type", "", "The type of the scope. Use `GLOBAL` or empty for company-managed project, and `PROJECT` for team-managed project")
	cmd.Flags().StringVar(&bodyTemplateSecurityDescription, "template-security-description", "", "The description of the security scheme")
	cmd.Flags().StringVar(&bodyTemplateSecurityName, "template-security-name", "", "The name of the security scheme")
	cmd.Flags().StringVar(&bodyTemplateSecuritySecurityLevels, "template-security-security-levels", "", "The security levels for the security scheme")
	cmd.Flags().StringVar(&bodyTemplateWorkflowStatuses, "template-workflow-statuses", "", "The statuses for the workflow")
	cmd.Flags().StringVar(&bodyTemplateWorkflowWorkflows, "template-workflow-workflows", "", "The transitions for the workflow")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
