// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectCategoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "project-category",
		Short:  "Get, create, update, and remove project category",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectCategoryCreateCmd(flags))
	cmd.AddCommand(newProjectCategoryGetAllProjectCategoriesCmd(flags))
	cmd.AddCommand(newProjectCategoryGetByIdCmd(flags))
	cmd.AddCommand(newProjectCategoryRemoveCmd(flags))
	cmd.AddCommand(newProjectCategoryUpdateCmd(flags))
	return cmd
}
