// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCommentPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagExpand string
	var bodyIds string

	cmd := &cobra.Command{
		Use:         "comment",
		Short:       "Returns a [paginated](#pagination) list of comments specified by a list of comment IDs.",
		Long:        "Returns a [paginated](#pagination) list of comments specified by a list of comment IDs.",
		Example:     "  jira-pp-cli-pp-cli comment",
		Annotations: map[string]string{"pp:endpoint": "comment.get-by-ids", "pp:method": "POST", "pp:path": "/rest/api/2/comment/list"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("ids") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "ids")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/comment/list"
			params := map[string]string{}
			if flagExpand != "" {
				params["expand"] = fmt.Sprintf("%v", flagExpand)
			}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyIds != "" {
				var parsedIds any
				if err := json.Unmarshal([]byte(bodyIds), &parsedIds); err != nil {
					return fmt.Errorf("parsing --ids JSON: %w", err)
				}
				body["ids"] = parsedIds
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "comment", data, "")
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagExpand, "expand", "", "Use [expand](#expansion) to include additional information about comments in the response.")
	cmd.Flags().StringVar(&bodyIds, "ids", "", "The list of comment IDs. A maximum of 1000 IDs can be specified.")

	// Wire sibling endpoints and sub-resources as subcommands
	{
		sub := newCommentPropertiesCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}

	return cmd
}
