// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAtlassianAccessGroupsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCursor string
	var bodyExpand string
	var bodyGroupIds string
	var bodyGroupNamesContains string
	var bodyGroupNamesEq string
	var bodyLimit int

	cmd := &cobra.Command{
		Use:         "atlassian-access-groups <orgId>",
		Short:       "**This API is deprecated and will no longer work after June 30, 2026.",
		Long:        "**This API is deprecated and will no longer work after June 30, 2026.",
		Example:     "  jira-pp-cli-pp-cli atlassian-access-groups 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "atlassian-access-groups.search", "pp:method": "POST", "pp:path": "https://api.atlassian.com/admin/v1/orgs/{orgId}/groups/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://api.atlassian.com/admin/v1/orgs/{orgId}/groups/search"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "orgId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "orgId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("orgId is required\nUsage: %s <%s>", cmd.CommandPath(), "orgId"))
			}
			path = replacePathParam(path, "orgId", args[0])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyExpand != "" {
				var parsedExpand any
				if err := json.Unmarshal([]byte(bodyExpand), &parsedExpand); err != nil {
					return fmt.Errorf("parsing --expand JSON: %w", err)
				}
				body["expand"] = parsedExpand
			}
			if bodyGroupIds != "" {
				var parsedGroupIds any
				if err := json.Unmarshal([]byte(bodyGroupIds), &parsedGroupIds); err != nil {
					return fmt.Errorf("parsing --group-ids JSON: %w", err)
				}
				body["groupIds"] = parsedGroupIds
			}
			{
				nestedGroupNames := map[string]any{}
				if bodyGroupNamesContains != "" {
					nestedGroupNames["contains"] = bodyGroupNamesContains
				}
				if bodyGroupNamesEq != "" {
					var parsedGroupNamesEq any
					if err := json.Unmarshal([]byte(bodyGroupNamesEq), &parsedGroupNamesEq); err != nil {
						return fmt.Errorf("parsing --group-names-eq JSON: %w", err)
					}
					nestedGroupNames["eq"] = parsedGroupNamesEq
				}
				if len(nestedGroupNames) > 0 {
					body["groupNames"] = nestedGroupNames
				}
			}
			if bodyLimit != 0 {
				body["limit"] = bodyLimit
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "Cursor specifying the starting point for page result retrieval.")
	cmd.Flags().StringVar(&bodyExpand, "expand", "", "Indicates the user information fields to include in the response.")
	cmd.Flags().StringVar(&bodyGroupIds, "group-ids", "", "Unique ID that serves as reference to the group.")
	cmd.Flags().StringVar(&bodyGroupNamesContains, "group-names-contains", "", "Partial group name filter")
	cmd.Flags().StringVar(&bodyGroupNamesEq, "group-names-eq", "", "The list of group names to filter by")
	cmd.Flags().IntVar(&bodyLimit, "limit", 0, "The number of items to return. Default = max = 1000")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
