// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDirectoriesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagAccountId string
	var flagDirectoryIds string
	var flagSearchTerm string
	var flagCursor string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "directories <orgId>",
		Short:       "Returns a page of directories in an organization that match the supplied parameters. #### Scopes **[OAuth 2.",
		Long:        "Returns a page of directories in an organization that match the supplied parameters. #### Scopes **[OAuth 2.",
		Example:     "  jira-pp-cli-pp-cli directories 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "directories.get-for-org", "pp:method": "GET", "pp:path": "https://api.atlassian.com/admin/v2/orgs/{orgId}/directories", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://api.atlassian.com/admin/v2/orgs/{orgId}/directories"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "orgId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "orgId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("orgId is required\nUsage: %s <%s>", cmd.CommandPath(), "orgId"))
			}
			path = replacePathParam(path, "orgId", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "directories", path, map[string]string{
				"accountId":    fmt.Sprintf("%v", flagAccountId),
				"directoryIds": fmt.Sprintf("%v", flagDirectoryIds),
				"searchTerm":   fmt.Sprintf("%v", flagSearchTerm),
				"cursor":       fmt.Sprintf("%v", flagCursor),
				"limit":        fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAccountId, "account-id", "", "Filters the results to only the directories where the specified user is a member.")
	cmd.Flags().StringVar(&flagDirectoryIds, "directory-ids", "", "A list of directory IDs. The requestor must have permissions to administer resources linked to these directories.")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "A search term to search the `name` field.")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Sets the cursor position to retrieve the next set of results.")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "The desired number of results for the search request.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands
	{
		sub := newDirectoriesGroupsCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}
	{
		sub := newDirectoriesUsersCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}

	return cmd
}
