// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScreenschemeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "screenscheme",
		Short:  "Get, create, update, and delete screenscheme",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newScreenschemeCreateScreenSchemeCmd(flags))
	cmd.AddCommand(newScreenschemeDeleteScreenSchemeCmd(flags))
	cmd.AddCommand(newScreenschemeGetScreenSchemesCmd(flags))
	cmd.AddCommand(newScreenschemeUpdateScreenSchemeCmd(flags))
	return cmd
}
