// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newScreensGetBulkTabsCmd(flags *rootFlags) *cobra.Command {
	var flagScreenId string
	var flagTabId string
	var flagStartAt int
	var flagMaxResult int

	cmd := &cobra.Command{
		Use:         "get-bulk-tabs",
		Short:       "Returns the list of tabs for a bulk of screens.",
		Example:     "  jira-pp-cli-pp-cli screens get-bulk-tabs",
		Annotations: map[string]string{"pp:endpoint": "screens.get-bulk-tabs", "pp:method": "GET", "pp:path": "/rest/api/2/screens/tabs", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/screens/tabs"
			params := map[string]string{}
			if flagScreenId != "" {
				params["screenId"] = fmt.Sprintf("%v", flagScreenId)
			}
			if flagTabId != "" {
				params["tabId"] = fmt.Sprintf("%v", flagTabId)
			}
			if flagStartAt != 0 {
				params["startAt"] = fmt.Sprintf("%v", flagStartAt)
			}
			if flagMaxResult != 0 {
				params["maxResult"] = fmt.Sprintf("%v", flagMaxResult)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "screens", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagScreenId, "screen-id", "", "The list of screen IDs. To include multiple screen IDs, provide an ampersand-separated list.")
	cmd.Flags().StringVar(&flagTabId, "tab-id", "", "The list of tab IDs. To include multiple tab IDs, provide an ampersand-separated list.")
	cmd.Flags().IntVar(&flagStartAt, "start-at", 0, "The index of the first item to return in a page of results (page offset).")
	cmd.Flags().IntVar(&flagMaxResult, "max-result", 100, "The maximum number of items to return per page. The maximum number is 100,")

	return cmd
}
