// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSecurityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "security",
		Short:  "Get, delete, and submit security",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSecurityDeleteLinkedWorkspacesCmd(flags))
	cmd.AddCommand(newSecurityDeleteVulnerabilitiesByPropertyCmd(flags))
	cmd.AddCommand(newSecurityDeleteVulnerabilityByIdCmd(flags))
	cmd.AddCommand(newSecurityGetLinkedWorkspaceByIdCmd(flags))
	cmd.AddCommand(newSecurityGetLinkedWorkspacesCmd(flags))
	cmd.AddCommand(newSecurityGetVulnerabilityByIdCmd(flags))
	cmd.AddCommand(newSecuritySubmitVulnerabilitiesCmd(flags))
	cmd.AddCommand(newSecuritySubmitWorkspacesCmd(flags))
	return cmd
}
