// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newServicedeskapiCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "servicedeskapi",
		Short:  "Get, create, add, update, delete, and remove servicedeskapi",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newServicedeskapiAddCustomersCmd(flags))
	cmd.AddCommand(newServicedeskapiAddOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiAddRequestParticipantsCmd(flags))
	cmd.AddCommand(newServicedeskapiAddUsersToOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiAnswerApprovalCmd(flags))
	cmd.AddCommand(newServicedeskapiAttachTemporaryFileCmd(flags))
	cmd.AddCommand(newServicedeskapiCheckRequestTypePermissionsCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateCommentWithAttachmentCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateCustomerCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateCustomerRequestCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateRequestCommentCmd(flags))
	cmd.AddCommand(newServicedeskapiCreateRequestTypeCmd(flags))
	cmd.AddCommand(newServicedeskapiDeleteFeedbackCmd(flags))
	cmd.AddCommand(newServicedeskapiDeleteOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiDeletePropertyCmd(flags))
	cmd.AddCommand(newServicedeskapiDeletePropertyServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiDeleteRequestTypeCmd(flags))
	cmd.AddCommand(newServicedeskapiGetAllRequestTypesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetApprovalByIdCmd(flags))
	cmd.AddCommand(newServicedeskapiGetApprovalsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetArticlesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetArticlesServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiGetAssetsWorkspacesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetAttachmentContentCmd(flags))
	cmd.AddCommand(newServicedeskapiGetAttachmentThumbnailCmd(flags))
	cmd.AddCommand(newServicedeskapiGetAttachmentsForRequestCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCommentAttachmentsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCustomerRequestByIdOrKeyCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCustomerRequestStatusCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCustomerRequestsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCustomerTransitionsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetCustomersCmd(flags))
	cmd.AddCommand(newServicedeskapiGetFeedbackCmd(flags))
	cmd.AddCommand(newServicedeskapiGetInfoCmd(flags))
	cmd.AddCommand(newServicedeskapiGetInsightWorkspacesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetIssuesInQueueCmd(flags))
	cmd.AddCommand(newServicedeskapiGetOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiGetOrganizationsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetOrganizationsServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiGetPropertiesKeysCmd(flags))
	cmd.AddCommand(newServicedeskapiGetPropertiesKeysServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiGetPropertyCmd(flags))
	cmd.AddCommand(newServicedeskapiGetPropertyServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiGetQueueCmd(flags))
	cmd.AddCommand(newServicedeskapiGetQueuesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestCommentByIdCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestCommentsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestParticipantsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestTypeByIdCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestTypeFieldsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestTypeGroupsCmd(flags))
	cmd.AddCommand(newServicedeskapiGetRequestTypesCmd(flags))
	cmd.AddCommand(newServicedeskapiGetServiceDeskByIdCmd(flags))
	cmd.AddCommand(newServicedeskapiGetServiceDesksCmd(flags))
	cmd.AddCommand(newServicedeskapiGetSlaInformationCmd(flags))
	cmd.AddCommand(newServicedeskapiGetSlaInformationByIdCmd(flags))
	cmd.AddCommand(newServicedeskapiGetSubscriptionStatusCmd(flags))
	cmd.AddCommand(newServicedeskapiGetUsersInOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiInviteCustomerCmd(flags))
	cmd.AddCommand(newServicedeskapiPerformCustomerTransitionCmd(flags))
	cmd.AddCommand(newServicedeskapiPostFeedbackCmd(flags))
	cmd.AddCommand(newServicedeskapiRemoveCustomersCmd(flags))
	cmd.AddCommand(newServicedeskapiRemoveOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiRemoveRequestParticipantsCmd(flags))
	cmd.AddCommand(newServicedeskapiRemoveUsersFromOrganizationCmd(flags))
	cmd.AddCommand(newServicedeskapiRevokePortalOnlyAccessForUserCmd(flags))
	cmd.AddCommand(newServicedeskapiSetPropertyCmd(flags))
	cmd.AddCommand(newServicedeskapiSetPropertyServicedeskCmd(flags))
	cmd.AddCommand(newServicedeskapiSubscribeCmd(flags))
	cmd.AddCommand(newServicedeskapiUnsubscribeCmd(flags))
	return cmd
}
