// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newServicedeskapiGetArticlesCmd(flags *rootFlags) *cobra.Command {
	var flagQuery string
	var flagHighlight bool
	var flagStart int
	var flagLimit int
	var flagCursor string
	var flagPrev bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-articles",
		Short:       "Returns articles which match the given query string across all service desks.",
		Example:     "  jira-pp-cli-pp-cli servicedeskapi get-articles --query example-value --highlight true",
		Annotations: map[string]string{"pp:endpoint": "servicedeskapi.get-articles", "pp:method": "GET", "pp:path": "/rest/servicedeskapi/knowledgebase/article", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("query") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "query")
			}
			if !cmd.Flags().Changed("highlight") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "highlight")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/servicedeskapi/knowledgebase/article"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "servicedeskapi", path, map[string]string{
				"query":     fmt.Sprintf("%v", flagQuery),
				"highlight": fmt.Sprintf("%v", flagHighlight),
				"start":     fmt.Sprintf("%v", flagStart),
				"limit":     fmt.Sprintf("%v", flagLimit),
				"cursor":    fmt.Sprintf("%v", flagCursor),
				"prev":      fmt.Sprintf("%v", flagPrev),
			}, nil, flagAll, "cursor", "cursor", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagQuery, "query", "", "The string used to filter the articles (required).")
	cmd.Flags().BoolVar(&flagHighlight, "highlight", false, "If set to true matching query term in the title and excerpt will be highlighted using the `@@@hl@@@term@@@endhl@@@`")
	cmd.Flags().IntVar(&flagStart, "start", 0, "(Deprecated) The starting index of the returned objects. Base index: 0.")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "The maximum number of items to return per page. Default: 50.")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Pointer to a set of search results, returned as part of the next or prev URL from the previous search call.")
	cmd.Flags().BoolVar(&flagPrev, "prev", false, "Should navigate to the previous page. Defaulted to false. Set to true as part of prev URL from the previous search call.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
