// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newServicedeskapiGetCustomerRequestsCmd(flags *rootFlags) *cobra.Command {
	var flagSearchTerm string
	var flagRequestOwnership string
	var flagRequestStatus string
	var flagApprovalStatus string
	var flagOrganizationId string
	var flagServiceDeskId string
	var flagRequestTypeId string
	var flagExpand string
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-customer-requests",
		Short:       "This method returns all customer requests for the user executing the query.",
		Example:     "  jira-pp-cli-pp-cli servicedeskapi get-customer-requests",
		Annotations: map[string]string{"pp:endpoint": "servicedeskapi.get-customer-requests", "pp:method": "GET", "pp:path": "/rest/servicedeskapi/request", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/servicedeskapi/request"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "servicedeskapi", path, map[string]string{
				"searchTerm":       fmt.Sprintf("%v", flagSearchTerm),
				"requestOwnership": fmt.Sprintf("%v", flagRequestOwnership),
				"requestStatus":    fmt.Sprintf("%v", flagRequestStatus),
				"approvalStatus":   fmt.Sprintf("%v", flagApprovalStatus),
				"organizationId":   fmt.Sprintf("%v", flagOrganizationId),
				"serviceDeskId":    fmt.Sprintf("%v", flagServiceDeskId),
				"requestTypeId":    fmt.Sprintf("%v", flagRequestTypeId),
				"expand":           fmt.Sprintf("%v", flagExpand),
				"start":            fmt.Sprintf("%v", flagStart),
				"limit":            fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "", "offset", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "Filters customer requests where the request summary matches the `searchTerm`. [Wildcards](https://confluence.atlassian.")
	cmd.Flags().StringVar(&flagRequestOwnership, "request-ownership", "", "Filters customer requests using the following values")
	cmd.Flags().StringVar(&flagRequestStatus, "request-status", "", "Filters customer requests where the request is closed, open, or either of the two where")
	cmd.Flags().StringVar(&flagApprovalStatus, "approval-status", "", "Filters results to customer requests based on their approval status")
	cmd.Flags().StringVar(&flagOrganizationId, "organization-id", "", "Filters customer requests that belong to a specific organization (note that the user must be a member of that")
	cmd.Flags().StringVar(&flagServiceDeskId, "service-desk-id", "", "Filters customer requests by service desk.")
	cmd.Flags().StringVar(&flagRequestTypeId, "request-type-id", "", "Filters customer requests by request type.")
	cmd.Flags().StringVar(&flagExpand, "expand", "", "A multi-value parameter indicating which properties of the customer request to expand, where")
	cmd.Flags().IntVar(&flagStart, "start", 0, "The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details.")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
