// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSoftwareCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "software",
		Short:  "Manage software command groups",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSoftwareGetApproximateIssueCountForBacklogCmd(flags))
	cmd.AddCommand(newSoftwareGetApproximateIssueCountForBoardCmd(flags))
	cmd.AddCommand(newSoftwareGetBoardIssuesForEpicJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetBoardIssuesForSprintJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesForBacklogJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesForBoardJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesForEpicJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesForSprintJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesWithoutEpicForBoardJsisCmd(flags))
	cmd.AddCommand(newSoftwareGetIssuesWithoutEpicJsisCmd(flags))
	return cmd
}
