// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newUserCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyApplicationKeys string
	var bodyDisplayName string
	var bodyEmailAddress string
	var bodyKey string
	var bodyName string
	var bodyPassword string
	var bodyProducts string
	var bodySelf string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a user. This resource is retained for legacy compatibility.",
		Example:     "  jira-pp-cli-pp-cli user create --email-address 123 Test St, Anytown, ST 12345",
		Annotations: map[string]string{"pp:endpoint": "user.create", "pp:method": "POST", "pp:path": "/rest/api/2/user"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("email-address") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "email-address")
				}
				if !cmd.Flags().Changed("products") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "products")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rest/api/2/user"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyApplicationKeys != "" {
					var parsedApplicationKeys any
					if err := json.Unmarshal([]byte(bodyApplicationKeys), &parsedApplicationKeys); err != nil {
						return fmt.Errorf("parsing --application-keys JSON: %w", err)
					}
					body["applicationKeys"] = parsedApplicationKeys
				}
				if bodyDisplayName != "" {
					body["displayName"] = bodyDisplayName
				}
				if bodyEmailAddress != "" {
					body["emailAddress"] = bodyEmailAddress
				}
				if bodyKey != "" {
					body["key"] = bodyKey
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPassword != "" {
					body["password"] = bodyPassword
				}
				if bodyProducts != "" {
					var parsedProducts any
					if err := json.Unmarshal([]byte(bodyProducts), &parsedProducts); err != nil {
						return fmt.Errorf("parsing --products JSON: %w", err)
					}
					body["products"] = parsedProducts
				}
				if bodySelf != "" {
					body["self"] = bodySelf
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "user", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "user", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "user", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "user", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "user", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "user",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "user", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "user", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyApplicationKeys, "application-keys", "", "Deprecated, do not use.")
	cmd.Flags().StringVar(&bodyDisplayName, "display-name", "", "This property is no longer available. If the user has an Atlassian account, their display name is not changed.")
	cmd.Flags().StringVar(&bodyEmailAddress, "email-address", "", "The email address for the user.")
	cmd.Flags().StringVar(&bodyKey, "key", "", "This property is no longer available. See the [migration guide](https://developer.atlassian.")
	cmd.Flags().StringVar(&bodyName, "name", "", "This property is no longer available. See the [migration guide](https://developer.atlassian.")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "This property is no longer available. If the user has an Atlassian account, their password is not changed.")
	cmd.Flags().StringVar(&bodyProducts, "products", "", "Products the new user has access to.")
	cmd.Flags().StringVar(&bodySelf, "self", "", "The URL of the user.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
