// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "users",
		Short:  "This resource represent users. Use it to: * get, get a list of, create, and delete users.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersGetAllCmd(flags))
	cmd.AddCommand(newUsersGetAllDefaultCmd(flags))
	return cmd
}
