// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVendorsReportingCreateCmd(flags *rootFlags) *cobra.Command {
	var flagAddon string
	var flagStartDate string
	var flagEndDate string
	var flagText string
	var flagTier string
	var flagDateType string
	var flagLicenseType string
	var flagPartnerType string
	var flagHosting string
	var flagCloudComplianceBoundaries string
	var flagAppEdition string
	var flagStatus string
	var flagWithAttribution bool
	var flagWithDataInsights bool
	var flagIncludeAtlassianLicenses bool
	var flagLastUpdated string
	var flagShowLifeTimeFreeLicenses bool
	var flagLicenseLevel string
	var flagShowLicensesHistory bool
	var flagSortBy string
	var flagOrder string
	var flagAccept string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <vendorId>",
		Short:       "Initiate a POST request to export all licenses that match the specified filters for the vendor's apps.",
		Example:     "  jira-pp-cli-pp-cli vendors reporting create 42",
		Annotations: map[string]string{"pp:endpoint": "reporting.create", "pp:method": "POST", "pp:path": "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/licenses/async/export"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("date-type") {
				allowedDateType := []string{"end", "start"}
				validDateType := false
				for _, v := range allowedDateType {
					if flagDateType == v {
						validDateType = true
						break
					}
				}
				if !validDateType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "date-type", flagDateType, allowedDateType)
				}
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"addonName", "company", "country", "endDate", "hosting", "licenseId", "licenseType", "partner", "region", "startDate", "tier"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"asc", "desc"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			if cmd.Flags().Changed("accept") {
				allowedAccept := []string{"csv", "json"}
				validAccept := false
				for _, v := range allowedAccept {
					if flagAccept == v {
						validAccept = true
						break
					}
				}
				if !validAccept {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "accept", flagAccept, allowedAccept)
				}
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/licenses/async/export"
			path = replacePathParam(path, "vendorId", args[0])
			params := map[string]string{}
			if flagAddon != "" {
				params["addon"] = fmt.Sprintf("%v", flagAddon)
			}
			if flagStartDate != "" {
				params["startDate"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagText != "" {
				params["text"] = fmt.Sprintf("%v", flagText)
			}
			if flagTier != "" {
				params["tier"] = fmt.Sprintf("%v", flagTier)
			}
			if flagDateType != "" {
				params["dateType"] = fmt.Sprintf("%v", flagDateType)
			}
			if flagLicenseType != "" {
				params["licenseType"] = fmt.Sprintf("%v", flagLicenseType)
			}
			if flagPartnerType != "" {
				params["partnerType"] = fmt.Sprintf("%v", flagPartnerType)
			}
			if flagHosting != "" {
				params["hosting"] = fmt.Sprintf("%v", flagHosting)
			}
			if flagCloudComplianceBoundaries != "" {
				params["cloudComplianceBoundaries"] = fmt.Sprintf("%v", flagCloudComplianceBoundaries)
			}
			if flagAppEdition != "" {
				params["appEdition"] = fmt.Sprintf("%v", flagAppEdition)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagWithAttribution != false {
				params["withAttribution"] = fmt.Sprintf("%v", flagWithAttribution)
			}
			if flagWithDataInsights != false {
				params["withDataInsights"] = fmt.Sprintf("%v", flagWithDataInsights)
			}
			if flagIncludeAtlassianLicenses != false {
				params["includeAtlassianLicenses"] = fmt.Sprintf("%v", flagIncludeAtlassianLicenses)
			}
			if flagLastUpdated != "" {
				params["lastUpdated"] = fmt.Sprintf("%v", flagLastUpdated)
			}
			if flagShowLifeTimeFreeLicenses != false {
				params["showLifeTimeFreeLicenses"] = fmt.Sprintf("%v", flagShowLifeTimeFreeLicenses)
			}
			if flagLicenseLevel != "" {
				params["licenseLevel"] = fmt.Sprintf("%v", flagLicenseLevel)
			}
			if flagShowLicensesHistory != false {
				params["showLicensesHistory"] = fmt.Sprintf("%v", flagShowLicensesHistory)
			}
			if flagSortBy != "" {
				params["sortBy"] = fmt.Sprintf("%v", flagSortBy)
			}
			if flagOrder != "" {
				params["order"] = fmt.Sprintf("%v", flagOrder)
			}
			if flagAccept != "" {
				params["accept"] = fmt.Sprintf("%v", flagAccept)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "reporting", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "reporting", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reporting", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reporting", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reporting", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "reporting",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reporting", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "reporting", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagAddon, "addon", "", "If specified, restricts the query to values for apps with the specified keys")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Starting date for the query")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Ending date for the query")
	cmd.Flags().StringVar(&flagText, "text", "", "Text to search for in license fields (license id, customer information and partner information)")
	cmd.Flags().StringVar(&flagTier, "tier", "", "Restricts the query to values for these user/edition tiers")
	cmd.Flags().StringVar(&flagDateType, "date-type", "", "The date field against which filters will be applied (one of: end, start)")
	cmd.Flags().StringVar(&flagLicenseType, "license-type", "", "If specified, restricts the query to values with the provided license type; 'inactive' queries for expired licenses.")
	cmd.Flags().StringVar(&flagPartnerType, "partner-type", "", "Specifies whether to query only direct sales, expert sales, or reseller sales")
	cmd.Flags().StringVar(&flagHosting, "hosting", "", "Restricts the query to values for these hosting types")
	cmd.Flags().StringVar(&flagCloudComplianceBoundaries, "cloud-compliance-boundaries", "", "Restricts the query to values for these cloud compliance boundaries types, with default value as 'commercial'.")
	cmd.Flags().StringVar(&flagAppEdition, "app-edition", "", "Restricts the query to these app edition types")
	cmd.Flags().StringVar(&flagStatus, "status", "", "If specified, restricts the query to values with the provided status")
	cmd.Flags().BoolVar(&flagWithAttribution, "with-attribution", false, "This field is deprecated. Please use withDataInsights to obtain additional data insights.")
	cmd.Flags().BoolVar(&flagWithDataInsights, "with-data-insights", false, "If specified, retrieve additional data insights - marketing funnel attribution")
	cmd.Flags().BoolVar(&flagIncludeAtlassianLicenses, "include-atlassian-licenses", false, "If true, include internal Atlassian licenses in the report")
	cmd.Flags().StringVar(&flagLastUpdated, "last-updated", "", "If specified, restricts the query to values updated on or after the specified date")
	cmd.Flags().BoolVar(&flagShowLifeTimeFreeLicenses, "show-life-time-free-licenses", false, "If specified")
	cmd.Flags().StringVar(&flagLicenseLevel, "license-level", "", "If specified, restricts the query to values with the provided license level.")
	cmd.Flags().BoolVar(&flagShowLicensesHistory, "show-licenses-history", false, "If specified, determines whether to return the historical snapshots of the licenses as well or not")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "If specified, determines the license sort order (one of: addonName, company, country, endDate, hosting, licenseId, licenseType, partner, region, startDate, tier)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Determines whether values are sorted in ascending or descending order (one of: asc, desc)")
	cmd.Flags().StringVar(&flagAccept, "accept", "", "Specifies the response format. If unspecified, the 'Accept' header will be used. (one of: csv, json)")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
