// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVendorsReportingGetVendors13Cmd(flags *rootFlags) *cobra.Command {
	var flagAddon string
	var flagStartDate string
	var flagEndDate string
	var flagText string
	var flagTier string
	var flagDateType string
	var flagLicenseType string
	var flagPartnerType string
	var flagHosting string
	var flagCloudComplianceBoundaries string
	var flagAppEdition string
	var flagStatus string
	var flagWithAttribution bool
	var flagWithDataInsights bool
	var flagIncludeAtlassianLicenses bool
	var flagLastUpdated string
	var flagShowLifeTimeFreeLicenses bool
	var flagLicenseLevel string
	var flagShowLicensesHistory bool
	var flagSortBy string
	var flagOrder string
	var flagAccept string

	cmd := &cobra.Command{
		Use:         "get-vendors-13 <vendorId>",
		Short:       "Export all licenses, matching the specified filters, for the specified vendor's apps.",
		Example:     "  jira-pp-cli-pp-cli vendors reporting get-vendors-13 42",
		Annotations: map[string]string{"pp:endpoint": "reporting.get-vendors-13", "pp:method": "GET", "pp:path": "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/licenses/export", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("date-type") {
				allowedDateType := []string{"end", "start"}
				validDateType := false
				for _, v := range allowedDateType {
					if flagDateType == v {
						validDateType = true
						break
					}
				}
				if !validDateType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "date-type", flagDateType, allowedDateType)
				}
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"addonName", "company", "country", "endDate", "hosting", "licenseId", "licenseType", "partner", "region", "startDate", "tier"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"asc", "desc"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			if cmd.Flags().Changed("accept") {
				allowedAccept := []string{"csv", "json"}
				validAccept := false
				for _, v := range allowedAccept {
					if flagAccept == v {
						validAccept = true
						break
					}
				}
				if !validAccept {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "accept", flagAccept, allowedAccept)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/licenses/export"
			path = replacePathParam(path, "vendorId", args[0])
			params := map[string]string{}
			if flagAddon != "" {
				params["addon"] = fmt.Sprintf("%v", flagAddon)
			}
			if flagStartDate != "" {
				params["startDate"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagText != "" {
				params["text"] = fmt.Sprintf("%v", flagText)
			}
			if flagTier != "" {
				params["tier"] = fmt.Sprintf("%v", flagTier)
			}
			if flagDateType != "" {
				params["dateType"] = fmt.Sprintf("%v", flagDateType)
			}
			if flagLicenseType != "" {
				params["licenseType"] = fmt.Sprintf("%v", flagLicenseType)
			}
			if flagPartnerType != "" {
				params["partnerType"] = fmt.Sprintf("%v", flagPartnerType)
			}
			if flagHosting != "" {
				params["hosting"] = fmt.Sprintf("%v", flagHosting)
			}
			if flagCloudComplianceBoundaries != "" {
				params["cloudComplianceBoundaries"] = fmt.Sprintf("%v", flagCloudComplianceBoundaries)
			}
			if flagAppEdition != "" {
				params["appEdition"] = fmt.Sprintf("%v", flagAppEdition)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagWithAttribution != false {
				params["withAttribution"] = fmt.Sprintf("%v", flagWithAttribution)
			}
			if flagWithDataInsights != false {
				params["withDataInsights"] = fmt.Sprintf("%v", flagWithDataInsights)
			}
			if flagIncludeAtlassianLicenses != false {
				params["includeAtlassianLicenses"] = fmt.Sprintf("%v", flagIncludeAtlassianLicenses)
			}
			if flagLastUpdated != "" {
				params["lastUpdated"] = fmt.Sprintf("%v", flagLastUpdated)
			}
			if flagShowLifeTimeFreeLicenses != false {
				params["showLifeTimeFreeLicenses"] = fmt.Sprintf("%v", flagShowLifeTimeFreeLicenses)
			}
			if flagLicenseLevel != "" {
				params["licenseLevel"] = fmt.Sprintf("%v", flagLicenseLevel)
			}
			if flagShowLicensesHistory != false {
				params["showLicensesHistory"] = fmt.Sprintf("%v", flagShowLicensesHistory)
			}
			if flagSortBy != "" {
				params["sortBy"] = fmt.Sprintf("%v", flagSortBy)
			}
			if flagOrder != "" {
				params["order"] = fmt.Sprintf("%v", flagOrder)
			}
			if flagAccept != "" {
				params["accept"] = fmt.Sprintf("%v", flagAccept)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "reporting", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAddon, "addon", "", "If specified, restricts the query to values for apps with the specified keys")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Starting date for the query")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Ending date for the query")
	cmd.Flags().StringVar(&flagText, "text", "", "Text to search for in license fields (license id, customer information and partner information)")
	cmd.Flags().StringVar(&flagTier, "tier", "", "Restricts the query to values for these user/edition tiers")
	cmd.Flags().StringVar(&flagDateType, "date-type", "", "The date field against which filters will be applied (one of: end, start)")
	cmd.Flags().StringVar(&flagLicenseType, "license-type", "", "If specified, restricts the query to values with the provided license type; 'inactive' queries for expired licenses.")
	cmd.Flags().StringVar(&flagPartnerType, "partner-type", "", "Specifies whether to query only direct sales, expert sales, or reseller sales")
	cmd.Flags().StringVar(&flagHosting, "hosting", "", "Restricts the query to values for these hosting types")
	cmd.Flags().StringVar(&flagCloudComplianceBoundaries, "cloud-compliance-boundaries", "", "Restricts the query to values for these cloud compliance boundaries types, with default value as 'commercial'.")
	cmd.Flags().StringVar(&flagAppEdition, "app-edition", "", "Restricts the query to these app edition types")
	cmd.Flags().StringVar(&flagStatus, "status", "", "If specified, restricts the query to values with the provided status")
	cmd.Flags().BoolVar(&flagWithAttribution, "with-attribution", false, "This field is deprecated. Please use withDataInsights to obtain additional data insights.")
	cmd.Flags().BoolVar(&flagWithDataInsights, "with-data-insights", false, "If specified, retrieve additional data insights - marketing funnel attribution")
	cmd.Flags().BoolVar(&flagIncludeAtlassianLicenses, "include-atlassian-licenses", false, "If true, include internal Atlassian licenses in the report")
	cmd.Flags().StringVar(&flagLastUpdated, "last-updated", "", "If specified, restricts the query to values updated on or after the specified date")
	cmd.Flags().BoolVar(&flagShowLifeTimeFreeLicenses, "show-life-time-free-licenses", false, "If specified")
	cmd.Flags().StringVar(&flagLicenseLevel, "license-level", "", "If specified, restricts the query to values with the provided license level.")
	cmd.Flags().BoolVar(&flagShowLicensesHistory, "show-licenses-history", false, "If specified, determines whether to return the historical snapshots of the licenses as well or not")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "If specified, determines the license sort order (one of: addonName, company, country, endDate, hosting, licenseId, licenseType, partner, region, startDate, tier)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Determines whether values are sorted in ascending or descending order (one of: asc, desc)")
	cmd.Flags().StringVar(&flagAccept, "accept", "", "Specifies the response format. If unspecified, the 'Accept' header will be used. (one of: csv, json)")

	return cmd
}
