// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVendorsReportingGetVendors15Cmd(flags *rootFlags) *cobra.Command {
	var flagAddon string
	var flagStartDate string
	var flagEndDate string
	var flagText string
	var flagTier string
	var flagSaleType string
	var flagPartnerType string
	var flagHosting string
	var flagCloudComplianceBoundaries string
	var flagAppEdition string
	var flagLastUpdated string
	var flagExcludeZeroTransactions bool
	var flagShowProratedTransactions bool
	var flagIncludeManualInvoice bool
	var flagPaymentStatus string
	var flagLicenseLevel string
	var flagSortBy string
	var flagOrder string
	var flagOffset string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-vendors-15 <vendorId>",
		Short:       "Get a list of transactions for the specified vendor's apps. This resource requires authentication.",
		Example:     "  jira-pp-cli-pp-cli vendors reporting get-vendors-15 42",
		Annotations: map[string]string{"pp:endpoint": "reporting.get-vendors-15", "pp:method": "GET", "pp:path": "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/sales/transactions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"addonName", "company", "country", "date", "hosting", "licenseId", "licenseType", "partner", "partnerType", "purchasePrice", "region", "saleType", "tier", "transactionId", "vendorAmount", "paymentStatus"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"asc", "desc"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/reporting/sales/transactions"
			path = replacePathParam(path, "vendorId", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "reporting", path, map[string]string{
				"addon":                     fmt.Sprintf("%v", flagAddon),
				"startDate":                 fmt.Sprintf("%v", flagStartDate),
				"endDate":                   fmt.Sprintf("%v", flagEndDate),
				"text":                      fmt.Sprintf("%v", flagText),
				"tier":                      fmt.Sprintf("%v", flagTier),
				"saleType":                  fmt.Sprintf("%v", flagSaleType),
				"partnerType":               fmt.Sprintf("%v", flagPartnerType),
				"hosting":                   fmt.Sprintf("%v", flagHosting),
				"cloudComplianceBoundaries": fmt.Sprintf("%v", flagCloudComplianceBoundaries),
				"appEdition":                fmt.Sprintf("%v", flagAppEdition),
				"lastUpdated":               fmt.Sprintf("%v", flagLastUpdated),
				"excludeZeroTransactions":   fmt.Sprintf("%v", flagExcludeZeroTransactions),
				"showProratedTransactions":  fmt.Sprintf("%v", flagShowProratedTransactions),
				"includeManualInvoice":      fmt.Sprintf("%v", flagIncludeManualInvoice),
				"paymentStatus":             fmt.Sprintf("%v", flagPaymentStatus),
				"licenseLevel":              fmt.Sprintf("%v", flagLicenseLevel),
				"sortBy":                    fmt.Sprintf("%v", flagSortBy),
				"order":                     fmt.Sprintf("%v", flagOrder),
				"offset":                    fmt.Sprintf("%v", flagOffset),
				"limit":                     fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "offset", "offset", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAddon, "addon", "", "If specified, restricts the query to values for apps with the specified keys")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Starting date for the query")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Ending date for the query")
	cmd.Flags().StringVar(&flagText, "text", "", "Text to search for in transaction fields (transaction id, license id, customer information and partner information)")
	cmd.Flags().StringVar(&flagTier, "tier", "", "Restricts the query to values for these user/edition tiers")
	cmd.Flags().StringVar(&flagSaleType, "sale-type", "", "Restricts the query to sales of these types")
	cmd.Flags().StringVar(&flagPartnerType, "partner-type", "", "Specifies whether to query only direct sales, expert sales, or reseller sales")
	cmd.Flags().StringVar(&flagHosting, "hosting", "", "Restricts the query to values for these hosting types")
	cmd.Flags().StringVar(&flagCloudComplianceBoundaries, "cloud-compliance-boundaries", "", "Restricts the query to values for these cloud compliance boundaries types, with default value as 'commercial'.")
	cmd.Flags().StringVar(&flagAppEdition, "app-edition", "", "Restricts the query to these app edition types")
	cmd.Flags().StringVar(&flagLastUpdated, "last-updated", "", "If specified, restricts the query to values updated on or after the specified date")
	cmd.Flags().BoolVar(&flagExcludeZeroTransactions, "exclude-zero-transactions", false, "If set to true, exclude $0 transactions from reports")
	cmd.Flags().BoolVar(&flagShowProratedTransactions, "show-prorated-transactions", false, "If set to true, returns all transaction lines with prorated charges for maximum quantity billing in the report.")
	cmd.Flags().BoolVar(&flagIncludeManualInvoice, "include-manual-invoice", false, "If set to true, include manual invoices in reports")
	cmd.Flags().StringVar(&flagPaymentStatus, "payment-status", "", "Restricts the query to payment status of these types")
	cmd.Flags().StringVar(&flagLicenseLevel, "license-level", "", "If specified, restricts the query to values with the provided license level.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "If specified, determines the transaction sort order (one of: addonName, company, country, date, hosting, licenseId, licenseType, partner, partnerType, purchasePrice, region, saleType, tier, transactionId, vendorAmount, paymentStatus)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Determines whether values are sorted in ascending or descending order (one of: asc, desc)")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "If specified, skips ahead by this number of items")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "If specified, limits the result set to this number of items. Max limit is 50")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
