// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVendorsPartnerMetricsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "partner-metrics",
		Short: "Create partner metrics for vendors",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newVendorsPartnerMetricsCreateCmd(flags))
	return cmd
}
