// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVendorsPromotionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyLinksCodesHref string
	var bodyLinksCodesTitle string
	var bodyLinksCodesType string
	var bodyLinksEditHref string
	var bodyLinksEditTitle string
	var bodyLinksEditType string
	var bodyLinksSelfHref string
	var bodyLinksSelfTitle string
	var bodyLinksSelfType string
	var bodyLinksStatusHref string
	var bodyLinksStatusTitle string
	var bodyLinksStatusType string
	var bodyLinksUsageHref string
	var bodyLinksUsageTitle string
	var bodyLinksUsageType string
	var bodyAppliesToAllLicenseTypes bool
	var bodyDiscount string
	var bodyDiscountPercent int
	var bodyDiscountType string
	var bodyEndImmediatelyDate string
	var bodyExpirationDate string
	var bodyHosting string
	var bodyMaxUses int
	var bodyName string
	var bodyProducts string
	var bodyStartDate string
	var bodyStatus string
	var bodyUsageType string
	var bodyUsed int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <vendorId>",
		Short:       "Create a new promotion for the specified vendor. This resource requires authentication. **This is a deprecated API.",
		Example:     "  jira-pp-cli-pp-cli vendors promotions create 42 --discount-type FLAT",
		Annotations: map[string]string{"pp:endpoint": "promotions.create", "pp:method": "POST", "pp:path": "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/promotions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("links-codes-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-codes-href")
				}
				if !cmd.Flags().Changed("links-edit-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-edit-href")
				}
				if !cmd.Flags().Changed("links-self-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-self-href")
				}
				if !cmd.Flags().Changed("links-status-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-status-href")
				}
				if !cmd.Flags().Changed("links-usage-href") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "links-usage-href")
				}
				if !cmd.Flags().Changed("discount-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discount-type")
				}
				if !cmd.Flags().Changed("expiration-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expiration-date")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("products") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "products")
				}
				if !cmd.Flags().Changed("usage-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "usage-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/promotions"
			path = replacePathParam(path, "vendorId", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedLinks := map[string]any{}
					{
						nestedLinksCodes := map[string]any{}
						if bodyLinksCodesHref != "" {
							nestedLinksCodes["href"] = bodyLinksCodesHref
						}
						if bodyLinksCodesTitle != "" {
							nestedLinksCodes["title"] = bodyLinksCodesTitle
						}
						if bodyLinksCodesType != "" {
							nestedLinksCodes["type"] = bodyLinksCodesType
						}
						if len(nestedLinksCodes) > 0 {
							nestedLinks["codes"] = nestedLinksCodes
						}
					}
					{
						nestedLinksEdit := map[string]any{}
						if bodyLinksEditHref != "" {
							nestedLinksEdit["href"] = bodyLinksEditHref
						}
						if bodyLinksEditTitle != "" {
							nestedLinksEdit["title"] = bodyLinksEditTitle
						}
						if bodyLinksEditType != "" {
							nestedLinksEdit["type"] = bodyLinksEditType
						}
						if len(nestedLinksEdit) > 0 {
							nestedLinks["edit"] = nestedLinksEdit
						}
					}
					{
						nestedLinksSelf := map[string]any{}
						if bodyLinksSelfHref != "" {
							nestedLinksSelf["href"] = bodyLinksSelfHref
						}
						if bodyLinksSelfTitle != "" {
							nestedLinksSelf["title"] = bodyLinksSelfTitle
						}
						if bodyLinksSelfType != "" {
							nestedLinksSelf["type"] = bodyLinksSelfType
						}
						if len(nestedLinksSelf) > 0 {
							nestedLinks["self"] = nestedLinksSelf
						}
					}
					{
						nestedLinksStatus := map[string]any{}
						if bodyLinksStatusHref != "" {
							nestedLinksStatus["href"] = bodyLinksStatusHref
						}
						if bodyLinksStatusTitle != "" {
							nestedLinksStatus["title"] = bodyLinksStatusTitle
						}
						if bodyLinksStatusType != "" {
							nestedLinksStatus["type"] = bodyLinksStatusType
						}
						if len(nestedLinksStatus) > 0 {
							nestedLinks["status"] = nestedLinksStatus
						}
					}
					{
						nestedLinksUsage := map[string]any{}
						if bodyLinksUsageHref != "" {
							nestedLinksUsage["href"] = bodyLinksUsageHref
						}
						if bodyLinksUsageTitle != "" {
							nestedLinksUsage["title"] = bodyLinksUsageTitle
						}
						if bodyLinksUsageType != "" {
							nestedLinksUsage["type"] = bodyLinksUsageType
						}
						if len(nestedLinksUsage) > 0 {
							nestedLinks["usage"] = nestedLinksUsage
						}
					}
					if len(nestedLinks) > 0 {
						body["_links"] = nestedLinks
					}
				}
				if cmd.Flags().Changed("applies-to-all-license-types") {
					body["appliesToAllLicenseTypes"] = bodyAppliesToAllLicenseTypes
				}
				if bodyDiscount != "" {
					var parsedDiscount any
					if err := json.Unmarshal([]byte(bodyDiscount), &parsedDiscount); err != nil {
						return fmt.Errorf("parsing --discount JSON: %w", err)
					}
					body["discount"] = parsedDiscount
				}
				if bodyDiscountPercent != 0 {
					body["discountPercent"] = bodyDiscountPercent
				}
				if bodyDiscountType != "" {
					body["discountType"] = bodyDiscountType
				}
				if bodyEndImmediatelyDate != "" {
					body["endImmediatelyDate"] = bodyEndImmediatelyDate
				}
				if bodyExpirationDate != "" {
					body["expirationDate"] = bodyExpirationDate
				}
				if bodyHosting != "" {
					body["hosting"] = bodyHosting
				}
				if bodyMaxUses != 0 {
					body["maxUses"] = bodyMaxUses
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyProducts != "" {
					var parsedProducts any
					if err := json.Unmarshal([]byte(bodyProducts), &parsedProducts); err != nil {
						return fmt.Errorf("parsing --products JSON: %w", err)
					}
					body["products"] = parsedProducts
				}
				if bodyStartDate != "" {
					body["startDate"] = bodyStartDate
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				if bodyUsageType != "" {
					body["usageType"] = bodyUsageType
				}
				if bodyUsed != 0 {
					body["used"] = bodyUsed
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "promotions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "promotions", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "promotions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "promotions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "promotions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "promotions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "promotions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "promotions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyLinksCodesHref, "links-codes-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksCodesTitle, "links-codes-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksCodesType, "links-codes-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksEditHref, "links-edit-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksEditTitle, "links-edit-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksEditType, "links-edit-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksSelfHref, "links-self-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksSelfTitle, "links-self-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksSelfType, "links-self-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksStatusHref, "links-status-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksStatusTitle, "links-status-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksStatusType, "links-status-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().StringVar(&bodyLinksUsageHref, "links-usage-href", "", "The link URI - hostname and scheme will be omitted if it is a link within Marketplace")
	cmd.Flags().StringVar(&bodyLinksUsageTitle, "links-usage-title", "", "Display name of the link - usually omitted")
	cmd.Flags().StringVar(&bodyLinksUsageType, "links-usage-type", "", "Content type of the linked data - may be omitted for JSON resources, will be 'text/html' for web pages")
	cmd.Flags().BoolVar(&bodyAppliesToAllLicenseTypes, "applies-to-all-license-types", false, "True if the promotion applies to all license types")
	cmd.Flags().StringVar(&bodyDiscount, "discount", "", "List of pricing tiers showing what the resulting discounts will be")
	cmd.Flags().IntVar(&bodyDiscountPercent, "discount-percent", 0, "Discount percentage if this promotion is based on a percentage discount")
	cmd.Flags().StringVar(&bodyDiscountType, "discount-type", "", "Indicates whether the promotion uses percentage discounts or dollar amounts")
	cmd.Flags().StringVar(&bodyEndImmediatelyDate, "end-immediately-date", "", "Date and time when the promotion was stopped. This is only applicable when a promotion is ended early")
	cmd.Flags().StringVar(&bodyExpirationDate, "expiration-date", "", "Expiration date of the promotion")
	cmd.Flags().StringVar(&bodyHosting, "hosting", "", "Hosting environment of the apps for which this promotion is applicable.")
	cmd.Flags().IntVar(&bodyMaxUses, "max-uses", 0, "Maximum number of times this promotion can be used if it is a shared promotion")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the promotion")
	cmd.Flags().StringVar(&bodyProducts, "products", "", "App keys of the apps for which this promotion is applicable")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "Starting date of the promotion")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Current status of the promotion")
	cmd.Flags().StringVar(&bodyUsageType, "usage-type", "", "Indicates whether this is a shared or single-use promotion")
	cmd.Flags().IntVar(&bodyUsed, "used", 0, "Number of times this promotion has been used")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
