// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVendorsPartnerMetricsCreateCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagOffset string
	var bodyAttributeFilter string
	var bodyAttributes string
	var bodyDateRangeEndDate string
	var bodyDateRangeStartDate string
	var bodyGranularity string
	var bodyMetricsMetricFields string
	var bodyMetricsMetricSets string
	var bodySortByList string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <vendorId>",
		Short:       "This resource fetches the time series data for the metric of choice. It requires authentication.",
		Example:     "  jira-pp-cli-pp-cli vendors partner-metrics create 42",
		Annotations: map[string]string{"pp:endpoint": "partner-metrics.create", "pp:method": "POST", "pp:path": "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/partner-metrics"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://marketplace.atlassian.com/rest/2/vendors/{vendorId}/partner-metrics"
			path = replacePathParam(path, "vendorId", args[0])
			params := map[string]string{}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			if flagOffset != "" {
				params["offset"] = fmt.Sprintf("%v", flagOffset)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAttributeFilter != "" {
					body["attributeFilter"] = bodyAttributeFilter
				}
				if bodyAttributes != "" {
					var parsedAttributes any
					if err := json.Unmarshal([]byte(bodyAttributes), &parsedAttributes); err != nil {
						return fmt.Errorf("parsing --attributes JSON: %w", err)
					}
					body["attributes"] = parsedAttributes
				}
				{
					nestedDateRange := map[string]any{}
					if bodyDateRangeEndDate != "" {
						nestedDateRange["endDate"] = bodyDateRangeEndDate
					}
					if bodyDateRangeStartDate != "" {
						nestedDateRange["startDate"] = bodyDateRangeStartDate
					}
					if len(nestedDateRange) > 0 {
						body["dateRange"] = nestedDateRange
					}
				}
				if bodyGranularity != "" {
					body["granularity"] = bodyGranularity
				}
				{
					nestedMetrics := map[string]any{}
					if bodyMetricsMetricFields != "" {
						var parsedMetricsMetricFields any
						if err := json.Unmarshal([]byte(bodyMetricsMetricFields), &parsedMetricsMetricFields); err != nil {
							return fmt.Errorf("parsing --metrics-metric-fields JSON: %w", err)
						}
						nestedMetrics["metricFields"] = parsedMetricsMetricFields
					}
					if bodyMetricsMetricSets != "" {
						var parsedMetricsMetricSets any
						if err := json.Unmarshal([]byte(bodyMetricsMetricSets), &parsedMetricsMetricSets); err != nil {
							return fmt.Errorf("parsing --metrics-metric-sets JSON: %w", err)
						}
						nestedMetrics["metricSets"] = parsedMetricsMetricSets
					}
					if len(nestedMetrics) > 0 {
						body["metrics"] = nestedMetrics
					}
				}
				if bodySortByList != "" {
					var parsedSortByList any
					if err := json.Unmarshal([]byte(bodySortByList), &parsedSortByList); err != nil {
						return fmt.Errorf("parsing --sort-by-list JSON: %w", err)
					}
					body["sortByList"] = parsedSortByList
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "partner-metrics", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "partner-metrics", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "partner-metrics", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "partner-metrics", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "partner-metrics", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "partner-metrics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "partner-metrics", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "partner-metrics", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "We are using granularity-based pagination, the limit is in the number of days/week/month/year based on granularity.")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "If specified, skips ahead by this number of days/week/month/year based on granularity")
	cmd.Flags().StringVar(&bodyAttributeFilter, "attribute-filter", "", "Attribute filters provide the specific attribute values in the report.")
	cmd.Flags().StringVar(&bodyAttributes, "attributes", "", "The attributes requested and displayed.")
	cmd.Flags().StringVar(&bodyDateRangeEndDate, "date-range-end-date", "", "* RECURRING_REVENUE: End date should be less than or equal to current date * DISTRIBUTIONS")
	cmd.Flags().StringVar(&bodyDateRangeStartDate, "date-range-start-date", "", "Start date")
	cmd.Flags().StringVar(&bodyGranularity, "granularity", "", "Defines the granularity to bucket results.")
	cmd.Flags().StringVar(&bodyMetricsMetricFields, "metrics-metric-fields", "", "Predefined metrics fields requested and displayed.")
	cmd.Flags().StringVar(&bodyMetricsMetricSets, "metrics-metric-sets", "", "The predefined metric sets (group of metric fields) requested and displayed.")
	cmd.Flags().StringVar(&bodySortByList, "sort-by-list", "", "list of sorting criteria to define the order in which the response data should be sorted.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
