// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newWikiPublishSharedDraftCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagExpand string
	var bodyAncestors string
	var bodySpaceKey string
	var bodyStatus2 string
	var bodyTitle string
	var bodyType string
	var bodyVersionNumber int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "publish-shared-draft <draftId>",
		Short:       "Publishes a shared draft of a page created from a blueprint. By default, the following objects are expanded: `body.",
		Example:     "  jira-pp-cli-pp-cli wiki publish-shared-draft 550e8400-e29b-41d4-a716-446655440000 --title example-resource",
		Annotations: map[string]string{"pp:endpoint": "wiki.publish-shared-draft", "pp:method": "PUT", "pp:path": "/wiki/rest/api/content/blueprint/instance/{draftId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("space-key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "space-key")
				}
				if !cmd.Flags().Changed("title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
				if !cmd.Flags().Changed("type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
				if !cmd.Flags().Changed("version-number") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "version-number")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/wiki/rest/api/content/blueprint/instance/{draftId}"
			path = replacePathParam(path, "draftId", args[0])
			params := map[string]string{}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagExpand != "" {
				params["expand"] = fmt.Sprintf("%v", flagExpand)
			}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAncestors != "" {
					var parsedAncestors any
					if err := json.Unmarshal([]byte(bodyAncestors), &parsedAncestors); err != nil {
						return fmt.Errorf("parsing --ancestors JSON: %w", err)
					}
					body["ancestors"] = parsedAncestors
				}
				{
					nestedSpace := map[string]any{}
					if bodySpaceKey != "" {
						nestedSpace["key"] = bodySpaceKey
					}
					if len(nestedSpace) > 0 {
						body["space"] = nestedSpace
					}
				}
				if bodyStatus2 != "" {
					body["status"] = bodyStatus2
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
				{
					nestedVersion := map[string]any{}
					if bodyVersionNumber != 0 {
						nestedVersion["number"] = bodyVersionNumber
					}
					if len(nestedVersion) > 0 {
						body["version"] = nestedVersion
					}
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "wiki", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "wiki", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "wiki",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "draft", "The status of the content to be updated, i.e. the draft.")
	cmd.Flags().StringVar(&flagExpand, "expand", "", "A multi-value parameter indicating which properties of the content to expand. - `childTypes.")
	cmd.Flags().StringVar(&bodyAncestors, "ancestors", "", "The new ancestor (i.e. parent page) for the content.")
	cmd.Flags().StringVar(&bodySpaceKey, "space-key", "", "The key of the space")
	cmd.Flags().StringVar(&bodyStatus2, "status-2", "current", "The status of the content. Set this to `current` or omit it altogether.")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "The title of the content. If you don't want to change the title, set this to the current title of the draft.")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of content. Set this to `page`.")
	cmd.Flags().IntVar(&bodyVersionNumber, "version-number", 0, "The version number. Set this to `1`.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
