// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newWikiCreateAuditRecordCmd(flags *rootFlags) *cobra.Command {
	var bodyAffectedObjectName string
	var bodyAffectedObjectObjectType string
	var bodyAssociatedObjects string
	var bodyAuthorDisplayName string
	var bodyAuthorOperations string
	var bodyAuthorType string
	var bodyAuthorUserKey string
	var bodyAuthorUsername string
	var bodyCategory string
	var bodyChangedValues string
	var bodyCreationDate int
	var bodyDescription string
	var bodyRemoteAddress string
	var bodySummary string
	var bodySysAdmin bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-audit-record",
		Short:       "Creates a record in the audit log. **[Permissions](https://confluence.atlassian.",
		Example:     "  jira-pp-cli-pp-cli wiki create-audit-record --remote-address 123 Test St, Anytown, ST 12345",
		Annotations: map[string]string{"pp:endpoint": "wiki.create-audit-record", "pp:method": "POST", "pp:path": "/wiki/rest/api/audit"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("affected-object-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "affected-object-name")
				}
				if !cmd.Flags().Changed("affected-object-object-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "affected-object-object-type")
				}
				if !cmd.Flags().Changed("author-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "author-type")
				}
				if !cmd.Flags().Changed("remote-address") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "remote-address")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/wiki/rest/api/audit"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAffectedObject := map[string]any{}
					if bodyAffectedObjectName != "" {
						nestedAffectedObject["name"] = bodyAffectedObjectName
					}
					if bodyAffectedObjectObjectType != "" {
						nestedAffectedObject["objectType"] = bodyAffectedObjectObjectType
					}
					if len(nestedAffectedObject) > 0 {
						body["affectedObject"] = nestedAffectedObject
					}
				}
				if bodyAssociatedObjects != "" {
					var parsedAssociatedObjects any
					if err := json.Unmarshal([]byte(bodyAssociatedObjects), &parsedAssociatedObjects); err != nil {
						return fmt.Errorf("parsing --associated-objects JSON: %w", err)
					}
					body["associatedObjects"] = parsedAssociatedObjects
				}
				{
					nestedAuthor := map[string]any{}
					if bodyAuthorDisplayName != "" {
						nestedAuthor["displayName"] = bodyAuthorDisplayName
					}
					if bodyAuthorOperations != "" {
						var parsedAuthorOperations any
						if err := json.Unmarshal([]byte(bodyAuthorOperations), &parsedAuthorOperations); err != nil {
							return fmt.Errorf("parsing --author-operations JSON: %w", err)
						}
						nestedAuthor["operations"] = parsedAuthorOperations
					}
					if bodyAuthorType != "" {
						nestedAuthor["type"] = bodyAuthorType
					}
					if bodyAuthorUserKey != "" {
						nestedAuthor["userKey"] = bodyAuthorUserKey
					}
					if bodyAuthorUsername != "" {
						nestedAuthor["username"] = bodyAuthorUsername
					}
					if len(nestedAuthor) > 0 {
						body["author"] = nestedAuthor
					}
				}
				if bodyCategory != "" {
					body["category"] = bodyCategory
				}
				if bodyChangedValues != "" {
					var parsedChangedValues any
					if err := json.Unmarshal([]byte(bodyChangedValues), &parsedChangedValues); err != nil {
						return fmt.Errorf("parsing --changed-values JSON: %w", err)
					}
					body["changedValues"] = parsedChangedValues
				}
				if bodyCreationDate != 0 {
					body["creationDate"] = bodyCreationDate
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyRemoteAddress != "" {
					body["remoteAddress"] = bodyRemoteAddress
				}
				if bodySummary != "" {
					body["summary"] = bodySummary
				}
				if cmd.Flags().Changed("sys-admin") {
					body["sysAdmin"] = bodySysAdmin
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "wiki", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "wiki", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "wiki",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAffectedObjectName, "affected-object-name", "", "Name")
	cmd.Flags().StringVar(&bodyAffectedObjectObjectType, "affected-object-object-type", "", "Object type")
	cmd.Flags().StringVar(&bodyAssociatedObjects, "associated-objects", "", "Objects that were associated with the event.")
	cmd.Flags().StringVar(&bodyAuthorDisplayName, "author-display-name", "", "The name that is displayed on the audit log in the Confluence UI.")
	cmd.Flags().StringVar(&bodyAuthorOperations, "author-operations", "", "Always defaults to null.")
	cmd.Flags().StringVar(&bodyAuthorType, "author-type", "", "Set to 'user'.")
	cmd.Flags().StringVar(&bodyAuthorUserKey, "author-user-key", "", "This property is no longer available and will be removed from the documentation soon. Use `accountId` instead.")
	cmd.Flags().StringVar(&bodyAuthorUsername, "author-username", "", "This property is no longer available and will be removed from the documentation soon. Use `accountId` instead.")
	cmd.Flags().StringVar(&bodyCategory, "category", "", "The category of the event, which is displayed in the 'Event type' column on the audit log in the Confluence UI.")
	cmd.Flags().StringVar(&bodyChangedValues, "changed-values", "", "The values that were changed in the event.")
	cmd.Flags().IntVar(&bodyCreationDate, "creation-date", 0, "The creation date-time of the audit record, as a timestamp.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A long description of the event, which is displayed in the 'Description' field on the audit log in the Confluence UI.")
	cmd.Flags().StringVar(&bodyRemoteAddress, "remote-address", "", "The IP address of the computer where the event was initiated from.")
	cmd.Flags().StringVar(&bodySummary, "summary", "", "The summary of the event, which is displayed in the 'Change' column on the audit log in the Confluence UI.")
	cmd.Flags().BoolVar(&bodySysAdmin, "sys-admin", false, "Indicates whether the event was actioned by a system administrator.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
