// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWikiGetAuditRecordsForTimePeriodCmd(flags *rootFlags) *cobra.Command {
	var flagNumber int
	var flagUnits string
	var flagSearchString string
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-audit-records-for-time-period",
		Short:       "Returns records from the audit log, for a time period back from the current date.",
		Example:     "  jira-pp-cli-pp-cli wiki get-audit-records-for-time-period",
		Annotations: map[string]string{"pp:endpoint": "wiki.get-audit-records-for-time-period", "pp:method": "GET", "pp:path": "/wiki/rest/api/audit/since", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("units") {
				allowedUnits := []string{"NANOS", "MICROS", "MILLIS", "SECONDS", "MINUTES", "HOURS", "HALF_DAYS", "DAYS", "WEEKS", "MONTHS", "YEARS", "DECADES", "CENTURIES"}
				validUnits := false
				for _, v := range allowedUnits {
					if flagUnits == v {
						validUnits = true
						break
					}
				}
				if !validUnits {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "units", flagUnits, allowedUnits)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/wiki/rest/api/audit/since"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "wiki", path, map[string]string{
				"number":       fmt.Sprintf("%v", flagNumber),
				"units":        fmt.Sprintf("%v", flagUnits),
				"searchString": fmt.Sprintf("%v", flagSearchString),
				"start":        fmt.Sprintf("%v", flagStart),
				"limit":        fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "", "offset", "limit", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagNumber, "number", 3, "The number of units for the time period.")
	cmd.Flags().StringVar(&flagUnits, "units", "MONTHS", "The unit of time that the time period is measured in. (one of: NANOS, MICROS, MILLIS, SECONDS, MINUTES, HOURS, HALF_DAYS, DAYS, WEEKS, MONTHS, YEARS, DECADES, CENTURIES)")
	cmd.Flags().StringVar(&flagSearchString, "search-string", "", "Filters the results to records that have string property values matching the `searchString`.")
	cmd.Flags().IntVar(&flagStart, "start", 0, "The starting index of the returned records.")
	cmd.Flags().IntVar(&flagLimit, "limit", 1000, "The maximum number of records to return per page. Note, this may be restricted by fixed system limits.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
