// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newWikiUpdateContentTemplateCmd(flags *rootFlags) *cobra.Command {
	var bodyBodyAnonymousExportViewRepresentation string
	var bodyBodyAnonymousExportViewValue string
	var bodyBodyAtlasDocFormatRepresentation string
	var bodyBodyAtlasDocFormatValue string
	var bodyBodyEditorRepresentation string
	var bodyBodyEditorValue string
	var bodyBodyEditor2Representation string
	var bodyBodyEditor2Value string
	var bodyBodyExportViewRepresentation string
	var bodyBodyExportViewValue string
	var bodyBodyStorageRepresentation string
	var bodyBodyStorageValue string
	var bodyBodyStyledViewRepresentation string
	var bodyBodyStyledViewValue string
	var bodyBodyViewRepresentation string
	var bodyBodyViewValue string
	var bodyBodyWikiRepresentation string
	var bodyBodyWikiValue string
	var bodyDescription string
	var bodyLabels string
	var bodyName string
	var bodySpaceKey string
	var bodyTemplateId string
	var bodyTemplateType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-content-template",
		Short:       "Updates a content template. Note, blueprint templates cannot be updated via the REST API.",
		Example:     "  jira-pp-cli-pp-cli wiki update-content-template --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "wiki.update-content-template", "pp:method": "PUT", "pp:path": "/wiki/rest/api/template"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("body-anonymous-export-view-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-anonymous-export-view-representation")
				}
				if !cmd.Flags().Changed("body-anonymous-export-view-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-anonymous-export-view-value")
				}
				if !cmd.Flags().Changed("body-atlas-doc-format-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-atlas-doc-format-representation")
				}
				if !cmd.Flags().Changed("body-atlas-doc-format-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-atlas-doc-format-value")
				}
				if !cmd.Flags().Changed("body-editor-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-editor-representation")
				}
				if !cmd.Flags().Changed("body-editor-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-editor-value")
				}
				if !cmd.Flags().Changed("body-editor2-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-editor2-representation")
				}
				if !cmd.Flags().Changed("body-editor2-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-editor2-value")
				}
				if !cmd.Flags().Changed("body-export-view-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-export-view-representation")
				}
				if !cmd.Flags().Changed("body-export-view-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-export-view-value")
				}
				if !cmd.Flags().Changed("body-storage-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-storage-representation")
				}
				if !cmd.Flags().Changed("body-storage-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-storage-value")
				}
				if !cmd.Flags().Changed("body-styled-view-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-styled-view-representation")
				}
				if !cmd.Flags().Changed("body-styled-view-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-styled-view-value")
				}
				if !cmd.Flags().Changed("body-view-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-view-representation")
				}
				if !cmd.Flags().Changed("body-view-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-view-value")
				}
				if !cmd.Flags().Changed("body-wiki-representation") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-wiki-representation")
				}
				if !cmd.Flags().Changed("body-wiki-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body-wiki-value")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("space-key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "space-key")
				}
				if !cmd.Flags().Changed("template-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "template-id")
				}
				if !cmd.Flags().Changed("template-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "template-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/wiki/rest/api/template"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedBody := map[string]any{}
					{
						nestedBodyAnonymousExportView := map[string]any{}
						if bodyBodyAnonymousExportViewRepresentation != "" {
							nestedBodyAnonymousExportView["representation"] = bodyBodyAnonymousExportViewRepresentation
						}
						if bodyBodyAnonymousExportViewValue != "" {
							nestedBodyAnonymousExportView["value"] = bodyBodyAnonymousExportViewValue
						}
						if len(nestedBodyAnonymousExportView) > 0 {
							nestedBody["anonymous_export_view"] = nestedBodyAnonymousExportView
						}
					}
					{
						nestedBodyAtlasDocFormat := map[string]any{}
						if bodyBodyAtlasDocFormatRepresentation != "" {
							nestedBodyAtlasDocFormat["representation"] = bodyBodyAtlasDocFormatRepresentation
						}
						if bodyBodyAtlasDocFormatValue != "" {
							nestedBodyAtlasDocFormat["value"] = bodyBodyAtlasDocFormatValue
						}
						if len(nestedBodyAtlasDocFormat) > 0 {
							nestedBody["atlas_doc_format"] = nestedBodyAtlasDocFormat
						}
					}
					{
						nestedBodyEditor := map[string]any{}
						if bodyBodyEditorRepresentation != "" {
							nestedBodyEditor["representation"] = bodyBodyEditorRepresentation
						}
						if bodyBodyEditorValue != "" {
							nestedBodyEditor["value"] = bodyBodyEditorValue
						}
						if len(nestedBodyEditor) > 0 {
							nestedBody["editor"] = nestedBodyEditor
						}
					}
					{
						nestedBodyEditor2 := map[string]any{}
						if bodyBodyEditor2Representation != "" {
							nestedBodyEditor2["representation"] = bodyBodyEditor2Representation
						}
						if bodyBodyEditor2Value != "" {
							nestedBodyEditor2["value"] = bodyBodyEditor2Value
						}
						if len(nestedBodyEditor2) > 0 {
							nestedBody["editor2"] = nestedBodyEditor2
						}
					}
					{
						nestedBodyExportView := map[string]any{}
						if bodyBodyExportViewRepresentation != "" {
							nestedBodyExportView["representation"] = bodyBodyExportViewRepresentation
						}
						if bodyBodyExportViewValue != "" {
							nestedBodyExportView["value"] = bodyBodyExportViewValue
						}
						if len(nestedBodyExportView) > 0 {
							nestedBody["export_view"] = nestedBodyExportView
						}
					}
					{
						nestedBodyStorage := map[string]any{}
						if bodyBodyStorageRepresentation != "" {
							nestedBodyStorage["representation"] = bodyBodyStorageRepresentation
						}
						if bodyBodyStorageValue != "" {
							nestedBodyStorage["value"] = bodyBodyStorageValue
						}
						if len(nestedBodyStorage) > 0 {
							nestedBody["storage"] = nestedBodyStorage
						}
					}
					{
						nestedBodyStyledView := map[string]any{}
						if bodyBodyStyledViewRepresentation != "" {
							nestedBodyStyledView["representation"] = bodyBodyStyledViewRepresentation
						}
						if bodyBodyStyledViewValue != "" {
							nestedBodyStyledView["value"] = bodyBodyStyledViewValue
						}
						if len(nestedBodyStyledView) > 0 {
							nestedBody["styled_view"] = nestedBodyStyledView
						}
					}
					{
						nestedBodyView := map[string]any{}
						if bodyBodyViewRepresentation != "" {
							nestedBodyView["representation"] = bodyBodyViewRepresentation
						}
						if bodyBodyViewValue != "" {
							nestedBodyView["value"] = bodyBodyViewValue
						}
						if len(nestedBodyView) > 0 {
							nestedBody["view"] = nestedBodyView
						}
					}
					{
						nestedBodyWiki := map[string]any{}
						if bodyBodyWikiRepresentation != "" {
							nestedBodyWiki["representation"] = bodyBodyWikiRepresentation
						}
						if bodyBodyWikiValue != "" {
							nestedBodyWiki["value"] = bodyBodyWikiValue
						}
						if len(nestedBodyWiki) > 0 {
							nestedBody["wiki"] = nestedBodyWiki
						}
					}
					if len(nestedBody) > 0 {
						body["body"] = nestedBody
					}
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyLabels != "" {
					var parsedLabels any
					if err := json.Unmarshal([]byte(bodyLabels), &parsedLabels); err != nil {
						return fmt.Errorf("parsing --labels JSON: %w", err)
					}
					body["labels"] = parsedLabels
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				{
					nestedSpace := map[string]any{}
					if bodySpaceKey != "" {
						nestedSpace["key"] = bodySpaceKey
					}
					if len(nestedSpace) > 0 {
						body["space"] = nestedSpace
					}
				}
				if bodyTemplateId != "" {
					body["templateId"] = bodyTemplateId
				}
				if bodyTemplateType != "" {
					body["templateType"] = bodyTemplateType
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "wiki", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "wiki", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "wiki",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "wiki", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyBodyAnonymousExportViewRepresentation, "body-anonymous-export-view-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyAnonymousExportViewValue, "body-anonymous-export-view-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyAtlasDocFormatRepresentation, "body-atlas-doc-format-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyAtlasDocFormatValue, "body-atlas-doc-format-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyEditorRepresentation, "body-editor-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyEditorValue, "body-editor-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyEditor2Representation, "body-editor2-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyEditor2Value, "body-editor2-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyExportViewRepresentation, "body-export-view-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyExportViewValue, "body-export-view-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyStorageRepresentation, "body-storage-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyStorageValue, "body-storage-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyStyledViewRepresentation, "body-styled-view-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyStyledViewValue, "body-styled-view-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyViewRepresentation, "body-view-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyViewValue, "body-view-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyBodyWikiRepresentation, "body-wiki-representation", "", "The content format type. Set the value of this property to the name of the format being used, e.g. 'storage'.")
	cmd.Flags().StringVar(&bodyBodyWikiValue, "body-wiki-value", "", "The body of the content in the relevant format.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the template.")
	cmd.Flags().StringVar(&bodyLabels, "labels", "", "Labels for the template.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the template. Set to the current `name` if this field is not being updated.")
	cmd.Flags().StringVar(&bodySpaceKey, "space-key", "", "Key")
	cmd.Flags().StringVar(&bodyTemplateId, "template-id", "", "The ID of the template being updated.")
	cmd.Flags().StringVar(&bodyTemplateType, "template-type", "", "The type of the template. Set to `page`.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
