// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWorkflowschemeDefaultCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "default",
		Short: "Get, update, and delete default for workflowscheme",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWorkflowschemeDefaultDeleteWorkflowCmd(flags))
	cmd.AddCommand(newWorkflowschemeDefaultGetWorkflowCmd(flags))
	cmd.AddCommand(newWorkflowschemeDefaultUpdateWorkflowCmd(flags))
	return cmd
}
