// Copyright 2026 smashingtags. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL                   string            `toml:"base_url" json:"base_url,omitempty"`
	AuthHeaderVal             string            `toml:"auth_header" json:"auth_header,omitempty"`
	Headers                   map[string]string `toml:"headers,omitempty" json:"headers,omitempty"`
	AuthSource                string            `toml:"-" json:"-"`
	AccessToken               string            `toml:"access_token" json:"access_token,omitempty"`
	RefreshToken              string            `toml:"refresh_token" json:"refresh_token,omitempty"`
	TokenExpiry               time.Time         `toml:"token_expiry" json:"token_expiry,omitempty"`
	ClientID                  string            `toml:"client_id" json:"client_id,omitempty"`
	ClientSecret              string            `toml:"client_secret" json:"client_secret,omitempty"`
	Path                      string            `toml:"-" json:"-"`
	JiraCloudPlatformUsername string            `toml:"cloud_platform_username" json:"username,omitempty"`
	JiraCloudPlatformPassword string            `toml:"cloud_platform_password" json:"password,omitempty"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://your-domain.atlassian.net",
	}

	// Resolve config path: explicit flag > env var > ~/.config/keen/ > legacy path
	path := configPath
	if path == "" {
		path = os.Getenv("JIRA_PP_CLI_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		keenJSON := filepath.Join(home, ".config", "keen", "auth.json")
		keenTOML := filepath.Join(home, ".config", "keen", "config.toml")
		legacyTOML := filepath.Join(home, ".config", "jira-pp-cli-pp-cli", "config.toml")
		switch {
		case fileExists(keenJSON):
			path = keenJSON
		case fileExists(keenTOML):
			path = keenTOML
		case fileExists(legacyTOML):
			path = legacyTOML
		default:
			path = filepath.Join(home, ".config", "keen", "config.toml")
		}
	}
	cfg.Path = path

	// Try to load config file (JSON or TOML based on extension)
	data, err := os.ReadFile(path)
	if err == nil {
		if strings.HasSuffix(path, ".json") {
			if err := json.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parsing config %s: %w", path, err)
			}
		} else {
			if err := toml.Unmarshal(data, cfg); err != nil {
				return nil, fmt.Errorf("parsing config %s: %w", path, err)
			}
		}
	}

	// Env var overrides
	if v := os.Getenv("JIRA_CLOUD_PLATFORM_USERNAME"); v != "" {
		cfg.JiraCloudPlatformUsername = v
		cfg.AuthSource = "env:JIRA_CLOUD_PLATFORM_USERNAME"
	}
	if v := os.Getenv("JIRA_CLOUD_PLATFORM_PASSWORD"); v != "" {
		cfg.JiraCloudPlatformPassword = v
		cfg.AuthSource = "env:JIRA_CLOUD_PLATFORM_PASSWORD"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.JiraCloudPlatformUsername != "" {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.JiraCloudPlatformPassword != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("JIRA_PP_CLI_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	if c.JiraCloudPlatformUsername == "" || c.JiraCloudPlatformPassword == "" {
		return ""
	}
	credentials := c.JiraCloudPlatformUsername + ":" + c.JiraCloudPlatformPassword
	return "Basic " + base64.StdEncoding.EncodeToString([]byte(credentials))
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

// SaveCredential persists a single API credential to the field that
// AuthHeader() consults for api_key auth. Writing to AccessToken (the
// bearer slot) would silently no-op since AuthHeader() reads the env-var-
// derived field, not AccessToken, when Auth.Type == "api_key".
//
// The clears precede the assignment so a canonical env-var whose placeholder
// collides with a builtin tag (e.g. an env var named XXX_ACCESS_TOKEN
// resolving to the AccessToken field) ends up holding the new token.
func (c *Config) SaveCredential(token string) error {
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.JiraCloudPlatformUsername = token
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.JiraCloudPlatformUsername = ""
	c.JiraCloudPlatformPassword = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll
